### ISSUE TITLE
User guide missing axes page

### ISSUE THREAD

**Issue by adiep2501** [altair-viz/altair#1041]
I was looking at changing the name of my axes. I found that [Chart().configure()](https://altair-viz.github.io/user_guide/configuration.html?highlight=configure#config-chart) could be useful. But the link for [axe configuration is dead](https://altair-viz.github.io/user_guide/axis.html).

There are a lot of basic recipes that I find missing like sorting the x axis based on the y axis. Maybe I could raise an issue and add my own recipes?

**Comment by jakevdp** [comment]
Thanks – this is a known issue and has been fixed in the master branch. The links on the website will be fixed when we do the next release.

Regarding basic recipes – yes, we'd welcome any additional documentation. If you're willing to contribute, a section on sorting could fit well here: https://github.com/altair-viz/altair/blob/master/doc/user_guide/customization.rst

**Comment by adiep2501** [comment]
So if I wanted to upload my examples, I just pull and push changes to that specific doc?

**Comment by adiep2501** [comment]
Fixed in master.

**Comment by jakevdp** [comment]
> So if I wanted to upload my examples, I just pull and push changes to that specific doc?

Yes, you can open a pull request with changes to that RST source. Once those changes make it into a release, it will be pushed to http://altair-viz.github.io/
