### ISSUE TITLE
"anyOf" syntax in API documentation is too techie and difficult for n00bs 

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#1051]
The screenshot below shows the current [API documentation](https://altair-viz.github.io/user_guide/API.html) for the X class. Each keyword argument accepted by X is listed in a table. The data types allowed by each input are the first item in the definition, often structured in an "anyOf" statement like "(anyOf(string, RepeatRef))" or "(anyOf(boolean, BinParams))".

![screenshot from 2018-07-27 11-13-46](https://user-images.githubusercontent.com/9993/43339418-23e93ffe-918e-11e8-8ddf-e6e9dc6b79ec.png)

We agree that it is crucial to provide this information in the docs, and its position at the beginning of each entry is welcome. However, the "anyOf" syntax is arcane and might be offputting to beginners. We propose restructuring those docs, if possible, to have a more humanized appearance. This could take the form of a separate column with a header explaining these are the acceptable inputs. Or perhaps more humanized structuring of the list with commas and a conjunction like "and" before the final item.

Additionally, it would be an excellent addition, IMHO, if classes listed in those lists (like BinParams or Axis) linked directly to their documentation. 

Sincerely yours!

Dedicated Altair users,

@palewire and @irisslee

**Comment by jakevdp** [comment]
Agreed – keep in mind that these docs are automatically generated from the vega-lite schema, so it's not as easy as just editing a text file.

The relevant code is here: https://github.com/altair-viz/altair/blob/55ff81d4bdbf69e275a4d1afe6cb6eca4a4daa97/tools/schemapi/utils.py#L185-L187

And note also that we need to be careful about how we represent this, because it could be nested. So for example, if you choose to describe ``anyOf(float, int)`` with prose, such as ``"either float or int``, then ``anyOf(anyOf(bool, float), int)`` will parse as ``either either bool or int or int``

**Comment by jakevdp** [comment]
To link classes to the documentation would require making schemapi aware of sphinx, which it is not at the moment.

**Comment by jakevdp** [comment]
If you want to change the format of how the attributes are presented, that would involve writing a custom [sphinx autodoc extension](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html). Currently we're using the default output.

**Comment by jakevdp** [comment]
I don't see any easy solution, and I don't think I'll have the bandwidth to tackle any of this, but if someone else would like to take a look I'd support that.

**Comment by jakevdp** [comment]
(I think that effort would be much better spent in improving the rest of the docs... the API docs are meant to be very low-level)

**Comment by kanitw** [comment]
FYI, we also had to implement [a custom template](https://github.com/vega/vega-lite/blob/master/_includes/type.html) for output nice typings in Vega-Lite docs too (using Jekyll template).

Given Altair is not using Jekyll, it might not be directly useful. But it might still be a useful reference if someone wanna replicate the logic for a custom sphinx autodoc extension. :)

**Comment by jakevdp** [comment]
Yeah, we have a couple more levels of indirection in Altair... the schemapi tool is used to parse the vega-lite schema and generate Python classes with appropriate docstrings, and those docstrings are parsed by sphinx-autodoc to create the HTML pages.

**Comment by jakevdp** [comment]
FYI: in #1063 I changed the code generation so that definitions in generated API tables will include a link to the object.

Regarding the ``anyOf(x,y)``, I can't think of any decent alternative. You said the syntax is too confusing... what is confusing about it? Can you think of an alternative way of expressing that a variable can be one of a number of specific types that you would not find confusing, and that would not require substantially changing the HTML layout with a custom sphinx extension?

**Comment by palewire** [comment]
I think it's a little too computer-programmy. I had a newbie use ask me what it was. They weren't familiar with the concept of `anyOf`. Something a little more like a textbook might be nice.

**Comment by jakevdp** [comment]
Any suggestions?

**Comment by irisslee** [comment]
Newbie here. What about simple change in wording from `anyOf(x,y)` to something like `One of (x or y)` ? This way, even when it's nested, `anyOf(anyOf(bool, float), int)` can be `One of(One of (bool or float) or int)`. It's a small change, but I think it's more straightforward, and closer to `either, or` language. 

Or, what about creating a third column in the current two column  documentation? (@palewire and I have discussed this) Right now there is a column for the keyword argument and another for description. If we can create a column in between that simply lists the input types the argument takes, it would be even better IMHO.

**Comment by jakevdp** [comment]
I don't think this is going to change at this point, for the reasons discussed above.
