### ISSUE TITLE
String Labels next to quantities on Y Axis

### ISSUE THREAD

**Issue by jmansilla** [altair-viz/altair#1067]
Hi!

I want to add some extra labels to the axis, but preserving the numerical ones (like the "safe", "neutral, "dangerous") seen on the attached example.

Is it something possible with altair?

![extralabels](https://user-images.githubusercontent.com/488675/43608577-ccafd010-9677-11e8-9750-fab742b94f84.png)

**Comment by jakevdp** [comment]
I don't know of an easy way to do this.

**Comment by jmansilla** [comment]
Too bad.

Thanks for the reply Jake. At least I'll stop investing time reading the docs :+1:

**Comment by Alcampopiano** [comment]
@jmansilla I know this is not exactly what you had asked but perhaps you could extend this example from the gallery:
https://altair-viz.github.io/gallery/bar_chart_with_highlight.html

**Comment by jmansilla** [comment]
Wow, thanks @Alcampopiano !!!

Worked like a charm!

```
def threshold_artifacts():
    thresholds = pd.DataFrame([
        {"th_value": MAX_VALUE, "th": "mandatorish"},
        {"th_value": MAX_VALUE/2, "th": "interesting"},
        {"th_value": MAX_VALUE/-2, "th": "⭡ cost, ⭣ value"},
        {"th_value": -MAX_VALUE, "th": "nonsense"},
    ])

    rules = alt.Chart(thresholds).mark_rule().encode(
        y='th_value:Q',
        color=alt.value('#224455'),
        opacity=alt.value(0.5)
    )

    text = alt.Chart(thresholds).mark_text(
        align='left', dx=-290, dy=-5
    ).encode(
        alt.Y('th_value:Q'),
        text='th',
        opacity=alt.value(0.5)
    )

    return rules + text
```

![screenshot from 2018-08-16 10-14-19](https://user-images.githubusercontent.com/488675/44210565-3a6b7d00-a13d-11e8-9b78-5ccb15879ea2.png)

**Comment by Alcampopiano** [comment]
Awesome. Glad to hear it!

**Comment by jakevdp** [comment]
@jmansilla would you be willing to submit a chart like this one as an example for the documentation?

**Comment by jmansilla** [comment]
@jakevdp I'm flattered

Can you help me a bit? Where should I make the submission?

**Comment by jakevdp** [comment]
Sure! You can add an example by opening a pull request to add a new file to ``altair/vegalite/v2/examples/``

It's easiest to work from another example as a template; for example this one: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/simple_scatter.py

The requirements are:

1. a descriptive doc string
2. a comment specifying the category (used to construct the website gallery)
3. the last line of the script should evaluate to the chart you create

Let me know if you have any questions

**Comment by joelostblom** [comment]
Just for reference, you can now achieve something similar to the original ask here [by using the axis param `labelExpr` with a conditional vega expression, example here](https://github.com/vega/vega-lite/issues/7045).

**Comment by ogencoglu** [comment]
Coming back to slightly similar issue. I would like to show the log axis labels in `10 to the power` format instead of scientific notation `1e+22`.

My current hack is:
```
y=alt.Y(
f'{y_axis}:Q',
scale=alt.Scale(type="log"),
axis=alt.Axis(format=".0g", labelExpr='"10^" + round(log(datum.value) / LN10)')),
```
where I use `labelExpr`,  treat the sign `10^` as a string and try to get the actual value matching with logarithm hacks. It is not a pretty approach nor a pretty sight. Any suggestions?

![image](https://user-images.githubusercontent.com/8182738/215892738-3ba19ce5-7287-41c8-a2e2-7f7f81e831ad.png)

**Comment by mattijn** [comment]
Under the hood this is delegated to 'd3 format'.
You might want to search for 'd3 format superscript'. I found some info on formatPower and poweroften, but I did not find better approaches than what you currently have. 

If you do find some, please report back. That will be much appreciated. Good luck 👍

**Comment by ChristopherDavisUCI** [comment]
@ogencoglu Is this useful at all? https://stackoverflow.com/a/19062994 

I haven't thought about it carefully, was just browsing and thought this seemed relevant.  I'm surprised this functionality doesn't already exist!

**Comment by mattijn** [comment]
btw, I just remember something from 4 years ago that I'd made in one of the previous versions of Vega: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhA4kAE3k1xZNAJlIGmNhBoAvOGlkLpIAO4159NQAYbM+DTJY0AJgCMM+UkwpUAbVBxJARDdDEGACcoQxkogBsjLFx8IlIKajpGFnZeCgBaeLo4Am9fTm0oAGsISigIYlMAMzZI5Ew0UEwATxwwkHrGmTlIiDDQHEiaGKNxBgQmOEiQAF8vOCKEYuX0GRW1oJD++KRuti1TYiR4hjgINECQAH1LNAA2AA43mV0yYMT0BYrDBTI5nB1UB4VgBdGEyZCRGoPQ6hIzIZSmHp9IxkSLnHDNPEITogMp+EAnM4XNYgODiKBseTjEAMHBlZlA6yoUC-f5GTkgmlglzckC865JOBOFz7GkIpEBFH9eX3GRY-qROBQDoyPHxfqYaZVQlsYmislGCLRQw0ukMpkk1nskkADygJOg136LuaNA28iMk2mNpk3XdoquNzC7hslAENIFJMjtzQ7iFUvBSeuKdQ7gALDS2HIoHRulmo2hYwB2GlNGjxAGgZP9ADEec+riYedWsuhPygXvuipAwVR6B9at6xzYqi8pqQGICsbsNk8MZXfZAkSQKjC-nsPKcfMBlmscK353EAdQmEitxk4mDaFvtwOI6OloH+qeDPEpEiOogOqRj0JqEAwGw8QBnO6KSAEIDuHA+QxqYiH5AAnKhSEfFh+RVrhby4QIuHdjIaEAMy4a4uHuFhADUNhYbRZFwNRLGUSxpEIXAxEsYRLH4SxOEsZhLEoZu267g8CE2IA3gQAJ2AI4EqFyfJgAOBCpsmAJ4EmmAB4EmmAO4EmmAG4EmmAK4EmmAC4EmkAM2aQATZp8kqRpZE2M5bmOW5dludZbkWW5pluUZbn6W5OmwpuSAuncyJil+3rNK07RGLGiGmK0friBCIBMGw2CmpiRoAMKXhC6hAXQ+pGJEgCSuJggAmuJEgBcuAABDggCJBFMgBKuIAErimHoyhMj6uYyHajLMoa1RDqATo+MyEC3mwVTMs2RgtlAm1basPxLStADqp4ghG2bRnGsoyCcizxDNIDKJgSxINqNCkM+d5wHEbLzSSO5kNVJ0VqgNg0tcR7ljmW7Sh0NIPS6EI8gln5ej+Ej-oBdb+kYa00vII1NqdqbAzILTZQAyvoq0E7mriyvsUgI16RgThSSDXUOTTXGMMi4q8N7vTImV0jleUFcSapGuznMfSAg1XnAI3A5FKxAA)
<img width="536" alt="image" src="https://user-images.githubusercontent.com/5186265/216441017-2bc74507-6e66-4b8c-9cd5-ae31201dc7f7.png">
The spec still works, maybe this can be used to find the solution for Vega-lite, which then can be applied to altair

**Comment by ogencoglu** [comment]
Btw I [found a bug](https://github.com/vega/vega-lite/issues/8691) of using `slice` method of `LabelExpr` and zoom for the interested.

**Comment by ogencoglu** [comment]
Thanks @mattijn . At this point zoom is much higher priority than 10 to the power notation for me. I will keep tinkering.

**Comment by ogencoglu** [comment]
I cracked it and it works with zoom!

![image](https://user-images.githubusercontent.com/8182738/216480070-c838c73d-fa1e-473d-96fe-f8a027c65fe0.png)


**Here is the expression from hell:**
`"if(isValid(toString(datum.label)), if(substring(toString(datum.label), 0, 1)==1, '10' + if(slice(toString(datum.label), 2, 3)=='-', '⁻', '⁺') + if(length(slice(toString(datum.label),3))==1, ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)],'') + if(length(slice(toString(datum.label),3))==2, ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[0]] + ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[1]],'') + if(length(slice(toString(datum.label),3))==3, ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[0]] + ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[1]] + ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[2]],''), substring(toString(datum.label), 0, 1) + '×10' + if(slice(toString(datum.label), 2, 3)=='-', '⁻', '⁺') + if(length(slice(toString(datum.label),3))==1, ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)],'') + if(length(slice(toString(datum.label),3))==2, ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[0]] + ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[1]],'') + if(length(slice(toString(datum.label),3))==3, ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[0]] + ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[1]] + ['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][slice(toString(datum.label),3)[2]],'')), '')"`

**Working example:**

```
df = pd.DataFrame({'X': np.arange(-30, 30), 'Y':np.power(10, np.arange(-30.0, 30.0))})

# signs
superscript_minus = '⁻'
superscript_plus = '⁺'
multiplication_sign = "×"
mapping = "['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹']"

# extractions from the original label
first_letter = 'substring(toString(datum.label), 0, 1)'
exponent = "slice(toString(datum.label),3)"
len_exponent = f"length({exponent})"
sign = "slice(toString(datum.label), 2, 3)"

# conditions & labels
if_sign_minus = f"if({sign}=='-', '{superscript_minus}', '{superscript_plus}')"
if_len_exponent1 = f"if({len_exponent}==1, {mapping}[{exponent}],'')"
if_len_exponent2 = f"if({len_exponent}==2, {mapping}[{exponent}[0]] + {mapping}[{exponent}[1]],'')"
if_len_exponent3 = f"if({len_exponent}==3, {mapping}[{exponent}[0]] + {mapping}[{exponent}[1]] + {mapping}[{exponent}[2]],'')"
label_if_first_letter_is_one = f"'10' + {if_sign_minus} + {if_len_exponent1} + {if_len_exponent2} + {if_len_exponent3}"
label_if_first_letter_is_not_one = f"{first_letter} + '{multiplication_sign}10' + {if_sign_minus} + {if_len_exponent1} + {if_len_exponent2} + {if_len_exponent3}"
if_first_letter = f"if({first_letter}==1, {label_if_first_letter_is_one}, {label_if_first_letter_is_not_one})"

expression = f"if(isValid(toString(datum.label)), {if_first_letter}, '')"

points = alt.Chart(df).mark_point(size=60).encode(
    x=alt.X('X:Q'),
    y=alt.Y('Y:Q', scale=alt.Scale(type="log"), axis=alt.Axis(format=".0e", labelExpr=expression)),
).add_selection(
    alt.selection_interval(bind='scales'),
)
points
```

**Breakdown:**
- Original labels are in the format `1e-20`, `1e+5` etc. when `axis=alt.Axis(format=".0e")`. But when it is zoomed in, the following can also appear `3e-3` or `8e+5`.
- `mapping` is an array that we can index (`5` becomes `⁵`). We perform this mapping as many times as the length of the `exponent` (`for` loops are not allowed!). so `23` becomes `²³`. Limited to 3 digit exponents so max is `10⁹⁹⁹`.
- if `first_letter` is `1` we go with `10⁶` format, otherwise we go with `3×10⁶`
- a certain level of zoom do not show any labels. To prevent the whole thing crashing, we need to check if original label is even visible (valid) by `isValid(toString(datum.label))` statement.
