### ISSUE TITLE
Adding text to stacked bar charts

### ISSUE THREAD

**Issue by tzbaris** [altair-viz/altair#1147]
Hi, 

I was wondering how we can add text to stacked bar charts that have differing lengths. I've found this image online but it only has html code for vega-lite. Is there a way to implement this in Altair? 

![image](https://user-images.githubusercontent.com/6526450/46107215-c9da6600-c1a8-11e8-9554-d1c87617cc5b.png)

**Comment by Alcampopiano** [comment]
@tzbaris  If the issue is how to get the text marks positioned on their respective segments, I usually write a python function to calculate the midpoints of each segment. Then, I add a column to my DataFrame to use as the position of the text mark (so the X position in this case). You can change the `align` property of the text mark to shift the marks to the right or left.

```python
df=pd.DataFrame({'Org': ['school','school','school','school', 'board', 'board', 'board', 'board'],
                 'variable': ['rose', 'dropped', 'maintained', 'failed','rose', 'dropped', 'maintained', 'failed'],
                'percent': [25,25,25,25,25,25,25,25], 
                 'position': [12.5, 37.5,62.5, 87.5,12.5, 37.5,62.5, 87.5]})
    
bars=alt.Chart().mark_bar().encode(
    x=alt.X('sum(percent)', title='Percentage of Students'),
    y=alt.Y('Org', sort=['school'], title=None),
    color=alt.Color('variable', title=None),
    order='junk:Q'
)

text=alt.Chart().mark_text(align='center', baseline='middle').encode(
    y=alt.Y('Org', sort=['school'], title=None),
    x='position',
    text='percent')

alt.layer(bars, text, data=df)

```


![im](https://user-images.githubusercontent.com/4624246/46144458-fe8f0180-c22a-11e8-9757-91236afe16ab.png)

**Comment by tzbaris** [comment]
@Alcampopiano 
Thanks for your reply. I guess what I'm struggling with is that I have different lengths of bars, so a universal 'position' won't exist. How would I specify the position of the text for each bar differently?

**Comment by Alcampopiano** [comment]
Perhaps I don't understand your question but in my example the position *is* explicitly set for each bar segment. This is why it does not matter if the segments or full bars have different lengths. Here is another example where segments and bars are different lengths.

df=pd.DataFrame({'Org': ['school','school','school','school', 'board', 'board', 'board', 'board'],
                 'variable': ['rose', 'dropped', 'maintained', 'failed','rose', 'dropped', 'maintained', 'failed'],
                'percent': [25,35,25,45,25,25,25,25], 
                 'position': [12.5, 42.5, 72.5, 107.5, 12.5, 37.5,62.5, 87.5]})

    
bars=alt.Chart().mark_bar().encode(
    x=alt.X('sum(percent)', title='Percentage of Students'),
    y=alt.Y('Org', sort=['school'], title=None),
    color=alt.Color('variable', title=None),
    order='junk:Q'
)

text=alt.Chart().mark_text(align='center', baseline='middle').encode(
    y=alt.Y('Org', sort=['school'], title=None),
    x='position',
    text='percent')

alt.layer(bars, text, data=df)
![visualization 49](https://user-images.githubusercontent.com/4624246/46147578-dc4db180-c233-11e8-9866-5ffd915810fc.png)

**Comment by tzbaris** [comment]
@Alcampopiano 
Oh I see now, my mistake! Would you be able to share the code you used to calculate the midpoints by any chance? Thank you!

**Comment by Alcampopiano** [comment]
Something like this for every bar. 

```python
def calc_midpoints(y):
    x=[]
    for i in range(len(y)):
        trailing_quant=y[:i]
        x.append(y[i]/2 + sum(trailing_quant))
        
    return x


y=[25,35,25,45]
x=calc_midpoints(y)
```
```
print(x)
[12.5, 42.5, 72.5, 107.5]
```

**Comment by jakevdp** [comment]
@tzbaris If you can share the vega-lite code for the original plot, I can translate it to the altair code for you.

**Comment by tzbaris** [comment]
@jakevdp 
I've pasted the code below but I got it from this site: https://bl.ocks.org/pratapvardhan/00800a4981d43a84efdba0c4cf8ee2e1

{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "https://vega.github.io/editor/data/barley.json"},
  "width": 500, "height": 250,
  "resolve": {"scale": {"color": "independent"}},
  "layer": [
     {"mark": "bar",
      "encoding": {
        "x": {"aggregate": "sum", "field": "yield", "type": "quantitative", "stack": "zero"},
        "y": {"field": "variety", "type": "nominal"},
        "color": {"field": "site", "type": "nominal"}}
     },
     {"mark": {"type": "text", "dx": -15, "dy": 3},
      "encoding": {
        "x": {"aggregate": "sum", "field": "yield", "type": "quantitative", "stack": "zero"},
        "y": {"field": "variety", "type": "nominal"},
        "color": {"field": "site", "type": "nominal", "scale": {"range": ["white"]}, "legend": null},
        "text": {"aggregate": "sum", "field": "yield", "type": "quantitative", "format": ".1f"}}
    }
  ]
}

**Comment by Alcampopiano** [comment]
@tzbaris @jakevdp 

To save Jake the time, and yes this is a much better way to do it.



```python
import altair as alt
import pandas as pd
from vega_datasets import data

df=data.barley()

bars=alt.Chart().mark_bar().encode(
    x=alt.X('sum(yield)',stack='zero'),
    y=alt.Y('variety'),
    color=alt.Color('site')
)

text=alt.Chart().mark_text(dx=-15, dy=3).encode(
    y=alt.Y('variety'),
    x=alt.X('sum(yield)',  stack='zero'),
    color=alt.Color('site', legend=None, scale=alt.Scale(range=['white'])),
    text=alt.Text('sum(yield)',format='.1f')
)

alt.layer(bars, text, data=df).resolve_scale(color='independent')
```
![visualization 51](https://user-images.githubusercontent.com/4624246/46157353-87b53100-c249-11e8-8e15-eb0696072b71.png)

**Comment by dejmail** [comment]
Does this also apply for layered, faceted stacked barplots ?

```
stacked_bar = alt.Chart().mark_bar().encode(
    alt.X('Strand:N'),
    alt.Y('percent:Q'),
    color=alt.Color('rntp:N')
)

text=alt.Chart().mark_text(
        align='center',
        baseline='middle',
    ).encode(
        y = alt.Y('percent'),
        x = alt.X('Strand:N'),
        text=alt.Text('percent:Q',format='.1f')
)

alt.layer(stacked_bar, text, data=data).facet(
    column='organ:N',
    row='age:N'
)
```

produces 

![example](https://user-images.githubusercontent.com/1876487/54280672-4cf54a00-4598-11e9-9455-fa7980acab03.png)

I cannot quite seem to get it to place the labels in the correct position. Adjusting the dx and dy just moves the whole group of numbers.

**Comment by jakevdp** [comment]
The issue is that your bars are stacked (so the top of bar `a` is at position `y = a + c + g + t`), while your text is not stacked, so the text for `a` is at position `y = a`.

Unfortunately, in the current version of Altair there's no easy way to stack the text encoding, aside from computing the stacked values as part of the input data. In Altair 3.0, you'll be able to do this within the chart spec using a Stack Transform (here's the vega-lite docs for this transform: https://vega.github.io/vega-lite/docs/stack.html).

**Comment by jakevdp** [comment]
Live example is here: https://altair-viz.github.io/gallery/stacked_bar_chart_with_text.html

**Comment by armsp** [comment]
@Alcampopiano @jakevdp  this works well when the stack is `zero`, but fails when the stack is `normalize`, the text starts gettng in other areas. Since `dx` is kind of an absolute value, playing around with it doesn't help because if it works for one of the bars, then it will fail for another one. Is there a way to do this for `normalize` bars or do I have to calculate the midpoints and add them as data points?

**Comment by armsp** [comment]
@jakevdp @Alcampopiano any luck with the above?

**Comment by ckchandler** [comment]
Would the code supplied by @Alcampopiano work the same when using a transform_fold? Since my data is wide form I have to use a transform fold on both the values rendered in the bars/the text AND with the positions. For some reason when using the code above, both the position and the real value are displaying overlayed in my chart and I can't quite figure out where this is coming from?

```
small_df = pd.DataFrame({'Probability A':[0.2,0.8,0.4],'Probability B':[0.5,0.1,0.1],'Probability C':[0.3,0.1,0.5],'ID':['John','Sally','Frank'], 'position a': [0.1, 0.6, 0.2], 'position b': [0.45,0.85,0.45], 'position c': [0.85,0.95,0.75]})

base = alt.Chart(small_df)

bar = base.mark_bar().transform_fold(
        ['Probability A','Probability B','Probability C']
    ).encode(
        x=alt.X('value:Q',scale=alt.Scale(domain=[0, 1])),
        y='ID:N',
        color=alt.Color('key:N'),
    )

text = base.mark_text().transform_fold(
        ['Probability A', 'Probability B', 'Probability C'],
        as_ = ['key_x', 'value_x']
    ).transform_fold(
        ['position a', 'position b', 'position c'],
        as_ = ['key_y', 'value_y']
    ).encode(
        y=alt.Y('ID:N'),
        x=alt.X('value_y:Q'),
        text=alt.Text('value_x:Q',format='.2f')
    )

alt.layer(bar, text, data=small_df)
```

![visualization - 2022-11-02T105851 825](https://user-images.githubusercontent.com/10505527/199553743-f2eba57d-6214-4dab-a47c-1e8a3b3a41a3.png)
