### ISSUE TITLE
selection: getting selected data 

### ISSUE THREAD

**Issue by eamonnmag** [altair-viz/altair#1153]
Is there a way, given a selection to give back the selected data as a dataframe for example?

**Comment by Alcampopiano** [comment]
I've never seen that in Altair but perhaps Jake knows a way. Something similar might be to have the selection displayed as a table (like a heat map but with text marks in the cells), but I know this is not exactly what you are asking.

[sort of like this](https://altair-viz.github.io/gallery/layered_heatmap_text.html)

**Comment by jakevdp** [comment]
No, there's no easy way to do that at the moment.

If you write a custom javascript frontend, it is theoretically possible via the [vega view](https://github.com/vega/vega-view) api, but I don't know of any example of that.

Making this easier is on the Vega-Lite roadmap, and once it's developed there we can think about how to support it from the Python side.

**Comment by yassersouri** [comment]
It would be nice to use the altair chart as a way to let user select input for some other part of code.

Currently I am using streamlit and such a usecase is coming up but I cannot really do anything about it.

**Comment by jakevdp** [comment]
Yes, it would be nice, and no, there is still no way to do this, because the selection happens in the Javascript layer and there is no mechanism for the Javascript to communicate back to Python. Enabling this would require changes to Altair, vega-embed, the vega IPython extension, and the vega Jupyter extension. I don't know of anybody working on this – if it's important to you, you might consider exploring what it would take.

**Comment by joelostblom** [comment]
@eamonnmag It is not currently possible to emit signals from Altair/VegaLite to Ipywidgets (or any other widget framework). There is some work on this for Jupyter in https://github.com/yifanwu/b2 and for Streamlit in https://github.com/streamlit/streamlit/issues/2263.

Since this is not an issue that Altair can solve, would you mind closing this issue and continue discussion in one of the links above or on the Vega-Lite issue tracker?

**Comment by Z-Shakeri** [comment]
This did the trick for me: https://stackoverflow.com/questions/64565901/how-to-retrieve-attributes-from-selected-datum-in-altair
However, you need to serve the chart in Streamlit to be able to use this solution.

**Comment by joelostblom** [comment]
The capability to listen to Vega events and define custom callback for e.g. selected points was recently merged in Panel and will likely be included in their next major release, exciting! https://github.com/holoviz/panel/pull/2592

![image](https://user-images.githubusercontent.com/1550771/127645541-5476d06e-d217-4285-93ef-aaa76e1470ca.gif)

**Comment by jonmmease** [comment]
This functionality will be available in Altair 5.1 using the `JupyterChart` jupyter widget added in https://github.com/altair-viz/altair/pull/3119.  This will work in all environments that support Jupyter Widgets (classic jupyter notebook, jupyter lab, colab, visual studio code, and others).

Other dashboard toolkits that want to provide this functionality will need to implement it themselves, as Panel does.
