### ISSUE TITLE
Set Max Rows only for 1 Chart

### ISSUE THREAD

**Issue by CMCDragonkai** [altair-viz/altair#1180]
Is there a way to lift the max rows restriction just for 1 chart?

**Comment by Alcampopiano** [comment]
Perhaps you just turn it off then back on again?

```python
alt.data_transformers.enable('default', max_rows=None)

    alt.Chart(cars).mark_circle(size=60).encode(
        x='Horsepower',
        y='Miles_per_Gallon',
        color='Origin',
        tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
    ).interactive()

alt.data_transformers.enable('default', max_rows=5000)
.
.
.
```

**Comment by jakevdp** [comment]
You can use a context manager. e.g.
```python
chart = alt.Chart(cars)).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()

with alt.data_transformers.enable(max_rows=None):
    chart.display()
```

**Comment by CMCDragonkai** [comment]
The context manager is a good way to do it! But I'm wondering why this isn't just part of the chart options?

**Comment by jakevdp** [comment]
The chart object itself mirrors the Vega-Lite API, and the vega-lite API doesn't have any notion of limiting the size of the data it receives.

The reason the MaxRowsError is in place is that we found early on that people tended to crash their browser working with larger datasets because they didn't realize the way the library works under the hood. By making them explicitly disable that error, it's a barrier to ending up with notebooks that are too big for their browser to load.

Hope that makes sense.

**Comment by jakevdp** [comment]
In Altair 3.1 or newer, the clearer way to do this is
```python
with alt.data_transformers.disable_max_rows():
    chart.display()
```
