### ISSUE TITLE
easier saving of static charts?

### ISSUE THREAD

**Issue by jbloom** [altair-viz/altair#1187]
Forgive me if this is a silly question that betrays a lack of knowledge about the goals of Altair, but what are the prospects for easier methods of saving charts (ideally to PDF but at least to PNG or SVG)?

I know that the main goal of Altair is to generate images in Vega for use in Jupyter Labs, etc---and this is great, I can see the advantages of this in many contexts.

But for computational biology, it is also handy to be able to use similar code to that in my Jupyter notebooks in non-interactive Python scripts that generate static PDFs. I am struggling with the ease of saving static plots, and this makes Altair less useful for me than `ggplot2` or `plotnine`. It is possible to save these images (I've done this following the instructions), but it requires installation of non-Python programs which add a lot of overhead if you are trying to write Python code that non-experts can easily run on lots platforms.

So I guess my main question as I consider how much to switch my code over to Altair is as follows: is it likely that Altair will eventually have a simple pure Python way to save a static plot? Or is this not even a good question for some larger philosophical reason that I don't understand?

**Comment by jakevdp** [comment]
Altair is rendered with Vega, and vega currently supports PNG and SVG output. Vega is a javascript program, and so there is no way to render altair visualizations without running javascript: that means the options are opening your web browser and running that javascript by clicking a button, or using a headless web browser to run that javascript programmatically.

Theoretically it might be possible to write a Python interpreter/renderer for vega-lite so that figures could be saved without having to call-out to javascript, but I don't know of any serious efforts toward something like that.

Hope that helps.
