### ISSUE TITLE
Improve documentation for window transform?

### ISSUE THREAD

**Issue by kanitw** [altair-viz/altair#1301]
A user on Stackoverflow seems to have trouble with it 

https://stackoverflow.com/questions/53972616/is-it-possible-to-create-custom-aggregations-that-work-with-selection-filters-in/53987549?noredirect=1#comment95279328_53987549

**Comment by jakevdp** [comment]
Yes, I think this could be improved :smile:

**Comment by iaindillingham** [comment]
I'd like to help with this, as I've benefited from a discussion on the Slack channel about window transforms. I'll try and devote a couple of hours this week (28 January) to it.

**Comment by jakevdp** [comment]
That would be great – thanks! The relevant section to add to is here: https://github.com/altair-viz/altair/blob/master/doc/user_guide/transform.rst#window-transform

Or if you develop some good self-contained examples, they can go here: https://github.com/altair-viz/altair/tree/master/altair/examples

**Comment by iaindillingham** [comment]
Would you object to me replacing the activities example in the Altair documentation with the IMDB example from the Vega-Lite documentation, @jakevdp?
```python
import altair as alt
from vega_datasets import data

movies = data.movies()

alt.Chart(movies).transform_window(
    cumulative_count='count(count)',
    sort=[{'field': 'IMDB_Rating'}],
    frame=[None, 0],
).mark_area().encode(x='IMDB_Rating:Q', y='cumulative_count:Q')
```
As well as a more realistic example, it uses only a window, rather than a calculate and window, and so it conceptually simpler. By replacing the activities example with the IMDB example, we'd save space, which I could use to explain the kwargs.
