### ISSUE TITLE
plots not rendering in vscode with python extension

### ISSUE THREAD

**Issue by StevenLi-DS** [altair-viz/altair#1304]
Is there any way to use Altair in vscode now? The plots don't seem to render at all.

![image](https://user-images.githubusercontent.com/33796896/51536770-a358ce80-1e1a-11e9-8e1d-3fab9ba19b78.png)

**Comment by jakevdp** [comment]
I've never tried to render Altair with VSCode, but perhaps the notebook renderer is not the right way to use it?

I'd contact the VSCode Python extension developers and ask them.

**Comment by jakevdp** [comment]
This part of the docs might also be helpful: https://altair-viz.github.io/user_guide/faq.html#does-altair-work-with-pycharm-spyder-my-favorite-ide

**Comment by stevencollinscn** [comment]
I was told a few days ago that the interactive feature provided by the extension actually uses nteract.  I read the doc and right now the only way I can think of is to save every plot object as a .html and then open a live server (there is an [extension ](https://github.com/ritwickdey/vscode-live-server
)for that) for it so that it can be automactilly update everytime.

It would be nice if you could please contact them and figure it out so that Altair plots could be rendered in the Python Interactive tab.

![altair_vscode](https://user-images.githubusercontent.com/33796896/51574612-85bc5100-1e7c-11e9-9bf4-0f53a7be1a74.gif)

**Comment by jakevdp** [comment]
If it uses nteract then you might try removing the ``alt.renderers.enable('notebook')`` line. That is only for enabling display in Jupyter notebook, and will cause nteract rendering to not work.

(cc/ @ellisonbg – this is an example of one of the user issues I was talking about today that could be remedied by the kernel being able to detect the frontend)

**Comment by jakevdp** [comment]
From the screencasts you included, though, it seems like you've gotten it to work properly?

**Comment by stevencollinscn** [comment]
I actually tried without that line before opening this issue, but it will give me something like this:

![image](https://user-images.githubusercontent.com/33796896/51615710-84c80580-1ef6-11e9-87ab-1604144218da.png)

**Comment by jakevdp** [comment]
OK - I'm not sure what javascript resources VSCode provides in outputs. Someone who's motivated should take a look and see if they can get Altair working.

**Comment by kindofluke** [comment]
For folks who stumble on this bug, there is a workaround that I implemented. I want to stress that this is just a workaround and it will limit some of Altair's functionality (like interactivity). 

Basically, Jupyter/Ipython has native support for showing SVG shapes and Altair/Vega-lite can render any chart to SVG. So, the goal is to take all altair charts, grab their SVG and give it to the Jupyter `display` command. 

This can be done with a function decorator defined as follows: 
```
#%%
import altair as alt
from vega_datasets import data
from functools import wraps
from IPython.display import HTML, display, Image, SVG
from io import StringIO


def chart(function):
    """
    This creates a decorator that will output the SVG of an
    altair chart whenever the system detects it is running in a
    jupyter session.
    """
    @wraps(function)
    def wrapper(**kwargs):
        chart = function(**kwargs)
        try:
            get_ipython() #evaluates True if running in any jupyter shell
            output = StringIO()
            chart.save(output, format='svg')
            display(SVG(output.getvalue()))
        except:
                pass
    return wrapper
```

This defines a new decorator `@chart` which will request the SVG and display it in VSCode's Jupyter Interactive Screen. 

```
@chart
def test_scatter( **kwargs):
    """
    This is a test chart that relies on only the vega-datasets package. 
    """
    source = data.cars()
    chart = alt.Chart(source, title="Horspower for Steve Cars").mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
)
    return chart
#You have to call the chart don't forget. 
test_scatter()
```

Now whenever that function is called the SVG will be displayed. This is some major overhead. The SVG save format requires selenium and headless chrome so in effect you are creating another browser to create code to show in VS Code's browser but because we push these charts automatically into publications, we have those dependencies set-up and its not a problem. 
![2v7awc](https://user-images.githubusercontent.com/20745904/53761889-a83a8480-3e94-11e9-9684-83371a504b8f.gif)

Oh and you have to use a light theme in VS Code or the charts look a little funny.

**Comment by csheaff** [comment]
I'd appreciate this feature as well, as I am transitioning away from Jupyter.

**Comment by StevenLi-DS** [comment]
https://github.com/microsoft/vscode-python/pull/8409

**Comment by hathawayj** [comment]
Ok.  I see that they updated VScode.  Now what settings do I need to change to get it to render? He page doesn't show the setting for vscode - https://altair-viz.github.io/user_guide/troubleshooting.html.

I suppose it will be something like the following.

```
alt.renderers.enable('notebook')
```

Here is the error.

```
If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```

**Comment by jakevdp** [comment]
I don't know, but if you figure it out please send a PR to update the docs with what you found!

**Comment by hathawayj** [comment]
Well.  I made it past the troubleshooting error.  

Here is the code chunk that I ran

```python
import altair as alt
from vega_datasets import data

source = data.movies.url

alt.Chart(source).mark_bar().encode(
    alt.X("IMDB_Rating:Q", bin=True),
    y='count()',
)
```

The new error is below.  It looks to be something with react and anteract.

```
ReferenceError: require is not defined
    at eval (eval at runCodeHere (webpack:///./node_modules/@nteract/transforms/lib/javascript.js?), <anonymous>:8:1)
    at runCodeHere (webpack:///./node_modules/@nteract/transforms/lib/javascript.js?:32:12)
    at JavaScript.componentDidMount (webpack:///./node_modules/@nteract/transforms/lib/javascript.js?:60:7)
    at Vh (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js?:216:198)
    at Zh (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js?:220:182)
    at eval (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js?:250:268)
    at Object.exports.unstable_runWithPriority (webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:18:163)
    at Fi (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js?:250:203)
    at Di (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js?:249:383)
    at Yh (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js?:248:144)
```

**Comment by Casyfill** [comment]
my 2 cents - Nteract has an obsolete vega as a dependency, which results in `<VegaLite 2 object>` as a render substitute there. I've bumped dependency ~2 months ago in the master repo, but they didn't push any `release` after that just yet.

**Comment by bioe007** [comment]
I stumbled upon this while trying to figure how to use altair.. 

This feature seemed to 'just work' for me with conda (python=3.7, VSCode 1.41.1)

![image](https://user-images.githubusercontent.com/38385/71387217-b5516d00-25a7-11ea-930c-508dbae8c32f.png)

I made the environment with something like `conda create --name my_altair python=3.7 altair ipython jupyter notebook`

**Comment by StevenLi-DS** [comment]
This now is supported by vscode python extension.

https://github.com/microsoft/vscode-python/issues/4125
