### ISSUE TITLE
cutomize label text 

### ISSUE THREAD

**Issue by python152** [altair-viz/altair#1348]
hi -

I have a bar graph looks like the following: I'd like to put a customized text label on top of the bar which represents, for example, the ratio of `A/B` on that year. I am having a hard time to figure out how. Must this ratio be part of the data frame? If so, it seems messing up the data frame's long form. Can I make the ratio from else where and still use it as text label?  please help.

```
testdf= pd.DataFrame({'year': [2015, 2016, 2017, 2018]*2, 'var': list("A")*4 + list("B")*4, "price" : [4, 6, 7, 8, 5, 7, 9, 4]})

bars = alt.Chart(testdf).mark_bar().encode(
    x = "year:O",
    y = "price",
    color="var"
)

# text = bars.mark_text(
# ).encode(
#     text= "??"
# )

# bars + text
```
![visualization](https://user-images.githubusercontent.com/17506882/53290312-2fd71380-3770-11e9-8e06-7d9fe36a1bf5.png)

**Comment by jakevdp** [comment]
There is not an easy way to do this kind of thing currently, short of pre-computing the ratio and adding it as a column in the dataset.

In a future Altair release, however, it will be possible to use Vega-Lite's new [fold transform](https://vega.github.io/vega-lite/docs/fold.html) to do this sort of operation. Here is a Vega-Lite spec that demonstrates this; as of yet there is no Python syntax to produce this spec, because it relies on features that have not yet made it into a Vega-Lite release (version 3) (view in [vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAIJkAsANFAEJkCsrkAnobABOZAEwAGAIycAvsyrVaDVADYeHVAHYe-IaMnLZ8jIrJb2ZAJzaBw1OIkbD1GvTIAONU2u67kt9KMAXSonKHhBWAA7YgAzAHtBAFsySgVIAGM8dPxcBEIyGAR8RIA6OjAAejA4eGKSjh5YUlRICPgASzjIHgBzQTj8AAcAI14UvhtIQNCXeNxocYZPQMbmimxdHkHBdvT86aoVqkhc-lsKI3RnSEShAGsC4c2jTEJI9LjodsiesivnKAADz+kHgvEG+RaCS+kTw3SgMXahHmBR0whm1zGqFoYIhBQAjvgoh1EB0sPkeIjkQsWttdvkMdQMnFcAkQbjIVBInFEt84ZSkSiWjh0S8wAFqBj-hgbvd2eDOaDCID4PCYFiwABaGRyAGQN4fGG-bFizDA7GghUFaF83BqqlCqBoyCMmUanFWlqE4ntUntcn2wU0qB0vZq2A9PqEHp5ArEYou3UAsLK1UWjkFbm82F2gXUgptTousUSjCl4LSIA))
```
{
  "data": {
    "values": [
      {"A": 4, "B": 5, "year": 2015},
      {"A": 6, "B": 7, "year": 2016},
      {"A": 7, "B": 9, "year": 2017},
      {"A": 8, "B": 4, "year": 2018}
    ]
  },
  "transform": [
    {"calculate": "datum.A / datum.B", "as": "ratio", "groupby": ["year"]},
    {"fold": ["A", "B"], "as": ["var", "price"]}
  ],
  "layer": [
    {
      "mark": "bar",
      "encoding": {
        "x": {"type": "ordinal", "field": "year"},
        "y": {"type": "quantitative", "field": "price"},
        "color": {"type": "nominal", "field": "var"}
      }
    },
    {
      "mark": {"type": "text", "dy": -5},
      "encoding": {
        "x": {"type": "ordinal", "field": "year"},
        "y": {"type": "quantitative", "field": "price", "aggregate": "sum"},
        "text": {"type": "nominal", "field": "ratio"}
      }
    }
  ]
}
```
![visualization 41](https://user-images.githubusercontent.com/781659/53290729-137dab80-375d-11e9-9d9e-bdee7deeb976.png)

Once Vega-Lite 3 is released, we will work to get this functionality into Altair.

**Comment by jakevdp** [comment]
In Altair 3, you can do this as follows:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'A': [4, 6, 5, 8],
    'B': [5, 8, 10, 4],
    'year': [2015, 2016, 2017, 2018]
})

base = alt.Chart(df).transform_calculate(
    ratio=alt.datum.A / alt.datum.B,
).transform_fold(
    ['A', 'B'], as_=['var', 'price']
)

bars = base.mark_bar().encode(
    x='year:O',
    y='price:Q',
    color='var:N'
)

text = base.mark_text(dy=-5).encode(
    x='year:O',
    y='sum(price):Q',
    text='ratio:N'
)

bars + text
```
![visualization (100)](https://user-images.githubusercontent.com/781659/58382592-0a30f480-7f81-11e9-84b1-ed86a9434e8b.png)
