### ISSUE TITLE
Adding Legend in Selective Lines Chart based on Color and Thickness

### ISSUE THREAD

**Issue by ashutosh29** [altair-viz/altair#1416]
Hi,

I have been trying to create Line chart with selectively highlighting few lines.  Although I got success in that by using layering but not able to figure out how to plot legend in this case.

Help appreciated !

```python
base = alt.Chart(result1,title='Multivariate, pure factor returns'.upper()).encode(
      x=alt.X('date_str:T', scale=alt.Scale(domain=['2011-12-31','2017-10-31']), 
      axis=alt.Axis(title=''.upper(),format=("%b-%Y"))),
)

chart=alt.layer(
    base.mark_line(color='blue',strokeWidth=0.5).encode(y='Best Price Correlation'),
    base.mark_line(color='red').encode(y='Percent Change YoY')
)

chart
```

![github](https://user-images.githubusercontent.com/13638740/55561417-c0115c80-570f-11e9-9ea4-0e8229ba00e3.png)

Format for result1 is as below

![image](https://user-images.githubusercontent.com/13638740/55561921-9dcc0e80-5710-11e9-8840-5d18b2412af4.png)

And how not to include y axis titles ?

**Comment by jakevdp** [comment]
You have wide-form data; in order to create a legend you'll need to convert it to long-form and use a color encoding. See details here: https://altair-viz.github.io/user_guide/data.html#long-form-vs-wide-form-data

**Comment by Alcampopiano** [comment]
@ashutosh29 

Hi there,

A couple of friendly tips. 

To make code easier to read, it is helpful to format your code with syntax highlighting as mentioned [here](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting):

Also, instead of using screenshots of data, perhaps you could make a small example that can be copied and pasted so that it is easier for others to reproduce your example.

In terms of your question, it seems that you are looking to make a line chart with specific colors for each line, and a legend. If that is correct, you may be able to extend from this example:

```python
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', scale=alt.Scale(range=['red', 'lightgray'], domain=['AAPL', 'GOOG']))
)
```
![visualization](https://user-images.githubusercontent.com/4624246/55562928-f1b00680-56c2-11e9-9f50-f8141c1399f8.png)

**Comment by jakevdp** [comment]
To remove the y-axis title, use an encoding like this:
```
y=alt.Y('field name', title=None)
```

**Comment by ashutosh29** [comment]
@jakevdp and @Alcampopiano thanks for your prompt response !

I understand that longitudinal data format should be used.

Still, how to assign desired line thickness to a particular line among all selectively.  

I have seen one example here 

https://altair-viz.github.io/gallery/multiline_highlight.html

But this is interactive. 

I would like something like below with _legend(that could be solved with Longitudinal format)_ & _selective colors (as mentioned in @Alcampopiano  comment)_ **but** still how to assign selective thickness:

 
![github](https://user-images.githubusercontent.com/13638740/55610246-2940b080-57a0-11e9-95e2-9be59c2fd7f1.png)


As above steps give below but same thickness to every line

![github_longitudinal](https://user-images.githubusercontent.com/13638740/55610896-8be67c00-57a1-11e9-87d8-49848e6535db.png)

**Comment by Alcampopiano** [comment]
Here is one idea that makes use of the `size` encoding channel.

```python
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    size=alt.Size('symbol', legend=None),
    color=alt.Color('symbol', scale=alt.Scale(range=['lightgray', 'red'], domain=['AAPL', 'GOOG']))
)
```

![visualization (1)](https://user-images.githubusercontent.com/4624246/55629033-351c7a80-5780-11e9-973c-ad7b867feb7e.png)

**Comment by ashutosh29** [comment]
Wondeful, thanks a lot !

**Comment by baereilon** [comment]
> @ashutosh29
> 
> Hi there,
> 
> It seems that you are looking to make a line chart with specific colors for each line, and a legend. If that is correct, you may be able to extend from this example:
> 
> ```python
> import altair as alt
> from vega_datasets import data
> 
> source = data.stocks()
> 
> alt.Chart(source).mark_line().encode(
>     x='date',
>     y='price',
>     color=alt.Color('symbol', scale=alt.Scale(range=['red', 'lightgray'], domain=['AAPL', 'GOOG']))
> )
> ```
> 
> ![visualization](https://user-images.githubusercontent.com/4624246/55562928-f1b00680-56c2-11e9-9f50-f8141c1399f8.png)

I spent quite a while looking for a way to define colors explicitly for values to be presented. 
In the case above selecting `'AAPL'` to be `'red'` and `'GOOG'` to be `'lightgrey'`. Seems pretty basic but took me a while to track down. Thanks so much! 
Is this somewhere in the docs / SO that I happened to miss?

**Comment by jakevdp** [comment]
> Is this somewhere in the docs / SO that I happened to miss?

Custom color scales are documented here: https://altair-viz.github.io/user_guide/customization.html#color-domain-and-range

**Comment by feliperoque** [comment]
@ashutosh29 Hi there, i'm trying to add a symbol with the same information you pass, but in return i get the following error:

**symbol encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.**

```
base = alt.Chart(new_df, title="Mean Control Chart")

domain = ['media','LSC','LM','LIC','1 x S(+)','2 x S(+)','1 x S(-)','2 x S(-)']
range_ = ['black','red','green','red','blue','blue','blue','blue']

# Linha da media
media_chart = base.mark_line(point=True, color='black').encode(
    alt.X('amostra', scale=alt.Scale(domain=(x_range_min_1,x_range_max_1)), axis=alt.Axis(title="Amostras")),
    alt.Y('media', scale=alt.Scale(domain=(y_range_min_1,y_range_max_1))),
    color = alt.Color('symbol', scale=alt.Scale(domain=domain, range=range_))
    
).properties(
    width=1000,
    height=500
).configure_axis(
    grid=True
)
```

The data i'm using:

![111](https://user-images.githubusercontent.com/34341242/115110395-98d20480-9f51-11eb-8880-9da0b5e028da.PNG)

**Comment by joelostblom** [comment]
Crossposted at https://stackoverflow.com/questions/67140945/altair-4-1-0-returning-an-empty-chart, let's answer there

**Comment by feliperoque** [comment]
@

> Crossposted at https://stackoverflow.com/questions/67140945/altair-4-1-0-returning-an-empty-chart, let's answer there

ok, its my post by the way rsrsrs
