### ISSUE TITLE
Bullet chart and BoxPlot chart implementation proposal

### ISSUE THREAD

**Issue by MireiaUB** [altair-viz/altair#1460]
I created two collab notebooks with an implementation of 
[bullet chart](https://colab.research.google.com/drive/1rwAK6C32Eelci8lcQdmNWCy4TYQmKO2a#scrollTo=wpPVshUZoFp0)
[boxplot chart](https://colab.research.google.com/drive/1314fafhKdaeQsN-EPZp7uHJPosWiKEds#scrollTo=vL5Z3yY2nBnm)
contributions are welcome and hope you find them useful.

I also published it in [my Medium page](https://medium.com/@mireia.ribera) 
Mireia

**Comment by joelostblom** [comment]
@MireiaUB I am going through Altair issues to find those that have been resolved and can be closed. Since this is something that needs to be fixed in Vega-Lite rather than in Altair, would you be able to close this issue or add a comment if there is something you don't think is resolved yet on the Altair side of things? Boxplots have already been implemented, but you could open a VegaLite issue for bulletcharts and link it here.
