### ISSUE TITLE
Yerrors and Xerrors in Altair 3.0.1

### ISSUE THREAD

**Issue by deisi** [altair-viz/altair#1473]
From the Documentation of Altair 3 I assumed that error bars are now easily available:
https://altair-viz.github.io/user_guide/encoding.html#encoding-channels

However if I try to do anything like:

    chart = alt.Chart(data).mark_point().encode(
        x='pump_freq:Q',
        y='t1:Q',
        yerror='error_t1:Q',
    )

I get:

       SchemaValidationError: Invalid specification
        altair.vegalite.v3.schema.core.FacetedEncoding, validating 'additionalProperties'
        Additional properties are not allowed ('yerror' was unexpected)

Also the documentation is confusing as it says: 

    Altair Class = YError

But the name is:

    alt.Yerror 

with a small E

**Comment by jakevdp** [comment]
The argument is ``yError``, not ``yerror``, but for consistency we should probably make it lower-case.

**Comment by jakevdp** [comment]
Actually, now that I look at it, ``yError`` is correct, as that's the name specified in the json schema.

**Comment by deisi** [comment]
Okay, with `yError` as keyword it doesn't fail, but it doesn't do anything either. Is it supposed to work with `mark_point` ?

**Comment by jakevdp** [comment]
To be honest I haven't spent much time using the new errorbar mark. You might find some of the documentation examples helpful:

- https://altair-viz.github.io/gallery/simple_scatter_with_errorbars.html?highlight=errorbar
- https://altair-viz.github.io/gallery/errorbars_with_std.html
- https://altair-viz.github.io/gallery/errorbars_with_ci.html

**Comment by deisi** [comment]
ah there are some examples. Thx a lot.

**Comment by deisi** [comment]
Looking at it I realized that is the old method I already use. However I was hoping that with the introduction of `Yerror` this would become simpler, as creating a separate errorbar plot is a tedious process.

**Comment by jakevdp** [comment]
It is simpler for some things, but yeah, I agree that there are some common use-cases that the Vega-Lite syntax ignores.

**Comment by jakevdp** [comment]
Some of those examples are based on the old way of doing things, because I haven't figured out how to do things the new way. I know there's a way to draw points with errorbars without calculating the ymin/ymax explicitly and without using layering. I just don't know anyone who has figured out how yet. If you figure it out, please consider submitting an example so others can learn from you!

**Comment by jakevdp** [comment]
(It's the strange thing about having a Python API that's mostly auto-generated: there are things that can be done that literally nobody has ever tried, and nobody knows how to do)

**Comment by jakevdp** [comment]
I think the trick is to use your encoding above with ``mark_errorbar``, and specify something to the ``ticks`` argument.

**Comment by deisi** [comment]
Okay here is a working and somewhat minimal example. 

```python
base = alt.Chart(params).encode(
    x='pump_freq:Q',
    y='t1',
    yError='error_t1',
    color='lipid',
)

base.mark_errorbar() + base.mark_point()
```

**Comment by jakevdp** [comment]
That's nice!

I think I might propose to Vega-Lite that the errorbar mark gain the ability to draw a point, just as the line mark has the ability to specify ``point=True``. Then your chart would look like this:
```py
base = alt.Chart(params).mark_errorbar(point=True).encode(
    x='pump_freq:Q',
    y='t1',
    yError='error_t1',
)
```
which I think would be what you were initially hoping for.

**Comment by jakevdp** [comment]
I asked about it on Slack... we'll see what they say

**Comment by jheer** [comment]
We did have a discussion about this when refining the errorbar design. One concern was that there are many choices one could in theory make for the central tendency point. These include:

- choice of aggregation function (mean, median)
- choice of point shape (circle, square, diamond, etc)
- choice of alternative mark (tick rather than point, etc)

Secondary issues might also arise relative to selections, which might make sense to define relative to a point mark, separate from the error bars themselves. (Thinking about how every _visual_ addition might interact with _interaction_ logic is a somewhat unique challenge for Vega-Lite language design!)

As a result, my recollection is that we decided that an initial design might omit point, but we could augment this later if it proved reasonable to do so. As we already include the `point=True` option for line/area marks, indeed it might be more consistent to include a similar basic functionality here. More customized options and interactions might still require an explicitly layered design. I think the remaining question is how much control we would give over the aggregation function. Perhaps a typing like `point?: "mean" | "median" | boolean`, where `true` corresponds to `mean`?

@kanitw @domoritz

**Comment by jakevdp** [comment]
What would make the most sense to me would be a typing like ``point?: boolean | MarkDef``, with the point drawn at the position specified by the ``y`` encoding (and ignored if no y encoding is specified). But I've still not wrapped my head around all the possible ways to use the errorbar mark, so this may not be general enough.

**Comment by jakevdp** [comment]
(let's move discussion of this to https://github.com/vega/vega-lite/issues/4422)
