### ISSUE TITLE
Boxplot gallery example doesn't work

### ISSUE THREAD

**Issue by ewels** [altair-viz/altair#1490]
Hi all,

With Altair v3 we now have boxplots, which is great! (resolves #664 I believe). However, the [example in the documentation(https://altair-viz.github.io/gallery/boxplot_max_min.html) doesn't seem to work for me:

```python
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_boxplot(extent='min-max').encode(
    x='age:O',
    y='people:Q'
)
```
![visualization (1)](https://user-images.githubusercontent.com/465550/57433832-bcef1c00-7239-11e9-91d3-05a5aeec2b43.png)

If I take the strip plot example and switch it for a boxplot then it works fine though:

```python
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_boxplot().encode(
    x='Horsepower:Q',
    y='Cylinders:O'
)
```

![visualization](https://user-images.githubusercontent.com/465550/57433808-ae086980-7239-11e9-9543-451fc107cd94.png)

```console
$ pip freeze | grep -E 'altair|jupyter'
altair==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==1.0.0a3
jupyterlab-server==0.3.0
```

Thanks for the updates - boxplots are a great addition!

Phil

**Comment by jakevdp** [comment]
The difference between the two is that the first chart accesses data by URL, and the second embeds the data. This makes me think that your renderer is unable to load URL data either because you are not connected to the internet, or you have some kind of adblocker that is preventing the javascript from performing an HTTP request. There will be an error in your browser javascript console that will tell you more.

**Comment by ewels** [comment]
You're completely right - AdBlock was preventing it from loading. I disabled it and it works 👍 

Thanks for the quick response! Apologies for the false alarm..

**Comment by jakevdp** [comment]
Great, glad it worked!
