### ISSUE TITLE
valid() aggregation not working with source csv files

### ISSUE THREAD

**Issue by asuagar** [altair-viz/altair#1549]
I am using Altair 3.0.1. `valid()` aggregation does not handle correctly missing values when a CSV file is used as source. Here is the code:

```
import altair as alt
import pandas as pd
import numpy as np

data = {'col_1': [1,1,1,2,2,2], 'col_2': [1,2,3,np.nan,np.nan,np.nan]}
df = pd.DataFrame(data)
df.to_csv('data.csv')

dataframe = alt.Chart(df).mark_bar().encode(
    x='col_1:O',
    y='valid(col_2):Q'
)

csv = alt.Chart('data.csv').mark_bar().encode(
    x='col_1:O',
    y='valid(col_2):Q'
)

dataframe | csv
```
![image](https://user-images.githubusercontent.com/19633/58848250-253cec00-8686-11e9-9c64-92ebb6f821df.png)

Thank you for any help you can offer and working in Altair so hard.

**Comment by jakevdp** [comment]
The CSV data is being parsed as a string. If you explicitly specify that it should be parsed as a number, it will work as expected:
```python
import altair as alt
import pandas as pd
import numpy as np

data = {'col_1': [1,1,1,2,2,2], 'col_2': [1,2,3,np.nan,np.nan,np.nan]}
df = pd.DataFrame(data)
df.to_csv('data.csv')

dataframe = alt.Chart(df).mark_bar().encode(
    x='col_1:O',
    y='valid(col_2):Q'
)

csv_data = alt.UrlData('data.csv',
                       format=alt.CsvDataFormat(parse={'col_1': 'number', 'col_2': 'number'}))

csv = alt.Chart(csv_data).mark_bar().encode(
    x='col_1:O',
    y='valid(col_2):Q'
)

dataframe | csv
```
![visualization - 2019-06-03T213235 252](https://user-images.githubusercontent.com/781659/58851316-1be05f00-8647-11e9-995d-ca612e186cad.png)

I believe this is a bug in Vega-Lite, and reflects the same issue reported in https://github.com/vega/vega-lite/issues/4988. In general I'd suggest using JSON rather than CSV for data sources, because JSON includes type information.

**Comment by asuagar** [comment]
Hello @jakevdp, thank you so much for your quick reply. Both of your solutions work flawesly. I have just found another one, observing the produced JSON files by pandas. In them, 'null' represents a null value. However, pandas use an empty string to do the same in CSV files by default. This behavior can be modified by:

`df.to_csv('data.csv', na_rep='null')`

Using it, helps Altair to process correctly the null values of the CSV files.

Thanks again and regards.
