### ISSUE TITLE
Zoomable map (again!)

### ISSUE THREAD

**Issue by trubens71** [altair-viz/altair#1555]
I appreciate that zooming of maps has been discussed before and it is not supported (e.g #632), however as a newcomer to Altair/Vega, I wonder appreciate guidance on this approach...

I can achieve what I want by editing the vega-lite spec (not vega) to bind a signal to the scale. Given this simple example...

```
import altair as alt
from vega_datasets import data
topo_data = alt.topo_feature(data.world_110m.url, 'countries')

slider_scale = alt.binding_range(min=50, max=1000, step=10)

select_scale = alt.selection_single(name="zoom", fields=['scale'],
                                   bind=slider_scale, init={'scale': 50})

alt.Chart(topo_data).mark_geoshape().project(
    scale=200
).add_selection(select_scale)
```
And then editing the vega-lite to bind a signal to the scale...

`"projection": {"scale": {"signal": "zoom_scale"}},`

This works just fine, however I'd prefer to be able to this directly from Altair, but the schema check insists that "scale" must be a number. I had a bit of a hack with alt.SignalRef but to no avail. From my (limited) understanding I was under the impression that any valid Vega-lite spec could be generated by Altair. Any thoughts?

I'm using Altair on Colab (v3.0.1).

**Comment by jakevdp** [comment]
According to the Vega-Lite schema, scale can only be a number, and so by design Altair validates that it is a number. For what it's worth, Vega-Lite also raises a warning if you pass a non-number to the scale. Altair raises an error because it's the only way to surface what would be obscure Javascript-side rendering errors in a more familiar Python traceback

If you want Altair to be able to accept values that are prohibited by the Vega-Lite schema, I'd suggest raising an issue in the Vega-Lite repository to update the schema.

Depending on whether you're using Jupyter Notebook, JupyterLab, nteract, vegascope, etc. you could use the low-level Vega-Lite renderers directly from Python to add non-valid values to the schema, but there's not really any general way to do that because every frontend behaves differently.

**Comment by vizsim** [comment]
I wonder if this issue can be solved now, as vega5 allows zooming. At least the following examples does:
https://vega.github.io/vega/examples/zoomable-world-map/

I was trying to add this to an altair example, however don't know how to add the events/signals.

**Comment by jakevdp** [comment]
Altair produces Vega-Lite, not Vega, and Vega-Lite still does not support zooming of geographical charts.
