### ISSUE TITLE
How can I set alt.bind_range() to datetime?

### ISSUE THREAD

**Issue by adxrgh** [altair-viz/altair#1595]
all the example with slider like this:
slider = alt.binding_range(min=1900, max=2000, step=10)

and I want to set the range to dates not years, but the function only supports numbers not timestamp or datetime.

How can I achieve this ?

Thanks !

**Comment by joelostblom** [comment]
This needs to be added in Vega-Lite, so I would recommend opening an issue there. Two work arounds can be seen here for altair https://stackoverflow.com/questions/62046930/altair-adding-date-slider-for-interactive-scatter-chart-pot. Closing this since it can't be fixed from the altair side of things.
