### ISSUE TITLE
Stacked bar chart with logarithmic scale doesn't appear

### ISSUE THREAD

**Issue by kai-tub** [altair-viz/altair#1598]
Hi.
First of all, I must thank everyone for working on Altair!
I love this library! I am still relatively new to the library, so this may be a
simple question to answer. I want to plot a stacked bar chart with a logarithmic
scale. I used the example code from the website, for easy reference.
If I use the following it doesn't work:

```
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar().encode(
    x=alt.X(
        'sum(yield)',
        scale=alt.Scale(type='log'),
    ),
    y=alt.Y('variety'),
    color='site',
)
```
And this is my output:
![visualization (1)](https://user-images.githubusercontent.com/46302524/60689554-1339ad80-9ebf-11e9-9891-e15a6621fc36.png)

If I remove the scale line I get the expected output:
![visualization (2)](https://user-images.githubusercontent.com/46302524/60689570-395f4d80-9ebf-11e9-9275-2c4aa7809e55.png)

Same after removing the color and keeping the scale:
![visualization (3)](https://user-images.githubusercontent.com/46302524/60689590-5ac03980-9ebf-11e9-969f-829f262da757.png)

What am I missing?
Thanks!

**Comment by mattijn** [comment]
If you open your false output in Vega-Editor you will notice it has thrown the warning:
```[Warning] Cannot stack non-linear scale (log)```

I raised this a while ago at the Vega-Lite repo https://github.com/vega/vega-lite/issues/4337 and solved it by computing beforehand the lower- and upperboundary and a `mark_rect()` as method for the mark properties. In your case this is not so easy since you are using `sum(yield)` as an Altair defined aggregate transform.

My reasoning at that moment for the question why you should not stack on a non-linear scale (apart of _potentially_ misleading):

> Maybe this functionality was switched off since the bar stack cannot determine the minimal value on the y-domain.

Doesn't really make sense since that also counts for a _non-stacked_ log scale. With other words, I think its a bug in Vega-Lite.

Off-topic: It would be nice if these warnings in Vega-Lite are piped back to Altair.

**Comment by kai-tub** [comment]
Oh, thanks!
I wasn't aware that error messages were hidden away in the Vega-Editor.
I agree it would've answered my question if the warnings would've been piped back to Altair.

After looking into it, I decided not to use a logarithmic scale. I thought I had an exception, for when it makes sense to create one, but in the end, it was easier to understand by simply putting the bars into a different chart. 

Nevertheless, thank you for your response!

I will close this issue, as in my specific case the recommendation to not use a logarithmic bar chart was correct and as you said, it would be an issue for vega-lite and not Altair.

**Comment by monfera** [comment]
Good call on not supporting and not wanting logarithmic scale for stacked bars, and I think even logarithmic bar and area charts are bad practice. Here are some old but still [relevant examples](https://www.graphpad.com/support/faq/graph-tip-dont-use-a-log-scale-on-a-bar-graph/) that show how misleading or even, manipulative it can be even with non-stacked bar charts, basically, like non-zero (non-natural) scale baseline on steroids. Here's one of the illustrations:

![image](https://user-images.githubusercontent.com/1548516/89730552-f10a4b80-da3f-11ea-985d-b84081ca31ae.png)
