### ISSUE TITLE
Support altair in Apache Zeppelin notebook

### ISSUE THREAD

**Issue by zjffdu** [altair-viz/altair#1616]
I'd like to help to support altair in apache zeppelin notebook, but need some help from you.
Currently what I figure out is that (I use kaggle render), altair will output 2 types of data: plain text and html, but I am not sure how frontend render the image based on these data. Could you tell me the internal mechanism and help me to integrate altair into zeppelin as well ? Thanks

**Comment by jakevdp** [comment]
So the broad view is this: Altair produces JSON specifications for the charts (which you can see with ``chart.to_json()``. These specifications can be fed into the [vega-embed](https://github.com/vega/vega-embed) javascript package to be rendered into an image on an HTML page. So every frontend that wants to render Altair charts just needs a way to take ``chart.to_json()`` and plug the result into a vega-embed call. And that's it.

Now, every frontend has slightly different constraints here. For example, JupyterLab and Nteract support mimebundle-based rendering, and recognize the vega-lite mimetype in the mimebundle output, and have built-in frontend extensions that know how to render this. You can see this by running
```python
with alt.renderers.enable('default'):
    chart._repr_mimebundle_(None, None)
```

The classic Jupyter Notebook doesn't support mimebundle-based rendering, so it uses the [ipyvega](https://github.com/vega/ipyvega/) renderer that can be enabled by running ``alt.renderers.enable('notebook')``, this renderer short-circuits the mimebundle display mechanism and calls ``IPython.display()`` on an appropriate object as a side-effect. You can see that here:

https://github.com/vega/ipyvega/blob/4cf32e602c9361ecd1f5089633a4e5fb9e3b7168/vega/vegalite.py#L16-L19

Kaggle and Colab are a bit simpler: they don't have specific frontend extensions that recognize the vega-lite mimebundle, so Their renderers cause the HTML mimetype which includes the literal HTML to display the chart. But each frontend provides a slightly different HTML/javascript environment, so the specific HTML output used has to be tailored to them. You can see this by running:
```
with alt.renderers.enable('kaggle'):
    print(chart._repr_mimebundle_(None, None))``
with alt.renderers.enable('colab'):
    print(chart._repr_mimebundle_(None, None))``
```

So all that to say, if you want to display charts in Zeppelin, you need to figure out what the right mechanism is to take ``chart.json()`` and run it through the Vega-Embed library. And once you know that mechanism, we can talk about how to best package the zeppelin renderer so that users can run ``alt.renderers.enable('zeppelin')``.

**Comment by jakevdp** [comment]
I should mention: if it's at all possible to make Zeppelin recognize the ``_repr_mimebundle()`` method and correctly interpret vega-lite mimetypes, that would be ideal. That's the uniform model that we'd like to be moving toward, but unfortunately the classic Jupyter notebook still has a lot of traction.

**Comment by zjffdu** [comment]
Thanks @jakevdp , I created PR https://github.com/altair-viz/altair/pull/1620 for this issue.
This is a draft PR, could you help review it ? If this approach is correct for you. I will refine it, at least add document.
