### ISSUE TITLE
Cannot alter point size when using mark_geoshape

### ISSUE THREAD

**Issue by schakalakka** [altair-viz/altair#1647]
When using a geopandas dataframe (or similar) with only points as geometries it is not possible to change the size of the points in the resulting plot

```
import altair as alt
import gpdvega 
alt.renderers.enable('notebook') 

points = alt.Chart(df_points).mark_geoshape(tooltip={"content": "data"}, size=5).encode()

points
```
size=5 or size=alt.value(5) do not have any effect

**Comment by jakevdp** [comment]
This is intended: geoshape marks are defined by their topojson geometries, so size has no effect.

**Comment by schakalakka** [comment]
That is true for most geometries but if a topojson/geoson/geopandasdataframe only contains points there is no intrinsic spatial value (like thickness or diameter). 

One solution for now is to extract the point coordinates to another normal pandas dataframe and plot it with something like: ` alt.Chart(baz).mark_circle(size=1).encode(longitude='x', latitude='y')`

This is of course possible but a bit tedious.

**Comment by jakevdp** [comment]
Can you show an example script in which you're unable to adjust the point size?

**Comment by schakalakka** [comment]
The Jupyter cell looks like this:

`foo = gpd.read_file("Data/Wohnungen_Adressen.shp", encoding='utf-8')`
`points = alt.Chart(foo).mark_geoshape(size=5).encode()`
`points`

where one entry in the geometry column of the geopandas dataframe looks like 
`POINT (379009.365 5800448.905)`

**Comment by jakevdp** [comment]
Can you provide a full example, including the data? (It should be a code snippet that I copy and paste into a fresh environment that runs without error) If I'm not able to reproduce your issue, I will not be able to help you out.

**Comment by mattijn** [comment]
@schakalakka this is something that is reproducible:
Having a GeoDataFrame as such:
```python
gdf
```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>name</th>
      <th>geometry</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Germany</td>
      <td>POINT (10.28848509274289 51.13372269040782)</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Netherlands</td>
      <td>POINT (5.512217100965401 52.2987003744418)</td>
    </tr>
    <tr>
      <th>2</th>
      <td>United States</td>
      <td>POINT (-112.5994383773273 45.70562953540318)</td>
    </tr>
  </tbody>
</table>

One can convert this to GeoJSON (this is `gpdvega` doing for you, plus some extras):
```python
gdf.to_json()
```
```
'{"type": "FeatureCollection", "features": [{"id": "0", "type": "Feature", "properties": {"name": "Germany"}, "geometry": {"type": "Point", "coordinates": [10.288485092742887, 51.13372269040782]}}, {"id": "1", "type": "Feature", "properties": {"name": "Netherlands"}, "geometry": {"type": "Point", "coordinates": [5.51, 52.23]}}, {"id": "2", "type": "Feature", "properties": {"name": "United States"}, "geometry": {"type": "Point", "coordinates": [-112.60, 45.71]}}]}'
```

So a full code snippet becomes something like this:
```python
# geojson
geojson_str = '{"type": "FeatureCollection", "features": [{"id": "0", "type": "Feature", "properties": {"name": "Germany"}, "geometry": {"type": "Point", "coordinates": [10.288485092742887, 51.13372269040782]}}, {"id": "1", "type": "Feature", "properties": {"name": "Netherlands"}, "geometry": {"type": "Point", "coordinates": [5.51, 52.23]}}, {"id": "2", "type": "Feature", "properties": {"name": "United States"}, "geometry": {"type": "Point", "coordinates": [-112.60, 45.71]}}]}'

# inline geojson data object
data_geojson = alt.InlineData(values=geojson_str, format=alt.DataFormat(property='features',type='json')) 

# chart object
alt.Chart(data_geojson).mark_geoshape(
).encode(
    color="properties.name:N"
).properties(
    projection={'type': 'mercator'}
)
```
![image](https://user-images.githubusercontent.com/5186265/62877437-56d9cf80-bd27-11e9-8208-5f9aa403bb02.png)

Where according to the Vega geoshape transform specification: https://vega.github.io/vega/docs/transforms/geoshape/ you should have a `pointRadius` property within the `projection` properties.
But according to the Vega-Lite documentation, https://vega.github.io/vega-lite/docs/projection.html#properties there is no such property support.

While the schema doesn't support it, it does renders in the [editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzDESPHGiCpSMdMBaaAEYArInGumADgEARpQAnK4M4Xy+AGyIAEyIvgyUDO6ulAHukKwWUIiwkhK8WDhqkrBqBJLUAJ72iAQmWpIEAM5ZUDUV9gBWLQiQgoYGlhIy9qgEsC204l3ZlgTwcJTI8OjFMMr5cpCddlhWsKKr4krtkCgESpT2peWVqq0AdNa2A8NQd90E0Kr9G3t7LZJNATNsRGpYKtqAAlcQrLRtDACD6QAAkLWgnAk9h41DULQwAHoibgCKhxE9UMg6FoAk9kLAiZjseJSeTxE4lDSCKS+E9+Uwnr1+vMjCZxC0CNQkdgcg4JS4PF4fP4mEFQuEGJEYvFEslUulMgdgAAdXbVCrmrDmgBiDWoTQIAGFlEofn94Ob2Ob6o1mi1rWAANpmyBUIPmpjesDmvaRyD2-0EGPmu4VKqEQNyc2vFOkc0AcUqEng1XNwljkAmR2lknLOYtVoLkAAClD4NRU5t8itrNRWkHgz4nrFfIlfO4mMFYgB2Bhj3yz9ipJ6uPh8WexWJRYJMZiz3yxAC6+nYYYjLdc3fjLaTjua3fTDyzQbDeYTADlpZxJEpxPAlDZpW5o1rY1D1m+caWvmNpth2XbtOacC9icA7ZlgwbuE8qQrrEo58KelYXpQCaxDeMEJveTpPmUGaPBh2C5jYsFVgAqvAPKUGAADKpjoRWPrVpM4GQY2t5we20Ldihkh9iYg6kMGTiuK4+FRGwYApE8s6uERp6QEMICCEAA):
![image](https://user-images.githubusercontent.com/5186265/62877847-33fbeb00-bd28-11e9-9451-adad3e0f7167.png)

So.. the following should be possible in Altair:
```python
alt.Chart(data_geojson).mark_geoshape(
).encode(
    color="properties.name:N"
).properties(
    projection={'type': 'mercator', 'pointRadius':30}
)
```

But this doesn't work since the Vega-Lite schema doesn't resolve. 
Conclusion: send a PR or file an issue at the Vega-Lite repo

**Comment by schakalakka** [comment]
Thank you @mattijn.
I will do that.

**Comment by schakalakka** [comment]
I see that it is already a known issue in vega-lite: vega/vega-lite#3396

**Comment by davefoote** [comment]
How do people plot geodataframe polygons in altair?

**Comment by mattijn** [comment]
```python
import geopandas as gpd
import altair as alt
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf.head()
```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pop_est</th>
      <th>continent</th>
      <th>name</th>
      <th>iso_a3</th>
      <th>gdp_md_est</th>
      <th>geometry</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>920938</td>
      <td>Oceania</td>
      <td>Fiji</td>
      <td>FJI</td>
      <td>8374.0</td>
      <td>(POLYGON ((180 -16.06713266364245, 180 -16.555...</td>
    </tr>
    <tr>
      <td>1</td>
      <td>53950935</td>
      <td>Africa</td>
      <td>Tanzania</td>
      <td>TZA</td>
      <td>150600.0</td>
      <td>POLYGON ((33.90371119710453 -0.950000000000000...</td>
    </tr>
    <tr>
      <td>2</td>
      <td>603253</td>
      <td>Africa</td>
      <td>W. Sahara</td>
      <td>ESH</td>
      <td>906.5</td>
      <td>POLYGON ((-8.665589565454809 27.65642588959236...</td>
    </tr>
    <tr>
      <td>3</td>
      <td>35623680</td>
      <td>North America</td>
      <td>Canada</td>
      <td>CAN</td>
      <td>1674000.0</td>
      <td>(POLYGON ((-122.84 49.00000000000011, -122.974...</td>
    </tr>
    <tr>
      <td>4</td>
      <td>326625791</td>
      <td>North America</td>
      <td>United States of America</td>
      <td>USA</td>
      <td>18560000.0</td>
      <td>(POLYGON ((-122.84 49.00000000000011, -120 49....</td>
    </tr>
  </tbody>
</table>

### projected data (with coordinates in degrees)

```python
alt.Chart(gdf).mark_geoshape().encode(
    color='pop_est', 
).project('equalEarth')
```
![image](https://user-images.githubusercontent.com/5186265/73636184-9b568000-4665-11ea-8ddd-7cd384ddb74b.png)

### unprojected data (with coordinates in meters)

```python
alt.Chart(gdf).mark_geoshape().encode(
    color='pop_est', 
).project('identity', reflectY=True)
```
![image](https://user-images.githubusercontent.com/5186265/73636325-e5d7fc80-4665-11ea-94dc-4faf1ebcb29a.png)

**Comment by dlevine01** [comment]
I know this is old and closed, but it's what I found when Googling a solution for this, so I'll note for anyone else who finds this:

adding:

```py
.project(pointRadius=2) 
```

to a `mark_geoshape()` resizes the size of the points to 2 pixels. 

per the vega-lite [docs](https://vega.github.io/vega-lite/docs/projection.html), the size is spec'ed in pixels and the default is 4.5
