### ISSUE TITLE
Unable to set horizontal grid lines using grid=True for LayerCharts

### ISSUE THREAD

**Issue by trllrgn** [altair-viz/altair#1700]
I have a couple of layer charts, say chartA and chartB, each of which in turn are layer charts, say
chartA = chart1 + chart2
chartB = chart3 + chart4

I am combining them into a chart = alt.Layer(chartA, chartB).resolve_scale(y='independent')

By default, vertical grid lines are on, horizontal ones are off.  I am trying to set horizontal grids on for the left hand side Y axis using configure_axisLeft(grid=True). I can turn the vertical grid lines on and off without any issue, but no matter what I do, I cannot turn the horizontal grid lines on.

Any suggestions? Are horizontal grid lines not possible when there are two Y axes? Dummy code below, I appreciate any help.

```
import altair as alt
from vega_datasets import data
alt.renderers.enable('notebook')
cars = data.cars()

chart1 = alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y='Miles_per_Gallon',
  color='Origin'
)
chart2 = alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y='Miles_per_Gallon',
  color='Origin'
)
chart =alt.layer(chart1+chart2,chart1+chart2).resolve_scale(y='independent')
display(chart)
chart.configure_axisRight(grid=True)
```

**Comment by jakevdp** [comment]
By default, grid lines are removed for layered independent scales, because they often look rather strange. But you can force them to be on via the ``axis.grid`` setting within the encoding.

Here's an example of a layered chart with grid lines on both scales, which should give you an idea of how to solve your problem, and also why such gridlines are turned off by default:
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

chart1 = alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y=alt.Y('Miles_per_Gallon', axis=alt.Axis(grid=True)),
  color='Origin'
)
chart2 = alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y=alt.Y('Acceleration', axis=alt.Axis(grid=True)),
  color='Origin'
)
alt.layer(chart1, chart2).resolve_scale(y='independent')
```
![visualization - 2019-09-20T055419 053](https://user-images.githubusercontent.com/781659/65328400-1ada2b80-db6b-11e9-92a4-e11c0ccd8996.png)

**Comment by trllrgn** [comment]
Thanks a lot, this solves my problem. But of course I only want to turn on the left hand side lines, not both :)
