### ISSUE TITLE
Adding order argument with mark_area() produces empty output

### ISSUE THREAD

**Issue by calebbraun** [altair-viz/altair#1718]
I am trying to reproduce the example from [this Stack Overflow question](https://stackoverflow.com/questions/55700724/controlling-stack-order-of-an-altair-area) without success.

```python
import random
import altair as alt
import pandas as pd

df = pd.DataFrame({
    "date": pd.date_range('1/1/2019',periods=20,freq="M"),
    "jack": random.sample(range(100, 500), 20), 
    "roy":random.sample(range(20, 90), 20),
    "bill":random.sample(range(600, 900), 20), 
})
df = df.melt(id_vars="date", var_name="person", value_name="measure")
alt.Chart(df).mark_area().encode(
    x='date',       
    y='measure',
    color='person',
    order=alt.Order('measure:Q', sort='descending')
)
```

Running this code gives:
![visualization](https://user-images.githubusercontent.com/12344924/66173406-e6ec1500-e604-11e9-9a60-748bfc311ed8.png)

Removing the `order` argument produces the chart I would expect.

Altair Version: 3.2.0
Vega Version: 2.6.0

**Comment by jakevdp** [comment]
You need to aggregate the order field. For example: 
```python
alt.Chart(df).mark_area().encode(
    x='date',       
    y='measure',
    color='person',
    order=alt.Order('sum(measure)', sort='ascending')
)
```
![visualization - 2019-10-03T201046 397](https://user-images.githubusercontent.com/781659/66178409-1e18f100-e61a-11e9-8eb9-0c5d3d964f32.png)

Explanation: the arguments of encodings with the exception of ``x`` and ``y`` are treated as fields to group the data by before drawing a mark. Because every point has a distinct ``measure`` value, this results in each group having a single point, which results in a zero-width area mark for each point and an apparently empty chart.

**Comment by calebbraun** [comment]
Got it, thanks for the explanation!
