### ISSUE TITLE
How to generate a dataset when using from_json method?

### ISSUE THREAD

**Issue by fj-sanchez** [altair-viz/altair#1720]
Hi,

I have created a Vega-Lite spec using the Vega editor, now I would like to load this json spec but use Altair with pandas DataFrames to generate a new spec that contains the data (the dataset section of the spec). How can I do this?

UPDATE:
I realised that I didn't phrased it in the best way, what I actually want to reuse is the chart definition and discard the existing data in the JSON spec. Then, using pandas load new data from a different source and produce the same JSON spect but with the updated data.

**Comment by jakevdp** [comment]
Good question! Say you have a chart like this ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAHawC2hZkAgpADRQ4EuoAWAL6cq1Wg2asAQlx54iZAOwixGCU35QAwnOwKtAJlXUa9TawAie3osEnTGqakgBRGwbIBmIWoC6VA6QjLAATgDWrABGYVxUkIR0AMYA9tAAlnQA5mToGJAAHrmQ8ACeAA5akACO+LB08OmIjVgs3JAAZumEuNCstiwOmKXFZZWsdCmMmXh6XT19LpKDgSBCQA)):
```json
{
  "data": {
    "values": [
      {"name": "A", "value": 4},
      {"name": "B", "value": 7},
      {"name": "C", "value": 2},
      {"name": "D", "value": 4},
      {"name": "E", "value": 3}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"type": "quantitative", "field": "value"},
    "y": {"type": "nominal", "field": "name"}
  }
}
```
![visualization - 2019-10-07T055220 805](https://user-images.githubusercontent.com/781659/66313232-e1255680-e8c6-11e9-8068-5a23e313f5c6.png)

The easiest way to turn it into an Altair chart is with the ``from_json`` method:
```python
spec = """
{
  "data": {
    "values": [
      {"name": "A", "value": 4},
      {"name": "B", "value": 7},
      {"name": "C", "value": 2},
      {"name": "D", "value": 4},
      {"name": "E", "value": 3}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"type": "quantitative", "field": "value"},
    "y": {"type": "nominal", "field": "name"}
  }
}
"""

import altair as alt
alt.Chart.from_json(spec)
```
![visualization - 2019-10-07T055421 689](https://user-images.githubusercontent.com/781659/66313258-eedadc00-e8c6-11e9-9b2b-64517cc96f0c.png)

(The chart looks a bit different because of Altair's default theme; setting ``alt.themes.enable('none')`` will change this).

If you want to extract the data, turn it into a dataframe, and construct the chart from scratch, you can do this:
```python
import pandas as pd
import json
data = json.loads(spec)['data']['values']
df = pd.DataFrame.from_records(data)

alt.Chart(df).mark_bar().encode(
    x='value:Q',
    y='name:N'
)
```
![visualization - 2019-10-07T055421 689](https://user-images.githubusercontent.com/781659/66313258-eedadc00-e8c6-11e9-9b2b-64517cc96f0c.png)

**Comment by fj-sanchez** [comment]
What I'm trying to do is just the opposite, I want to use the Vega-Lite editor to generate a spec, I'm using a dataset section with dummy data while creating the spec. What I want to do now is to load the JSON, remove the data and use a DataFrame with different data (same fields) to generate a new json spec.

**Comment by jakevdp** [comment]
Sure, you could do something like this:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'name': list('ABCDE'),
    'value': [4, 7, 2, 4, 3]
})

spec = """
{
  "data": {
    "values": [
      {"name": "dummy", "value": 0}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"type": "quantitative", "field": "value"},
    "y": {"type": "nominal", "field": "name"}
  }
}
"""

chart = alt.Chart.from_json(spec)
chart.data = df
chart
```
![visualization (16)](https://user-images.githubusercontent.com/781659/66330690-c0b8c480-e8e5-11e9-8551-1e5b964b44ec.png)

**Comment by fj-sanchez** [comment]
Amazing how easy it actually is!

Thanks!
