### ISSUE TITLE
Large paragraph in tooltip?

### ISSUE THREAD

**Issue by aneesh3397** [altair-viz/altair#1724]
Hi! I was wondering if it is possible to the tooltip to display a small sized paragraph. I am trying to visualize clusters of text data that are between 1-5 sentences long. Some of them are too big for the tooltip and get cut off. Is there anyway to change the size of the tooltip to accommodate the text?

**Comment by jakevdp** [comment]
There is currently no mechanism in Vega-Lite to allow line breaks in large text blocks. There is work on this for the 4.0 release, but I can't find the reference right now.

**Comment by wuqui** [comment]
I need the same functionality. Any updates on this?

**Comment by vinitrinh** [comment]
+1

**Comment by jtladner** [comment]
I'm looking for the same thing. Any updates?

**Comment by exam-ple** [comment]
@jakevdp Any updates? Even if passing a list of strings in place of a single string, the elements of the list DONOT be rendered as separate lines in tooltip.

**Comment by mattijn** [comment]
Hi @exam-ple. It is possible to render the elements of a long string over seperate lines in a tooltip. But I still think there is a maximum. I tried a bit and I think the maximum is about 307 characters to be displayed in a tooltip:
```python
import altair as alt
import pandas as pd

my_str = "@jakevdp Any updates? Even if passing a list of strings in place of a single string, the elements of the list DONOT be rendered as separate lines in tooltip."
my_long_str = my_str * 2
my_trunc_str = my_long_str[:307]

df = pd.DataFrame(data={"exam-ple": [my_trunc_str]})

alt.Chart(df).mark_rect().encode(
    tooltip=[alt.Tooltip("exam-ple")]
)
```
![image](https://user-images.githubusercontent.com/5186265/229540776-b0451d63-0183-467e-acfe-2f041c4950df.png)
(mousepointer not in screenshot)

If this length is insufficient for your use-case, you might raise an issue over at the https://github.com/vega/vega-tooltip repository, since rendering of the tooltip is outsourced to this package.
