### ISSUE TITLE
Adjusting y-axis limits in boxplot not working

### ISSUE THREAD

**Issue by martamatos** [altair-viz/altair#1743]
I just tried to change the y-axis limits on the boxplot example and it is not working (code below).
However, it works if I change `mark_boxplot` to `mark_point`.
This happens both with v3.2.0 and v3.3.0dev0.

```
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_boxplot(clip=True).encode(
    x='age:O',
    y=alt.Y('people:Q', scale=alt.Scale(domain=(-2,5000000)))
)
```

**Comment by jakevdp** [comment]
This is a bug that has been fixed in Vega-Lite. If you're using the current version of vega-lite in your frontend renderer, you will see the correct result:
![visualization (19)](https://user-images.githubusercontent.com/781659/67223305-e1077980-f3e3-11e9-98b3-c3c71ade85d2.png)
(to see this yourself, save the chart as HTML and open in a browser, or click on "Open In Vega Editor")

To upgrade your frontend renderer: either upgrade the ``vega`` nbextension if you are using Jupyter nobeook, or upgrade the vega labextension if you are using Jupyterlab.
