### ISSUE TITLE
Setting a random seed

### ISSUE THREAD

**Issue by TTitcombe** [altair-viz/altair#1783]
The [stripplot](https://altair-viz.github.io/gallery/stripplot.html) example creates a jitter effect using random number generation. Is there a way to set the random seed so that the plots are reproducible?

Vega has a [`setRandom`](https://vega.github.io/vega/docs/api/statistics/#setRandom) method, but I couldn't find an equivalent in Altair

**Comment by jakevdp** [comment]
Unfortunately, there is currently no way to call ``setRandom`` from the Altair API. If it's important to you, you could create an HTML template that includes the ``setRandom`` function in Javascript, export your chart spec, and use that template to view it (all renderers are essentially doing something like this under the hood).

To make this part of Altair would require coordinated changes to the jupyter notebook renderer, the jupyterlab renderer, other frontend renderers, and Altair itself, because we are in a world where frontend scripts are packaged separately from backend scripts.

**Comment by jakevdp** [comment]
Better would be if the Vega-Lite specification could include a way to specify the random seed. It would be worth a feature request in the Vega-Lite project.

**Comment by TTitcombe** [comment]
Thanks for the suggestions and the rapid response 👍

**Comment by TTitcombe** [comment]
For attention of any interested parties who come across this issue:

You can calculate the jitter outside of altair and add it as a column to your data. Then, alter the [stripplot](https://altair-viz.github.io/gallery/stripplot.html) example by pointing `x` to your custom jitter parameter and remove `transform_calculate` from the chart
