### ISSUE TITLE
empty selection

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1809]
Hello Altair folks,

I have two charts concatenated together. I am using an interval selection on one chart to filter the other. The filtered chart is empty when using the selection as shown here:

![ezgif com-crop (7)](https://user-images.githubusercontent.com/4624246/69675951-c9b84d80-106d-11ea-8638-a5204db28dff.gif)

Here is a reproducible example (Altair version 3.2.0):

```python
import altair as alt
import pandas as pd
from vega_datasets import data

source = data.iris().sample(frac=.1)
source=source.reset_index()
brush = alt.selection(type='interval')

l=alt.Chart().transform_fold(
    ['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth']
).mark_line().encode(
    x='key:N',
    y='value:Q',
    color=alt.condition(brush, 'species:N', alt.value('lightgray')),
    detail='index:N',
    opacity=alt.value(0.5)
).properties(width=500).add_selection(
    brush
)

n=alt.Chart().mark_text().encode(
y='index:N',
text='index:N',
color='species:N'
).properties(width=500).transform_filter(brush)

alt.concat(l,n, data=source)
```

Is anyone able help me to see what I am doing incorrectly?

**Comment by jakevdp** [comment]
Using an interval selection with a line marker is not well supported, and should be avoided.

Essentially the issue is this: your selection is keying on the x and y encodings, which are not present in the data source for the text chart, and so there's no way to propagate the selection to that chart.

If you change your selection to, for example
```python
brush = alt.selection_single(fields=['index'])
```
you will see that the selection propagates correctly (``index`` is available in both data sources) but unfortunately interval selections can only key on x and y encodings, so what you want to do is currently impossible in the Vega-Lite grammar.

There is a Vega-Lite feature request concerning this somewhere, but I can't find it at the moment.

**Comment by Alcampopiano** [comment]
Thanks very much Jake. This makes sense. I'll try to find the issue and link it here. Take care.
