### ISSUE TITLE
mark_rect height not working

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#1840]
jupyterlab 1.2.1
altair 3.3.0

When I was researching this, it did appear as though this should work as per the vega-lite documentation:
https://vega.github.io/vega/docs/marks/rect/

> For marks that support width and height settings (including rect and area), the horizontal dimensions are determined (in order of precedence) by the x and x2 properties, the x and width properties, the x2 and width properties, or the xc and width properties. If all three of x, x2 and width are specified, the width value is ignored. The y, y2, yc and height properties are treated similarly.

If I am reading that right - since I have not specifying both y's it should work,

*Reproducible example*:
```python
import pandas as pd
import altair as alt

data = {'sourceof': {0: 0, 1: 1},
 'start_date': {0: '2019-09-10',
  1: '2019-08-20'},
 'due_date': {0: '2020-03-06',
  1: '2020-01-03'}}

df = pd.DataFrame(data)

alt.Chart(df).mark_rect(height=3, filled=True, opacity=1, strokeWidth=3, color='pink', cornerRadius=5).encode(
    x='start_date:T',
    x2='due_date:T',
    y='sourceof:N')
```

That should yield this plot:
![visualization](https://user-images.githubusercontent.com/1798497/70173722-6ea3dd80-16a1-11ea-8f02-3507bb722253.png)

When adjusting the height parameter there is no effect.
**However**: when I do _open in vega editor_ I get this:
<a href="https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjKCFICMBDaAa1QCdYBXeAE0ygHcALZAFwFNIAacXSAG7IOjBsEiNktNswYAWAAwLuUZhzTM2DAMxKAvr1xQAtoXIkxkNrFgAbNsgAODeFVu29fA30i1CbQkt4QmMuLF9-QgBaAA5tAHZ4gDZoQkQk+I4AVgBGeMQsrI5CLIAmeIBOBVokjlLS-HicyG88U3MxPjw2AE9HMKhyDmgtQ344W1hyBkhHZHgLMbw4cngOcgAlQlpkKgBnBiylqBR3DnosNnIqDmPINQ0tLCOuqFhHYnYehhy7vavYCQOAB1KQyHReMaQDjwOA7eDoLA4fgAD0svX6M04xkcU0Ith4J2EtguUH+ZjYAH0-JwWncUaVLCgOCSZrQbtT-FxWvxvkirH0BpB4LBjPN8YTIMzWeE9tRyNAOLBEC1IT4ACR7aBqUwzTRsRx7DAAemNAg4qEIADpUOxmFR8FbkLBjVqdYQzRborZ2BwzdorXIrQorQArOXwHg+GmEPYcNgHJGvCIBWIJZKpdKZXL5QrFMqVaq1eqNZpYADarwgyKMeDlVAVSpVWGUVf45PIVJpQtKChyFSiCgHOQUUdr-HZHE5tPCvd7g+0g6SkDbPKMNdrkHrjeVP2ORi3AU7057fYHChiUV7Y-HUEnJ5mc4Ug5yC5X488RgAul4QHogA">long link</a>

and when I adjust the height parameter there it works:
![image](https://user-images.githubusercontent.com/1798497/70173850-baef1d80-16a1-11ea-85a4-bc8bd1086719.png)

I am not sure if that site runs a newer version of vega-lite or if this is a bug in altair - or if I am doing something wrong.

**Comment by jakevdp** [comment]
The vega editor is currently running Vega-Lite v4.0.0.rc12, which accounts for the differences there (the semantics of chart-level width and height are different in vega-lite 4).

The JupyterLab renderer is pinned to some older version of Vega-Lite depending on what version of the extension you have installed, and it is not straightforward to determine what version that is.

If you're on Altair 3.3, I'd suggest using ``alt.renderers.enable('html')``, which bypasses the Jupyterlab extension altogether and uses that version of Vega-Lite that Altair 3.3 is built on. I find when I do this, the height of the bars works correctly:
```python
alt.Chart(df).mark_rect(height=3, filled=True, opacity=1, strokeWidth=3, color='pink', cornerRadius=5).encode(
    x='start_date:T',
    x2='due_date:T',
    y='sourceof:N'
)
```
![visualization (33)](https://user-images.githubusercontent.com/781659/70177297-f3d1c700-168e-11ea-88e2-616821d4c53e.png)

```python
alt.Chart(df).mark_rect(height=20, filled=True, opacity=1, strokeWidth=3, color='pink', cornerRadius=5).encode(
    x='start_date:T',
    x2='due_date:T',
    y='sourceof:N'
)
```
![visualization (32)](https://user-images.githubusercontent.com/781659/70177300-f59b8a80-168e-11ea-8b6b-87945c4eaf94.png)

In Altair 4.0, the HTML renderer will be the default, which will hopefully prevent confusion due to silent mismatches between frontend and backend versions.

**Comment by jakevdp** [comment]
Also, if you want the marks to automatically fill the vertical space, consider using ``mark_bar()`` rather than ``mark_rect()`` with a custom height.

**Comment by afonit** [comment]
Jake, thanks,
the 'html' works perfect.  Also as a side benefit I just noticed - with lab and voila, I had been using 'kaggle' but I had to comment it out to work in lab, then enable it for voila to work with the plots.  However, using 'html' allows the plots to work in both.

**Comment by jakevdp** [comment]
Great! The ``html`` renderer should also work in nbviewer, nbconvert, zeppelin, databricks, Colab... the possibilities are endless :smile:
