### ISSUE TITLE
properties(width={'step':x} not working

### ISSUE THREAD

**Issue by samesand** [altair-viz/altair#1873]
I'm trying to use the {'step': value} to avoid the bars in a chart overlapping the chart axis, but it's not working, the chart width remains the same regardless of the value I use. Here is my code:

`alt.Chart(mix).mark_bar(size=30).encode(x=alt.X('proddate', title='Date'), y='count(wafer)', color='tech').properties(width={"step":300}, height=400, title='Wafers by Technology').configure_view(step=300)`

![chart](https://user-images.githubusercontent.com/38790017/70824334-e73c2580-1d96-11ea-8024-18d887e7877f.png)

**Comment by jakevdp** [comment]
The step argument only applies to categorical axes (nominal or ordinal), not continuous axes (temporal or quantitative). Yours is a temporal axis.

It's hard to tell without seeing your data, but perhaps setting the x-encoding to ``"monthdate(proddate):O"`` would make it behave as you expect?

**Comment by Alcampopiano** [comment]
Hello @samesand 

To add to what Jake suggests in case it helps. 

I think that `width={'step': value}` is redundant with `.configure_view(step=300)`. Either of them alone work to make the chart wider, putting some space between the bars. Also, I think that `.properties(width=value)` may be enough to prevent the bars from overlapping (since the chart will get wider).

Here is are the reproducible examples that I was testing with:

```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar(size=50).encode(
    x=alt.X('variety'),
    y='sum(yield)',
    color='site'
).properties(width={"step":100}, height=400)
```

![visualization](https://user-images.githubusercontent.com/4624246/70832168-67c44b80-1dc2-11ea-82b7-120bbd724602.png)

```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar(size=50).encode(
    x=alt.X('variety'),
    y='sum(yield)',
    color='site'
).properties(height=400).configure_view(step=100)

```
![visualization (1)](https://user-images.githubusercontent.com/4624246/70832452-22ece480-1dc3-11ea-92b1-c706b8fbd73c.png)

**Comment by samesand** [comment]
> It's hard to tell without seeing your data, but perhaps setting the x-encoding to `"monthdate(proddate):O"` would make it behave as you expect?

yes, this did it. Thank You!
