### ISSUE TITLE
is it possible to force `gradient` type legend on Nominal fields?

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair#1879]
Hi,
This is actually a question instead of an issue. 
- Question:
May I know if it is possible to force using `gradient` type legend on Nominal fields?
- Background:
When the number of unique values in a nominal field is too large, the generated legend will show an extremely long list, extending out of the main "window" of a chart, e.g.:
``` python3
import altair as alt
from vega_datasets import data

alt.Chart(data.cars()).mark_point().encode(
    x='Acceleration:Q',
    y='Miles_per_Gallon:Q',
    color=alt.Color('Name:N', legend=alt.Legend(type='symbol'))
)
```
<details><summary>The chart</summary>

<img src="https://user-images.githubusercontent.com/10766549/71021518-6a20f100-20b3-11ea-95e6-caa8f7a1a83e.png" alt="very long legend example">

</details>

As you can see that the legend is very long, and also the entries are ordered alphabetically. And since they are ordered anyway, I wonder if it is possible to control the appearance of the legend to look like the legend appearance of `Quantitative` fields. Something like this:
![Screen Shot 2019-12-17 at 10 10 44 AM](https://user-images.githubusercontent.com/10766549/71022725-051aca80-20b6-11ea-9531-5cdab67dc45a.png)

Thank you very much~

**Comment by jakevdp** [comment]
There's no built-in way to do this, by design – since there is no quantitative relationship between nominal labels, there's no way to define a continuous scale for them. In the example scale that you give, for example, there is no way for the reader to know what the midpoint between a subary and a vw rabbit represents. This probably means that color is the wrong encoding to choose for your particular data.

Have you considered using a tooltip encoding to represent the value for each point? That avoids listing all entries in a static scale, but still lets the viewer of the chart see what the values are.

**Comment by xujiboy** [comment]
@jakevdp Thank you very much for the explanation Jake. I am trying to mimic the "table plot" from R (https://cran.r-project.org/web/packages/tabplot/vignettes/tabplot-vignette.html), and I have used Tooltips but still want the chart itself to be more informative when viewed as a static image. Your last comment is very interesting:
> If you really want to represent your nominal data on a continuous scale with elided labels, you could do it using a calculate transform mapping your data to a continuous field, plus a custom color scale.

I think I will dig a little more on that front. Thanks again~
