### ISSUE TITLE
Inconsistent errors

### ISSUE THREAD

**Issue by lc0** [altair-viz/altair#1894]
First of all, I'd like to thank all developers and contributors for this amazing library!
Lately, I more and more use Altair and enjoying it pretty much.

Now, to the issue:
I highly appreciate it when a library provides verbose errors that allow the user to fix a problem more quickly. In many cases, that's what Altair does in the first place. Besides this piece, that might be a bug.

if we have simple example like

```python
import altair as alt

from vega_datasets import data
stocks = data.stocks.url

alt.Chart(stocks).mark_line().encode(
    x='dateq',
)
```
That, unfortunately, has a typo in a column name. The error that we get is 
```
ValueError: dateq encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.
```

That is not the most specific. In reality, the [place in code](https://github.com/altair-viz/altair/blob/master/altair/vegalite/v4/schema/channels.py#L41), that I think, checks it

Returns a type, that is not Pandas Dataframe. 
![image](https://user-images.githubusercontent.com/775466/71696329-00902a80-2db5-11ea-8ee9-af567939ae69.png)

If we pass is a dataframe, without Altair's magic
![image](https://user-images.githubusercontent.com/775466/71696475-5533a580-2db5-11ea-94ee-acd6e5e2404d.png)

We would get a proper error message 
```
ValueError: dateq encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.
```

My suggestion would be to add another check and communicate it properly in this case as well.
I am happy to contribute if anybody will point me in the right direction

**Comment by jakevdp** [comment]
Thanks for the suggestion.

In general, the reason errors are not more specific in cases like this is because much of the rendering logic for Altair is in Javascript, and giving more specific errors would require replicating the JS-side logic in Python. We tried this early-on and found that it was quite brittle, leading to false-positive errors in unanticipated cases, or when the JS-side logic changes.

For example, with the above spec, you might think about printing something different if the column does not appear in the input dataframe. But consider this case:
```python
import altair as alt

from vega_datasets import data
stocks = data.stocks.url

alt.Chart(stocks).transform_calculate(
   dateq='datum.date'
).mark_line().encode(
    x='dateq',
)
```
To give the "correct" error here, we'd have to check the spec to make certain that transforms do not define the column in question. Similarly, data may be defined in an upper layer of the chart, or via a table with a dynamic signal, or via a number of other means. Replicating the parsing logic to get the error correct in all those nuanced situations is quite involved, subject to errors in numerous corner cases, and brittle over time.

**Comment by lc0** [comment]
Thank you for explaining the issue! Especially given:

> when data is specified by URL, the Python code never actually touches the data

I was not sure how it's implemented when data specified by URL. I guess in this case Altair does its best being explicit with errors
