### ISSUE TITLE
selection on fields=[fieldname:N] generates :N in vega-lite fields but should not

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#1895]
Copied from https://github.com/vega/vega-lite/issues/5710:

if I call `selection = alt.selection_multi(fields=["advance_mode:N"], bind='legend')`, Altair 4.0.0 generates

```json
"selection": {
    "selector009": {
      "type": "multi",
      "fields": ["advance_mode:N"],
      "bind": "legend"
    },
```

but I believe it should drop the `:N` and generate

```json
"selection": {
    "selector009": {
      "type": "multi",
      "fields": ["advance_mode"],
      "bind": "legend"
    },
```

The latter has the intended behavior AFAICT.

**Comment by jakevdp** [comment]
The ``:N`` shorthand should only be used when specifying encodings. That is, rather than writing
```python
chart.encode(
  x=alt.X('advance_mode', type='nominal')
)
```
you can write
```python
chart.encode(
  x='advance_mode:N'
)
```
In other places that field names are specified, no type is required, and so no type parsing is performed. Thus when defining your selection you should use
```python
selection = alt.selection_multi(fields=["advance_mode"], bind='legend')
```
This has been the behavior since selections were introduced in Altair version 2.0.

**Comment by jowens** [comment]
OK. My use case is that I have a variable that stores the field of interest, and I want to use that variable in two places (encoding and selection). I can put in a `strip()` command in the selection call, but it seems cleaner if Altair did it; but it's an easy piece of code, no worries. Thanks!

**Comment by jakevdp** [comment]
In that case you should store the actual field name (without the ``:N``) and specify the encoding type separately.

**Comment by jowens** [comment]
OK. I can do that. Thank you for the advice.

**Comment by jakevdp** [comment]
The reason Altair doesn't do this automatically is because it requires assuming too much about user intent. For example, it's possible to have dataframe columns with colons in their names.

We could go down the rabbit hole of checking dataframe column names to infer the intent of the user, but then what about remote data? And what about transforms that define new data fields? There are a **ton** of potentially surprising corner cases and pitfalls as soon as you try to infer user intent from incomplete information, and so Altair has chosen to avoid that. As they say, explicit is better than implicit.

**Comment by jowens** [comment]
Totally sensible. I appreciate the explanation!
