### ISSUE TITLE
what rendering in Jupyter notebook should i expect by default?

### ISSUE THREAD

**Issue by cmorgan** [altair-viz/altair#190]
it seems that a png in is rendered but at low quality or resized to give loss in image quality in the notebook. Is this the default behaviour? I was expecting a more webby rendering in svg?

I'm on Windows, Python 2.7 installed from conda-forge

**Comment by jakevdp** [comment]
In a live notebook, you should see a live rendering dynamically constructed by ``vegalite.js``. But because github and other hosting services scrub javascript in displayed notebooks, on save we also render a PNG view and save it in the cell metadata. That way when you open the notebook on github, rather than seeing nothing, you see a PNG rendering.

**Comment by cmorgan** [comment]
thanks thought so. looks like i have a problem with vegalite.js, on my box i'm only rendering super ugly png's

**Comment by jakevdp** [comment]
You might try updating jupyter notebook – there is a bug in older versions that caused the PNG to replace the vegalite rendering prematurely.

**Comment by jakevdp** [comment]
This was a bug in Jupyter, and should be fixed now.
