### ISSUE TITLE
Jupyter lab action menu rendering issue in Firefox

### ISSUE THREAD

**Issue by zeqianli** [altair-viz/altair#1916]
Hi, I encountered the same issue in #1845 except I don't have any extension installed. 

- I'm running python 3.7.6, jupyterlab 1.2.4, altair 4.0.0 on Firefox 72.0.1 and MacOS 10.14.6. 
- No jupyter extension was installed. 
- It only happens for altair 4.0.0. On altair 3.2.0 it was fine. 
- It only happens in Firefox. It's fine in Safari 13.0.4 and Chrome 79.
- It only happens in jupyter lab. It's fine in notebook on Firefox. 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/36593276/72368346-83718900-36c3-11ea-9fbe-efb83e63e5b5.png">

**Comment by jakevdp** [comment]
This is likely due to another JupyterLab extension that you have installed adjusting global CSS stylings in a way that affects all other outputs. If you uninstall other extensions, it should fix the issue. See https://github.com/altair-viz/altair/issues/1845.

To list your installed extensions, run
```
$ jupyter labextension list
```
**from within the shell environment that you used to launch JupyterLab**.

The reason this doesn't happen in Altair 3.X is because jupyterlab rendering in 3.X is accomplished via an Altair-specific frontend extension.

The JupyterLab team has not yet released a version 4.0-compatible frontend extension; once they do, you will be able to run ``alt.renderers.enable('jupyterlab')`` to use that extension and fix the issue that way.

If none of the above advice is helpful, please use your browser object inspector to investigate what CSS properties are affecting the size of the options menu, and report back.

**Comment by zeqianli** [comment]
Hi Jake, thanks for the reply. 

- No extension was installed: 
```
$ jupyter labextension list
JupyterLab v1.2.4
No installed extensions
```
- Thanks for clarifying the JupyterLab compatibility issue. Maybe I'll use notebook for now before the release. 
- I'll look into CSS properties and report later.

**Comment by jakevdp** [comment]
Is it possible that you were using HTML outputs in other cells of notebooks within the same jupyterlab session? What happens if you close all notebooks, reload jupyterlab to clear any CSS that's been loaded in the DOM, open a new notebook, and create a chart?

**Comment by zeqianli** [comment]
It solved the problem! Thanks!
