### ISSUE TITLE
bug with binning?

### ISSUE THREAD

**Issue by dchudz** [altair-viz/altair#1936]
@jakevdp you mentioned I should feel free to reopen https://github.com/altair-viz/altair/issues/1932 but I don't think I can ("you cannot re-open your own issues if a repo collaborator closed them.").

So I hope you don't mind a new issue, since this does still seem like a bug to me, or at least I'm very confused:

My previous examples were probably unclear (sorry) so here's an example I took straight from the docs (with small changes in the data; no changes to the charting code at all) and no density transform:

```
import pandas as pd
import altair as alt
import numpy as np

N=20

# just like this example (https://altair-viz.github.io/gallery/layered_histogram.html),
# except I replaced the normals with `np.linspace`, and now N is 20 instead of 1000.
def draw_chart(trial_a_start, trial_a_end):
    # Generating Data
    source = pd.DataFrame({
        'Trial A': np.linspace(trial_a_start, trial_a_end, num=N),
        'Trial B': np.linspace(10, 11, num=N),
        'Trial C': np.linspace(11, 12, num=N),
    })

    return alt.Chart(source).transform_fold(
        ['Trial A', 'Trial B', 'Trial C'],
        as_=['Experiment', 'Measurement']
    ).mark_area(
        opacity=0.3,
        interpolate='step'
    ).encode(
        alt.X('Measurement:Q', bin=alt.Bin(maxbins=100)),
        alt.Y('count()', stack=None),
        alt.Color('Experiment:N')
    )
```

![Screen Shot 2020-01-29 at 8 19 03 AM](https://user-images.githubusercontent.com/1222726/73360021-112aa800-4270-11ea-975a-3480a72157ab.png)

I have altair `4.0.1` and python `3.7.6`.

**Comment by dchudz** [comment]
Very little is different between the two invocations of `draw_chart` (and very little is different between my usage and the docs). So it seems like the first example should work, but it doesn't.

**Comment by jakevdp** [comment]
There is no problem here with the binning – replace ``mark_area()`` with ``mark_bar()`` and you can see that the bins are created correctly.

The issue is that when your data lies in a single bin, only that single bin is returned, and trying to draw a line or an area mark from a single point results in no chart.

You can strip away all the bin logic and reproduce this directly by drawing a plot from a single data point:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({'x': [0], 'y': [1]})

alt.concat(
    alt.Chart(data, title='bar').mark_bar().encode(x='x', y='y'),
    alt.Chart(data, title='area').mark_area().encode(x='x', y='y'),
)
```
![visualization - 2020-01-29T060349 732](https://user-images.githubusercontent.com/781659/73363202-20ecc100-425d-11ea-97a8-0ce2fbf68a9a.png)

Just as in your example, the bar mark results in a single bar, and the area mark results in drawing the area below a zero-dimensional point, so nothing is shown.

I believe this is working as intended.

**Comment by jakevdp** [comment]
I think the issue comes from the assumption that binnings would return all bins for each sequence, even if zero values lie in the bin. This is a relevant vega-lite issue regarding imputing values within empty bins: https://github.com/vega/vega-lite/issues/5403 (TLDR, there is no good solution at the moment).

**Comment by dchudz** [comment]
Interesting. Thanks check!

**Comment by dchudz** [comment]
Interesting. Thanks for the explanation! I appreciate it.
