### ISSUE TITLE
WSL + jupyterlab - very large options button

### ISSUE THREAD

**Issue by jcmgray** [altair-viz/altair#1957]
This is a slightly odd one, currently if I make an `altair` plot in jupyterlab using the windows subsystem for linux (WSL) I get a rather large options button:
```python
import numpy as np
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': np.random.randn(100),
    'y': np.random.randn(100),
})

alt.Chart(df).encode(x='x', y='y').mark_point()
```

![Capture](https://user-images.githubusercontent.com/8982598/74058571-2f448680-499b-11ea-907d-8429178a3be7.PNG)

### Versions:

altair : master or conda
OS: Windows 10 + ubuntu WSL
jupyterlab: 1.2.6 (perhaps relevant: when I run `jupyter labextension install @jupyterlab/vega6-extension` I get an error 'ValueError: "@jupyterlab/vega6-extension" is not a valid npm package'` and indeed issue is fixed if I ``import altair.vegalite.v3 as alt``.

**Comment by jakevdp** [comment]
This is due to overzealous CSS elsewhere in your JupyterLab window, either in a front end extension or in the output cell of a notebook (not necessarily the current notebook).

Try closing all your notebook tabs in Jupyterlab, then reloading the browser window. If that doesn't work, disable frontend extensions that may be affecting CSS styles and re-launch JupyterLab.

More details: #1845, #1916, #1923
