### ISSUE TITLE
Default renderer in Altair 4 does not render plots in a Jupyter notebook on GitHub.com

### ISSUE THREAD

**Issue by firasm** [altair-viz/altair#2000]
Pre-v4, Altair plots inside a Jupyter notebook rendered very nicely on Github.com - this allowed our TAs to mark the HTML rendering of Jupyter notebooks on GH.

However since upgrading to Altair 4, this handy feature is now broken - likely because the renderer changed.

Here's an example in [my repo](https://github.com/firasm/bug_reports/blob/master/altair_renderer.ipynb).

I have found a workaround by switching to the `png` renderer, but of course this has the consequence of disabling the nice interactive features in Altair.

Could you suggest which renderer we should switch to so that we can still have interactive features in our notebook, and have it render as an image on GH ?

<img width="1366" alt="Screen Shot 2020-02-29 at 6 19 01 PM" src="https://user-images.githubusercontent.com/2507459/75618210-f756dc00-5b1f-11ea-9784-e0c1650ae76d.png">

**Comment by jakevdp** [comment]
This is by design – github scrubs all javascript from outputs before rendering, so Altair charts will not be displayed.

The JupyterLab and Juptyer Notebook renderers add a PNG output to the notebook when they render a chart, but there were a lot of issues that led to them being bad choices as the default renderer. Because of the Jupyter security model, it's impossible for the frontend to add a PNG to the output when not using a frontend extension, and having the backend add a PNG to the output requires a lot more system-specific setup that we were not comfortable requiring for basic altair use.

If you want to restore the pre-V4 behavior, you'll have to use ``alt.renderers.enable('jupterlab')`` and ensure that your JupyterLab frontend has the appropriate renderer for Altair version 4, which I believe doesn't yet exist.

**Comment by jakevdp** [comment]
You can open the github-hosted notebooks in nbviewer if you want to be able to view Altair charts. I use the [Open in nbviewer](https://jiffyclub.github.io/open-in-nbviewer/) browser extension.

**Comment by firasm** [comment]
Makes sense. Thanks for the explanation!

**Comment by firasm** [comment]
Actually @jakevdp you pointed me in the right direction. As of 2 days ago, Jupyterlab 2.0 was released which includes the vega5 and vega-lite4 renderers!

From the v2 [changelog](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v2-0-0):

>Removed the vega 4 and vega-lite 2 renderers (vega 5 and vega-lite 4 is included in JupyterLab by default). These legacy renderers may be available via custom extensions (#7650, #7523, #7658)

----

So after updating to Jupyterlab v2, I solved the issue by setting `alt.renderers.enable('mimetype')` at the top of my notebook.

**Comment by jakevdp** [comment]
Great! Note one other difference: with the default renderer, charts on nbviewer will be interactive. With the mimetype renderer, they will be static (because nbviewer doesn't have the frontend extension necessary to render vega-lite mimetypes).
