### ISSUE TITLE
Unable to apply tooltip in bar graph

### ISSUE THREAD

**Issue by jaseuts** [altair-viz/altair#2131]
When I ran this code
```
barChart = alt.Chart(subset).mark_bar().encode(
    x=alt.X('neighbourhood', type='nominal', sort='-y', title='Neighbourhoods'),
    y=alt.Y('count(id):Q',  title='Number of Airbnbs'),
).properties( 
    width=600,
    height=400
)

st.altair_chart(barChart)
```
It produced a correct bar graph below
![Graph 1](https://user-images.githubusercontent.com/11934573/80894696-a1b9ce00-8d20-11ea-96f5-522d108073b7.JPG)

But if I tried to apply tooltip to the same graph
```
barChart = alt.Chart(subset).mark_bar().encode(
    x=alt.X('neighbourhood', type='nominal', sort='-y', title='Neighbourhoods'),
    y=alt.Y('count(id):Q',  title='Number of Airbnbs'),
   tooltip=['neighbourhood', 'host_name', 'count(id)']
).properties( 
    width=600,
    height=400
).interactive()

st.altair_chart(barChart)
```
A graph with incorrect count and order would be generated
![Graph 2](https://user-images.githubusercontent.com/11934573/80894752-5a800d00-8d21-11ea-8d4d-fc384723998a.JPG)

Could you please advise whether this was a bug or I did something wrong? Thanks

**Comment by jakevdp** [comment]
This is working as intended. When you specify an aggregate within an encoding, it is applied after grouping by the other unaggregated encodings.

In the first chart, the count is grouped by `'neighborhood'`, because it is specified in the x encoding.

In the second chart, the count is grouped by `'neighborhood'` and `'host_name'`, because these encodings are specified by x and tooltip.

If you want the chart to be unchanged with the tooltip, you can specify an aggregate for ``host_name``, such as ``'min(host_name)'`

**Comment by jaseuts** [comment]
Thanks @jakevdp for the enlightenment. Much appreciated.
