### ISSUE TITLE
Data without values are rendered in line graph

### ISSUE THREAD

**Issue by morberg** [altair-viz/altair#2139]
I hope this example is clear enough. Although there is no snow during the summer the line in the graph indicates that there is. I would expect the color of the bottom line to be green and not red when there is no snow.

```python
import altair as alt
from vega_datasets import data

source = data.seattle_weather()

alt.Chart(source).mark_line(
).encode(
    x='month(date):O',
    y=alt.Y('count():Q', stack=True),
    color=alt.Color('weather:N', scale=alt.Scale(scheme='dark2'))
)
```

<img width="369" alt="image" src="https://user-images.githubusercontent.com/956034/81153445-37ed2e80-8f83-11ea-8783-7ab915070f35.png">

**Comment by jakevdp** [comment]
Since you specified ``stack=True`` and ``snow`` is the second entry in the stack, the number of snowy days is indicated by the space between the "sun" and "snow" lines. I believe the data is accurately reflected in the chart.

If you want to filter values with zero count so that they don't appear in the chart, you could do that with a [filter transform](https://altair-viz.github.io/user_guide/transform/filter.html) or an [impute transform](https://altair-viz.github.io/user_guide/transform/impute.html).

**Comment by morberg** [comment]
Thank you for your quick answer. I'll take a look at the transforms (or perhaps another way of showing the data).
