### ISSUE TITLE
Is it possible to concatenate repeated charts?

### ISSUE THREAD

**Issue by taralloc** [altair-viz/altair#2180]
Is it possible to concatenate repeated charts? This code, for example, does not work:
```python
import altair as alt
from vega_datasets import data

iris = data.iris.url

chart1 = alt.Chart(iris).mark_point().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='species:N'
).repeat(
    row=['petalLength', 'petalWidth'],
    column=['sepalLength', 'sepalWidth']
)
chart2 = alt.Chart(iris).mark_point().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='species:N'
).repeat(
    row=['petalWidth', 'petalLength'],
    column=['sepalWidth', 'sepalLength']
)

alt.hconcat(chart1,chart2).show()
```
because it throws this error

> JavaScript Error: Duplicate scale or projection name: "child__row_petalWidthcolumn_sepalWidth_x".

**Comment by joelostblom** [comment]
@taralloc I am going through Altair issues to find those that have been resolved and can be closed. Since this is something that needs to be fixed in Vega-Lite rather than in Altair, would you be able to close this issue or add a comment if there is something you don't think is resolved yet on the Altair side of things?

The relevant vegalite issues are https://github.com/vega/vega-lite/issues/5261 and https://github.com/vega/vega-lite/issues/4680 (although they are not exactly what you are asking here, I reading them and then opening a new Vega-Lite issue)

**Comment by taralloc** [comment]
OK, I'll close this issue. What I wanted to do is still not possible, but it is due to vega-lite.
