### ISSUE TITLE
Altair menu dropdown displays over entire chart

### ISSUE THREAD

**Issue by MattJBritton** [altair-viz/altair#2208]
I recently upgraded one of my Conda environments to 4.1.0, and after doing so I immediately started getting the following display issue. 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/12104506/84730792-38ef8380-af65-11ea-94b7-6bea5c3038bb.png">

The "three dot" menu displays over the entire chart, and so whenever I mouseover the chart the menu becomes opaque, obscuring the chart. This effect persists on any chart I create in this notebook, and is not affected by chart size. The issue also persists after restarting jupyter lab. 

I am using:

jupyterlab 1.2.6
jupyter_client 6.1.3
altair 4.1.0

I have Altair 4.1.0 on several other environments on this machine, and none of them have had this problem. 

Thanks in advance!

**Comment by jakevdp** [comment]
This is a known issue (see #1845, #1916, #1923, #1938, #2123, etc.) and is happening due to CSS defined elsewhere in your jupyterlab frontend, either in a labextension or the cell output of a notebook in the current session.

To address this, follow the steps here: https://github.com/altair-viz/altair/issues/2123#issuecomment-621557957

I have never been able to reproduce this issue, and so have not been able to identify the root cause or work on a fix. If you're able to use your browser tools to find the source of the offending CSS, please let me know!

**Comment by MattJBritton** [comment]
Thanks for the solution! And apologies that I missed the known issue. I wasn't able to find the exact CSS via browser tools, but one thing I have in common with others who have experienced this problem is the use of Jupyter Widgets. In particular, I was using the following in another instance of Jupyter Lab. 

```py
    options_layout = ipywidgets.Layout(
        overflow='auto',
        border='1px solid black',
        width='300px',
        height='300px',
        flex_flow='column',
        display='flex'
    )
```

**Comment by jakevdp** [comment]
Nice - thanks for the clue! I'll see if I can reproduce it from that.
