### ISSUE TITLE
"format" for labels in facet do not work - shows a constant 70 for any year value

### ISSUE THREAD

**Issue by armsp** [altair-viz/altair#2254]
I have tested this on 2 different datasets and both seemed to have the same issue, so this might be a bug.

We will use one of the internal examples - [US Population: Wrapped Facet](https://altair-viz.github.io/gallery/us_population_over_time_facet.html)

```py
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_area().encode(
    x='age:O',
    y=alt.Y(
        'sum(people):Q',
        title='Population',
        axis=alt.Axis(format='~s')
    ),
    facet=alt.Facet('year:O', columns=5, header=alt.Header(format="%y", formatType='time')),
).properties(
    title='US Age Distribution By Year',
    width=90,
    height=80
)
```
Output shows 70 for all the year labels.
![format_error](https://user-images.githubusercontent.com/12681262/89105372-23afb500-d43e-11ea-9097-7932b409d3e3.png)

**Expected output**
Correct year without century as a decimal number - [50, 60, 70, 80....]

**Comment by armsp** [comment]
@jakevdp any clue why Altair treats the years as 1970 and shows 70 for all the years when `"%y"` format is specified ?

**Comment by armsp** [comment]
Converting the datatype of year column from `int` to `datetime` made it work. However, the conversion itself does not play well with the data as it also adds day and month to the data. 

But then I don't think there is another way to fix this.
Feel free to close it maybe after confirming that this is indeed the case.

**Comment by jakevdp** [comment]
The issue is that these are not timestamps, these are integers. When you specify that an integer should be interpreted as a timestamp, it is interpreted as a unix timestamp (i.e. milliseconds since january 1st, 1970). Since all of your timestamps fall in the first few seconds of 1970, the result is what you see in your chart.

The way to fix this is to either (1) explicitly convert your integer years to timestamps, either as a preprocessing step, or using a transform in the chart, or (2) not use time formats for your integers.

**Comment by armsp** [comment]
Thanks for this, it helps with the explanation why everything becomes 70.
