### ISSUE TITLE
Show plots in jupyter notebook uploaded to github

### ISSUE THREAD

**Issue by fschran** [altair-viz/altair#2264]
It would be really practical to see the output of an altair graph created within a jupyter notebook and then uploaded to github for collaboration. This works, for instance, with matplotlib.

Would that be possible with altair?

**Comment by jakevdp** [comment]
Altair charts are rendered via javascript, and github scrubs all javascript output from display. Unfortunately, Altair has no control over that policy.
One way around this is to use the PNG renderer to produce static figures that will render on github; another option is to use http://nbviewer.jupyter.org which does render javascript figures.

**Comment by Philliec459** [comment]
I am running my Altair Jupyter Notebook and capturing the interaction with LICEcap as an animated gif file. You can show the interaction, but cannot actually have it line in a notebook where the other user can interact with the data.

**Comment by joelostblom** [comment]
@fschran You can also use `alt.renderers.enable('mimetype')` to have a PNG and interactive spec created so that when the Vega JS cannot be loaded it will show the PNG as a fallback, but your charts are still interactive in the notebook. I am going to close this issue as resolved, but please feel free to reopen if you have additional comments.
