### ISSUE TITLE
[RANDOM DATATYPE] is not JSON serializable

### ISSUE THREAD

**Issue by davidberenstein1957** [altair-viz/altair#2272]
When passing an arbitrary Pandas DataFrame to the 'altair.Chart' function, I would expect that only the columns that are actually used for rendering the visualization should result in an [RANDOM DATATYPE] is not JSON serializable error, however,  'altair.Chart' first seems to check whether any data from any arbitrary column in the DataFrame is JSON serializable, while not giving reference as to which column or data it is referring to when giving the error.

**Comment by jakevdp** [comment]
This is by design. If you don't want a particular column to be serialized in the chart, you should remove it from the dataframe.

Why doesn't Altair do this automatically? Mainly because it's very difficult to faithfully determine what columns from a dataset are actually used by a chart specification without re-implementing the entire Vega & Vega-Lite grammars in Python.

**Comment by davidberenstein1957** [comment]
Thank you for the quick response. Good to know. I already figured that might have been by design, but know I also know why. Thank you for explaining why.
