### ISSUE TITLE
What exactly does "fields" mean in selections?

### ISSUE THREAD

**Issue by armsp** [altair-viz/altair#2274]
I have been working with bindings and selections and while fiddling with an example I had in mind I noticed something peculiar in the docs which I don't understand - the usage of `fields` in **selections**.

Take [this example](https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions) from docs -
Important code -
```py
slider = alt.binding_range(min=0, max=100, step=1, name='cutoff:')
selector = alt.selection_single(name="SelectorName", fields=['cutoff'], bind=slider, init={'cutoff': 50})
```
We will focus on `name` in `slider` and `fields` in `selector`.
Q) I think `name` is just a string placeholder used for displaying purposes?

Based on what I [read here](https://altair-viz.github.io/user_guide/interactions.html#selection-targets-fields-and-encodings), `fields` are nothing but dataframe columns and encodings are self-explanatory.

I looked at the doc for [`selection_single`](https://altair-viz.github.io/user_guide/generated/api/altair.selection_single.html#altair.selection_single) and corresponding [doc](https://vega.github.io/vega-lite/docs/project.html) from vega-lite. But it still doesn't make sense to me.

**Why?**
There is NO `cutoff` field in the dataframe we pass to `Chart`.

Moreover, if you run the code below, where we replace `cutoff` with `xval` which is a field in the dataframe, then we see the **exact same output.**

```py
slider = alt.binding_range(min=0, max=100, step=1)
selector = alt.selection_single(fields=['xval'], bind=slider, init={'xval': 50})

alt.Chart(df).mark_point().encode(
    x='xval',
    y='yval',
    color=alt.condition(
        alt.datum.xval < selector.xval,
        alt.value('red'), alt.value('blue')
    )
).add_selection(
    selector
)
```
Can you please tell me what is the role of `cutoff` (I know its purported function) and `fields` here?

**Comment by jakevdp** [comment]
`fields` specifies the field names that the selector projects over. A point is considered in the selection if its value for the specified field or fields is equal to the selection field (for single selections), is one of the selection's fields (for multiple selections), or is within the range of the selections fields (for interval selections).

That example is a bit weird, because the selection field does not correspond to any column in the data, but rather is specified as the name of a value that is referenced in a calculate transform. In this case the field can be an arbitrary string.

Does that answer your question?

**Comment by joelostblom** [comment]
@armsp I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
