### ISSUE TITLE
Integrate altair with ipywidget

### ISSUE THREAD

**Issue by jodzga** [altair-viz/altair#2282]
My understanding is that altair visualizations perform all the interactive work on the browser side and I believe I understand the reason for it: altair is a layer on top on vega-lite so it supports vega-lite interactivity.
However, it would be very helpful to be able to propagate events from the browser to some ipywidget to integrate with ipywidget world. One  example where it would be useful is to do something on selection e.g. show details of selected item.
Does this kind of integration between altair and ipywidget makes sense? Does it already exist? Perhaps someone started working on it already?

**Comment by jodzga** [comment]
It looks like a tool for exploring data and the communication is from ipywidgets to altair but not the other way around. Do you know if this project contains an example of communication from altair chart e.g. selection to ipywidget?

**Comment by joelostblom** [comment]
@jodzga It is not currently possible to emit signals from Altair/VegaLite to Ipywidgets (or any other widget framework). There is some work on this for Jupyter in https://github.com/yifanwu/b2 and for Streamlit in https://github.com/streamlit/streamlit/issues/2263.

Since this is not an issue that Altair can solve, would you mind closing this issue and continue discussion in one of the links above or on the Vega-Lite issue tracker?

**Comment by domoritz** [comment]
If anyone wants to work on this and has questions, I am happy to help.
