### ISSUE TITLE
All interactive plots broken?

### ISSUE THREAD

**Issue by tbenst** [altair-viz/altair#2286]
None of these work for me on the website:
https://altair-viz.github.io/gallery/selection_layer_bar_month.html
https://altair-viz.github.io/gallery/seattle_weather_interactive.html

I also don't get any interactivity in Jupyter.

Not sure if related to https://github.com/altair-viz/altair/issues/2280 or https://github.com/altair-viz/altair/issues/2213.

Edit: seems like **all** interactive plots are broken..?

**Comment by jakevdp** [comment]
Seems to work for me on Google Chrome. Try clearing your browser cache, incase you're running into #2280

**Comment by tbenst** [comment]
Everything working today

**Comment by jakevdp** [comment]
Great!

**Comment by shawnbrown** [comment]
I just ran across this myself... none of the interactive examples were working for me. I searched through the issues to see if this had been reported and I couldn't find much until I searched for closed issues.

It turns out, that I was browsing the gallery on an older system that was running **Firefox 76**. After switching to **Firefox 83**, I can see that it's all working fine.
