### ISSUE TITLE
using locally saved PNGs in mark_image

### ISSUE THREAD

**Issue by Duane321** [altair-viz/altair#2318]
Hello,

I'm trying to use `mark_image` for png's stored locally, and I'm running into some issues.

First, if I use a remote location (using dropbox), it works fine:

```
url = "https://dl.dropboxusercontent.com/s/5jxbltadssmjbbwngk2/EfX_transparent.png"
df = pd.DataFrame(dict(x=[1], y=[1], url=[url]))
alt.Chart(df).mark_image().encode(x='x', y='y', url='url')
```

![image](https://user-images.githubusercontent.com/19956442/96191304-a4883400-0ef8-11eb-8d5c-86b2a9b5a579.png)

I'd rather not have to upload an image to a remote location for altair to reference it. I feel like I must be doing something wrong. Switching out the URL for a local location like url=r'my_folder/EfX_transparent.png' doesn't work. The chart shows up blank.

Though, it looks like something like this should work, as seen here:

![image](https://user-images.githubusercontent.com/19956442/96191550-24160300-0ef9-11eb-934d-9d41ecdb7be2.png)

So, what's the search path for altair? Any ideas would be appreciated.

**Comment by jakevdp** [comment]
You can use any URL visible to your frontend (i.e. JupyterLab, Jupyter Notebook, Colab, VSCode, Streamlit, etc.)

All of those frontends have different mechanisms for accessing local files (if they have a mechanism at all), so there is no way to provide general advice for how to proceed.

**Comment by Duane321** [comment]
Thank you! This helped!

**Comment by armsp** [comment]
@jakevdp I am not sure that this works. In my working directory I have a file called "nasa.jpg". I can read the file via its relative path - basically just its filename - when I use Matplotlib. But in the same notebook, when I make a dataframe with the filename of the image as one of the entries for a column, and try to plot it, I get nothing.

However, plotting the same image by its URI works.

JupyterLab and Colab are able to access the file because Matplotlib reads and shows it, any idea why it's not working with Altair?

**Comment by jakevdp** [comment]
Filepaths visible to Python and URLs visible to your Javascript frontend are not the same thing. You need to figure out how the frontend you are using (jupyter notebook, jupyterlab, etc.) enables HTTP access to local files, and use the appropriate URLs.

**Comment by armsp** [comment]
Ah! I understand it better now...

**Comment by joelostblom** [comment]
If anyone is looking for how to do this in JupyterLab, you need to find the image in the file browser, right click it, select "Copy download link", and (optionally) delete any letters after your image file name so that it looks something like this: `http://localhost:8888/files/path/to/your-image.png`

You could also paste the the actual image as a base64 encoded string by opening an image inside JupyterLab, right clicking, and selecting "Copy image address". The string will look something like this `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIwAAACsCAY...`

**Comment by githubbar** [comment]
> If anyone is looking for how to do this in JupyterLab, you need to find the image in the file browser, right click it, select "Copy download link", and (optionally) delete any letters after your image file name so that it looks something like this: `http://localhost:8888/files/path/to/your-image.png`
> 
> You could also paste the the actual image as a base64 encoded string by opening an image inside JupyterLab, right clicking, and selecting "Copy image address". The string will look something like this `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIwAAACsCAY...`

Thank you! This is what helped to export embedded images in HTML. You can also automate it in code:

`import altair as alt
import pandas as pd
from IPython.display import Image
import base64, io, IPython
from PIL import Image as PILImage

images = ["./videos/pip/peak00.jpg", "./videos/pip/peak01.jpg", "./videos/pip/peak02.jpg"]
imgCode = []


for imgPath in images:
    image = PILImage.open(imgPath)
    output = io.BytesIO()    
    image.save(output, format='JPEG')
    encoded_string = "data:image/jpeg;base64,"+base64.b64encode(output.getvalue()).decode()
    imgCode.append(encoded_string)

x = [0.5, 1.5, 2.5]
y = [0.5, 1.5, 2.5]
source = pd.DataFrame({"x": x, "y": y, "img": imgCode})
alt.Chart(source).mark_image(
    width=50,
    height=50
).encode(
    x='x',
    y='y',
    url='img'
)


# chart.save('chart.html', embed_options={'renderer':'svg'})
# html = '<img src="data:image/png;base64,{}"/>'.format(encoded_string)
# IPython.display.HTML(html)`
