### ISSUE TITLE
Make pandas a soft requirement?

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#234]
Technically we should be able to generate plots without touching pandas at all. It would take a bit of work to make pandas an optional requirement... is that worth the effort?

**Comment by ellisonbg** [comment]
Hmm, not sure given all the data cleaning we have to do before sending it off. But open to this.

**Comment by jakevdp** [comment]
Looking at this again a couple years later, I think this not feasible given the extent that we use pandas for data cleaning and type inference.

**Comment by brunorpinho** [comment]
@jakevdp hello from 2023! 

I think this issue needs to be reopened and it is really important based on the way the ecosystem is evolving. I understand it is a major refactor, but I strongly suggest this as we have fantastic other dataframe utilities apart from pandas. Otherwise, I see two options: 

- someone fork altair and adapt the code base; 
- start a new lib from fresh.

**Comment by jonmmease** [comment]
Hi @brunorpinho, could you say more about the use cases you have in mind?  Are you concerned about wanting to use Altair in environments where it's not possible to install pandas? Or are you more thinking about Altair providing first class support for non-pandas DataFrames?

Altair does support non-pandas DataFrame libraries that adhere to the DataFrame Interchange Protocol (such as pyarrow Tables, Polars, and Ibis). In the coming Altair 5.1, there should be full feature parity between using pandas and, for example, polars as the input DataFrame.

We have talked about eventually making pandas an optional dependency in favor of pyarrow, but I don't think the ecosystem is quite ready for Altair to include a hard dependency on pyarrow (we need to at least wait for pyarrow support in pyodide before making this change).

**Comment by brunorpinho** [comment]
@jonmmease Thank you for your response. I agree with both of your statements.

The reason I am considering reopening this issue is related to a project I'm currently working on. I made the choice to use polars instead of pandas as the exclusive dataframe requirement for an API. This decision was made with the aim of keeping the environment size in check, which would ultimately lead to more efficient processing times and resource utilization.

In light of this, I believe there is potential for major ecosystem components such as altair to naturally progress towards becoming dataframe agnostic. By embracing the dataframe interchange protocol and potentially reducing their dependency on pandas, these components could further align with the evolving landscape of modern libraries.

I hold respect for the work of open-source maintainers like yourself and understand the complexities of making these changes. My intention in suggesting this direction is rooted in the desire to contribute to the growth and efficiency of both the libraries and the broader community.
