### ISSUE TITLE
Include tailing and leading NaN values in date axis.

### ISSUE THREAD

**Issue by htufford** [altair-viz/altair#2340]
I have a df with one row per day for a given time period. Most rows have NaN values for all columns other than date. I want every date included in the x axis, including dates with only NaN values for the other columns. I am using this code:

```
    chart = alt.Chart(df).encode(
        x=alt.X('date:T'),
        y=alt.Y('value:Q'),
        ).mark_point()
```
But all trailing or leading rows with NaN values for "value" are cut off.

E.g., this plot has just one value, but I want to include all leading and trailing dates:

![visualization](https://user-images.githubusercontent.com/29307733/99391561-5922c600-28a8-11eb-99d2-4fe951a5ffef.png)

```
                 date  value
2019-11-18 2019-11-18    NaN
2019-11-19 2019-11-19    NaN
2019-11-20 2019-11-20    NaN
2019-11-21 2019-11-21    NaN
2019-11-22 2019-11-22    NaN
...               ...    ...
2020-11-13 2020-11-13    NaN
2020-11-14 2020-11-14    NaN
2020-11-15 2020-11-15    NaN
2020-11-16 2020-11-16    NaN
2020-11-17 2020-11-17    NaN
```

Is this possible?

**Comment by jakevdp** [comment]
There are two possible approaches I can think of. One is to explicitly set the domain:
```python
import altair as alt
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'date': pd.date_range('2020-06-01', freq='D', periods=10),
    'value': np.where(np.arange(10) == 5, 1, np.nan),
})

alt.Chart(df).mark_point().encode(
    x=alt.X('date:T', scale=alt.Scale(domain=[df['date'].min(), df['date'].max()])),
    y=alt.Y('value:Q'),
)
```
![visualization (12)](https://user-images.githubusercontent.com/781659/99423536-7f9b2e00-28b5-11eb-9b00-73fb226a4acf.png)

Another is to set the `invalid` mark property to `None` (rather than its default of `"filter"`) to specify that you don't want invalid points filtered from the chart. This results in invalid points being drawn at y=0; you can then hide them with an opacity condition:
```python
alt.Chart(df).mark_point(invalid=None).encode(
    x='date:T',
    y=alt.Y('value:Q'),
    opacity=alt.condition('isValid(datum.value)', alt.value(1.0), alt.value(0.0))
)
```
![visualization (11)](https://user-images.githubusercontent.com/781659/99423285-406cdd00-28b5-11eb-8115-833597cc653e.png)
