### ISSUE TITLE
Nothing is drawn when using timeUnit with a field containing escaped dot or bracket

### ISSUE THREAD

**Issue by ph-pi** [altair-viz/altair#2362]
This code sample doesn't work unless you remove the timeUnit argument.

```
data = pd.DataFrame([
    {"date": "2020-06-01T12:00:00", "value": 1},
    {"date": "2020-07-01T13:00:00", "value": 2},
    {"date": "2020-08-01T11:00:00", "value": 1}])
data['dotted.date'] = data['date']

alt.Chart(data).mark_line().encode(
    x=alt.X("dotted\.date:T", timeUnit="yearmonthdatehours"),
    y="value:Q",
)

```

**Comment by jakevdp** [comment]
Note that in Python strings, backslashes need to be escaped unless using raw strings. So rather than `"dotted\.date:T"`, you need to use `r"dotted\.date:T"` or `"dotted\\.date:T"`

That said, this still does not work due to a Vega-Lite bug that has been fixed in subsequent releases. Until Altair updates to a newer Vega-Lite release, a workaround is to display the chart and then click "Open In Vega Editor" to see the result: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLRgJLBQCYAnHUyYw5gBwsYl8ywBGd0zCNsFdgGwAjB7aciAaCgBOANY6ADYk2tyYUJB0JEioIAAeqoQAngAO2sgghJgaBRARCrEg3PCYsXQ6dBCEZXQAOp0AdHqJpXBaAKpQcOIleZiRGryM-YwUEZQgoXm5hcUgAI6kCkTjSnBoAw1NOmg1pCGhACSUYIzlKiVihAWUyAD0XycICj0EONGKRXD04BAvg8nuFfph-vp4mVfiwenYegEegArSjQOq6JQKSiYQgrTJ6BSGYxmSzWWwOJx0FzuTzeXyBYIoADaoH6OlMbAF+jYfmFAQAKgFTMgODK2PjLrFrigAvI2h0+kotgKhSKxZLpbKOKtOLytfzBWxhQB2fUBCRyuUKq7FUxq9qYOiasoW3W2tgS+2O41yM0+ko6q1sOx2gLB+XcRXK5Cq3Tqz3e7WW4UxgOSuNG+XSAC6siAA)

**Comment by ph-pi** [comment]
Thanks !
