### ISSUE TITLE
labelLimit is not solving legend cut-off

### ISSUE THREAD

**Issue by braaannigan** [altair-viz/altair#2381]
Hi

I used to be able to stop my legend text from being cut-off in jupyterlab by using
```
import altair as alt

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).configure_legend(labelLimit=0)
```
This no longer seems to have any effect.

I'm currently working with 
altair==4.1.0
jupyterlab==3.0.1

I tried rolling back to altair 3.1.0 and jupyterlab 2.2.9 but have the same issue of the legend being cut-off.

Can someone try testing the current set-up with the latest releases to see if they can replicate?

**Comment by jakevdp** [comment]
I'm not certain I understand the issue: I ran the code you included and I don't see anything that's cut-off.

**Comment by braaannigan** [comment]
Hi @jakevdp - thank you for replying.

Sure, this is what I get with the same example:
 
![image](https://user-images.githubusercontent.com/10512793/103656777-f0c79b00-4f60-11eb-8eb0-4353482335d6.png)

**Comment by jakevdp** [comment]
OK, I see – I don't think this is a problem with Altair. I think this is a problem with JupyterLab, which for some reason is displaying the chart in a div that is too narrow to show the full chart (you could check this hypothesis by setting the chart width to something smaller, using `chart.properties(width=200)`

Why is this happening? Probably some stray CSS affecting output divs. Due to JupyterLab's architecture, it's hard to guess where this CSS might be coming from: it could be in a frontend extension you have installed, it could be in the rich output of a cell in the current notebook, or it could be in the rich output of **any notebook you currently or previously opened in your jupyterlab session** (yes, I know, yikes!)

Best of luck.

**Comment by braaannigan** [comment]
Cheers.

It might be a browser issue for jupyterlab, as the problem occurs in Brave (i.e. Chromium) but not in firefox I see now.

I can rule out it being an Altair issue for sure now as I've saved the chart in html and opened it that way where it displays correctly.

I can rule out some of the other issues as I'm running in a fresh docker container so I don't have any jupyterlab extensions or any other previous installs to worry about.

**Comment by joelostblom** [comment]
@braaannigan I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
