### ISSUE TITLE
MaxRowsError better error message

### ISSUE THREAD

**Issue by EntilZha** [altair-viz/altair#2382]
I've been running into this error a decent bit and a nice QoL change would be to include the command to ignore it in the error message. I'd be happy to create a PR if that sounds good.

I'd change the message here https://github.com/altair-viz/altair/blob/d862ad494ecc0a5cff7e8b114df14e0796efa108/altair/utils/data.py#L61 to

```python
MaxRowsError(
            "The number of rows in your dataset is greater "
            "than the maximum allowed ({}). "
            "For information on how to plot larger datasets "
            "in Altair, see the documentation or add 'alt.data_transformers.disable_max_rows()' to your code".format(max_rows)
        )
```

**Comment by jakevdp** [comment]
Thanks for the suggestion: one reason we had not put this particular "solution" in the error message is because we don't want people to disable this message without understanding that doing so may result in crashing Jupyter and putting your notebook in a state where it is no longer able to be opened without crashing Jupyter. I wouldn't want to make it easier for people to shoot themselves in the foot that way...

If you hit `MaxRowsError`, it's important to understand why and choose the right solution for your particular situation. I wish it were easier than that, but it's not.

**Comment by jakevdp** [comment]
We could maybe say something like 
```
To disable this error, set 'alt.data_transformers.disable_max_rows()' BUT BEWARE: doing so may result in crashing your browser session and corrupting your notebook if not done carefully; see https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets for details.
```
I just want to make certain users understand that disabling max rows can have unfortunate consequences.

**Comment by EntilZha** [comment]
That makes sense to me, I just found myself frequently trying to find the right command to run, especially for cases where I have that many rows, but am doing an aggregate (eg bar plot counts). Having the direct link also seems helpful. If the message looks good, I could create a PR or if its easier for you to add it that works too :)

**Comment by jakevdp** [comment]
To be clear, doing an aggregate does not change the size of the JSON blob embedded in the web page, so whether or not your chart aggregates the data has no bearing on the issues of notebook size and potential crashing of Jupyter or your browser.

**Comment by EntilZha** [comment]
I suppose I wasn't aware of that, I thought it was mainly to limit the number of SVG elements, but I could certainly see where that could cause issues.
