### ISSUE TITLE
Sustain plots in Notebook UI after closing

### ISSUE THREAD

**Issue by seyoung-solteq** [altair-viz/altair#2387]
## Environments
- altair==4.1.0
- altair-viewer==0.3.0
- Python 3.6
- jupyter-client==6.1.7
- jupyter-core==4.7.0
- jupyter-server==1.2.0
- jupyterlab==3.0.1
- jupyterlab-server==2.0.0
- ipykernel==5.1.1
- ipython==7.5.0

## Current Behavior
I can plot things on Jupyter Lab. However, they become empty once I close the tab/window. But the notebook size in the disk indicates that the image data still exists (If I comment out the plotting commands and rerun, the notebook size shrinks). In order to view the images, I just have to rerun my notebook. 

According to my browser inspector, the plot is a canvas item,
![Screenshot 2021-01-13 at 17 35 18](https://user-images.githubusercontent.com/60608315/104473498-b6e03f80-55c5-11eb-88b0-f1552bd5b899.jpg)

This is different from how Matplotlib embeds images in base64 format as HTML item. Unfortunately, I don't know how HTML canvas works.

## Hoped Behavior
If Altair/Vega keeps image data into disk within a notebook file, it'd be nice if they could rerender them when I reopen notebooks.
Thank you.

**Comment by jakevdp** [comment]
This is due to JupyterLab's security model: it doesn't execute javascript in cells on opening a notebook, because that javascript has access to the Python runtime and can therefore do just about anything on your system. Altair charts display via javascript, so they don't display when the notebook opens.

If you want them to display on opening, you can make sure the vega labextension is up to date and use the `jupyterlab` renderer, which renders charts via a different mechanism; see https://altair-viz.github.io/user_guide/display_frontends.html for more information.

**Comment by seyoung-solteq** [comment]
Thank you @jakevdp for your quick and informative reply!
According to your suggestion, I added
```python
alt.renderers.enable('mimetype')

!jupyter labextension install @jupyterlab/vega5-extension
```
Now JupyterLab runders the plots on opening. 

BTW is it so that Github.com doesn't render .ipynb files which contains Altair plots?
My notebooks with Altair plots on Github repos always fails to render.
