### ISSUE TITLE
Allow building locally with Firefox/geckodriver when testing

### ISSUE THREAD

**Issue by harabat** [altair-viz/altair#2421]
Might not be the right place for this, sorry, but thought it might be helpful to have it written somewhere. 

When building the documentation locally for testing, an error was raised because I didn't have `chromedriver` and `Chrome` in my path. `webdriver='chrome'` is the default option when saving charts (and can't be overridden when building) and `altair_saver`'s README heavily emphasises Chrome, which makes it look like Chrome is necessary for being able to contribute. 

However, the documentation can be built with Firefox/geckodriver by temporarily changing `webdriver='chrome'` to `webdriver='firefox'` in [altair/utils/save.py](https://github.com/altair-viz/altair/blob/master/altair/utils/save.py)'s `save` method, and then reversing this before committing the changes. 

If there's a better solution for this, or a reason to only build with Chrome, please let me know, otherwise this can be closed.

**Comment by jakevdp** [comment]
Thanks - it looks like the issue is in this block: https://github.com/altair-viz/altair/blob/8a8642b2e7eeee3b914850a8f7aacd53335302d9/altair/sphinxext/altairgallery.py#L142-L146

There are two fixes here: easiest would be to catch the exception you're seeing (instead of ImportError, which I think is out of date) to allow building the docs without saving images. Harder (but not too difficult) would be adding a sphinx configuration option to specify which driver to use.

**Comment by mattijn** [comment]
The current best approach for building the documentation locally is to pip install the recently released `vl-convert-python` package. In that case  the `altair_saver` package is not needed.
