### ISSUE TITLE
Upgrade to Vega-Lite 5

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2425]
How can we prepare Altair and its community to upgrade towards the new [release](https://github.com/vega/vega-lite/releases/tag/v5.0.0) of Vega-Lite 5?

It's probably wishful thinking that @jakevdp has the time available to do this completely by himself, but it's probably also wishful thinking that someone can do this completely without the help of Jake. 

The skills and knowledge required to change the Vega-Lite schema into workable Python code is quite high. While Altair's codebase is flexible by nature to accommodate little changes within Vega-Lite, bigger changes such as `datum` and the recently introduced `params`, require more changes in the codebase.

Maybe someone is just about to finish all the work required for VL5 or maybe we have to become creative`¹`.

I'm sure more people have thoughts on this!

Useful references:
Interesting comments regarding development in the API of Altair can be found in these issues/PRs: https://github.com/altair-viz/altair/issues/2148, https://github.com/altair-viz/altair/issues/1567, https://github.com/altair-viz/altair/pull/1629

And here is the maintenance guide for Altair internals for people that already like to give it a go: https://github.com/altair-viz/altair/blob/master/NOTES_FOR_MAINTAINERS.md

`¹` such as:
- asking Jake for a code-explanation tour in a virtual setting so people with an interest in the project have a guideline to succeed in core-work PRs
- set up an Altair sponsor page to establish a fund for paid upgrading

**Comment by joelostblom** [comment]
Thanks for starting this discussion! I would love to see Altair being updated to work with the new exciting additions to Vega-Lite! I am not sure if I can contribute meaningfully in terms of the needed core changes, but I am more than happy to help out with other tasks that would free up the time for those working on this.

In terms of sponsorship, maybe Altair and/or Vega-Lite would [qualify to become a Numfocus project]( https://numfocus.org/projects-overview)? They support Python and JS projects among others and both Matplotlib and Bokeh receive their sponsorship.

**Comment by jakevdp** [comment]
Thanks! As far as Altair internals go... there's unfortunately not much of a process beyond what's documented in https://github.com/altair-viz/altair/blob/master/NOTES_FOR_MAINTAINERS.md

When it the update script leads to errors, the process is essentially:

- play around until you fix the code generation errors
- run the unit tests to see what backward-incompatible changes are implied by the updated Vega-Lite spec
- do your very best to accommodate those without breaking the existing Python API

Unfortunately, Vega-Lite 4.9 made some pretty significant changes that have resulted in it being quite difficult to build a new Python wrapper... I've set out to try it a few times in the last year or so, and always had to give up before getting close to solving all the issues. Unfortunately, I don't think this is a type of problem that lends itself well to sharing the burden across distributed collaborators. Someone will just have to sit down and figure out what assumptions the Altair API makes that Vega-Lite 4.9 broke.

Trying to build a stable API on an ever-shifting specification is pretty difficult, it turns out :grin:.

**Comment by jakevdp** [comment]
Side-note: all of these difficulties are caused by extra Python bells and whistles on top of the raw specification... so if you're one of the people who has been disappointed over the years by me turning down your API improvement idea, this is exactly why: our API is already far too "improved" to make Altair easily maintainable in the long-run.

**Comment by mattijn** [comment]
Thanks for the response! First of all, nobody is disappointed here! Fan for a lifetime! 

I hope that we can we reduce the first hurdle so more people will try to generate the API. The output generated by the `generate_schema_wrapper.py` is good to follow, but the generator itself is a bit more complicated. Not just to understand, but also to implement changes with confidence. 

With 6-years codebase experience this might feel like playing, but for motivated newcomers it is probably a bit more scary. Python code in comments? Mixins? Directed acyclic graph? Shorthands?

When introducing changes, in which parts should one be careful, not too-careful, or can one even be careless?

Over the years numerous shorthands have been introduced within the generator, which seems to bite us here, since they do not completely align anymore with an evolving VL specification. 
How important are which shorthands? Can one make a first step without these? Can they still be introduced outside the generator proces? Might maintainability improves by reducing complexity with the cost of increasing _tediosity_?

**Comment by jakevdp** [comment]
shorthands are things like
```python
chart.encode('sum(x):Q')
```
which is expanded to
```python
chart.encode(field='x', type='quantitative', aggregate-'sum')
```

**Comment by mattijn** [comment]
I love the shorthands, but I'm not against releasing an alpha release without these bells and whistles in order to get a better feeling what the new functionalities of VL mean for Altair. 

All current viszs can still be made and more, albeit a bit more verbose. Users with existing specifications including shorthands have to wait a bit more.

By that time @joelostblom is up and running and has discovered some new routes to bring back the shorthands:)

**Comment by jakevdp** [comment]
@mattijn interesting idea, but note that would break most tests that Altair uses to validate new releases. You could work around that by rewriting all the tests (which would be a lot of work that would later have to be undone) or disabling all the tests (which would leave us unable to validate whether the simplified wrappers even work).

All told, I think time would be better spent supporting the full API at the start.

**Comment by domoritz** [comment]
Thank you all for kicking off this conversation. I would like to offer full support from the Vega-Lite team to answer any questions you will run into.

**Comment by ramayer-fli** [comment]
Why not target full-Vega instead of Vega-Lite?   Seems to me Vega-Lite is short-and-easy enough to just use in a IPython.display.IFrame(...) directly; and a bigger benefit of a pythonic API would be to allow more complex full-vega json to be created more elegantly.

**Comment by mattijn** [comment]
Naming is hard, consider Vega-Lite as Vega-Compact and it make more sense to stick to Vega-Lite instead of Vega(-Verbose).

**Comment by domoritz** [comment]
Vega-Lite (yes, not a great name we admit) has gotten substantially more flexible and now supports a lot what previously only worked in Vega. Vega still needs an order of magnitude or two more spec for the same chart.

**Comment by jakevdp** [comment]
altair does have wrappers for full vega specs: `from altair import vega`. Nothing high-level, but all the low-level definitions are there for you to use if you wish.

**Comment by jbloom** [comment]
I was just curious about this upgrade and the general future of `altair`, as I've noticed commits and code updates have slowed a lot over last year or so. I certainly don't have ability to maintain package myself, but do think it's an awesome package. However, I'm trying to decide whether to use it for some long-term projects I'm starting, and hence am sort of curious whether it's likely `altair` continues to undergo a lot of active development and growth, or if it's sort of in maintenance mode now?

**Comment by firasm** [comment]
> I don't think it's that hard, it will just take some time and some experimentation. I estimate I could probably upgrade Altair to VL4.9 with maybe a ~week of engineering work.

I'd love to sponsor this work with money (since I have 0 capacity to take it on myself)!

I'm not sure how much a week of engineering costs, but if there are others willing, I'm sure we could put our wallets together for this. 

Let me know if this is something we should explore as a model to continue supporting this amazing library.

**Comment by PaleNeutron** [comment]
Hey, more than one year since this issue opened and I have see GitHub actions testing vega-light version 5.2.

Is there any plan to upgrade altair to 5.x?

**Comment by mattijn** [comment]
Thanks for checking in. As realized early on, the change from VL4 tot VL5 is significant. 

Over the last year there has been quite extensive progress. 

This means that the development version of altair repo on GitHub is already on VL5. 

Basic charts do work fine, but there are still some discussions around parameter usage in compound charts, see https://github.com/vega/vega-lite/issues/8230.

**Comment by joelostblom** [comment]
There is now a release candidate of Altair 5, which supports Vega-Lite 5! Details and info on how to install can be found  in https://github.com/altair-viz/altair/issues/2937
