### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by thewchan** [altair-viz/altair#2493]
I know there's a lot of trouble with updating Altair to VL5 especially because of the workload involved, but at the mean time I was wondering if I can help with contributing in more minor ways. I use Altair at work and we do try to enforce pretty strict type safety. Right now much of Altair's API isn't type-annotated. Is this something folks think I can work with without breaking anything? If so I can try to add type hints and make a PR?

**Comment by jakevdp** [comment]
Thanks - we'd definitely be open to that!

Unfortunately I think there are some stale dependencies in the CI, though, so we may need to address that before doing any significant changes.

**Comment by thewchan** [comment]
Thanks for the reply; if that's anything I can help with (although i doubt it?) please let me know.

**Comment by thewchan** [comment]
Any updates on this regarding broken dependencies?

**Comment by joelostblom** [comment]
Thanks for offering to help @thewchan ! The major changes to the API for the next version of Altair have already been merged to master, so I believe it would be relatively safe to branch from that and start adding type annotations ([note that some files are autogenerated](https://github.com/altair-viz/altair/blob/master/NOTES_FOR_MAINTAINERS.md)). @jakevdp has the last say on this though and I am not sure which the stale CI dependencies are that he was referring to above (I believe CI is working fine for the more recent PRs so this might have been fixed since his original comment was made).

**Comment by thewchan** [comment]
Great! I'll start on it. Shall I ping you @joelostblom for questions/comments?

**Comment by joelostblom** [comment]
Feel free to post here if you have questions or put up a draft PR if there are specifics you are wondering about or want to have reviewed. I don't have much ecperience with type hints myself but will try to be helpful where I can.

**Comment by binste** [comment]
Type hint efforts are now tracked in #2951
