### ISSUE TITLE
Include documentation for each mark type

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2578]
The docs for marks are currently still missing in the Altair documentation. It would be nice to have a similar structure as the [Data Transformations](https://joelostblom.github.io/altair-docs/user_guide/transform/index.html#) for Marks.

Raised before in https://github.com/altair-viz/altair/pull/2566#issuecomment-1079289236

**Comment by hebarton5** [comment]
Moving conversation from #2580 here! I would be willing to contribute to documentation on each mark, especially now that you have provided and example with mark_geoshape(). Since each mark already has a tagged example associated with it, what additional information/examples should be included in the documentation?

**Comment by joelostblom** [comment]
Hello @hebarton5 ! Thank you so much for your interest in contributing to Altair. I think it would be really nice to follow the design of the [`Mark` page in Vega-Lite](https://vega.github.io/vega-lite/docs/mark.html) when building it for Altair. I also like the reorganization that @mattijn started in https://github.com/joelostblom/altair/pull/1 ([preview](https://deploy-preview-1--spontaneous-sorbet-49ed10.netlify.app/user_guide/marks/index.html)) so we can draw inspiration from there as well. Here is what I would suggest (1 and 2 are the most important, and I'm open to feedback):

1. I think the landing page should include a short intro to what marks are (similar to what is there now already), the table of all available marks (same format as in @mattijn PR), and then a heading "Mark Properties" which contains the [current mark properties table](https://joelostblom.github.io/altair-docs/user_guide/marks.html#mark-properties), but [divided into subheadings as can be seen on the VegaLite page](https://vega.github.io/vega-lite/docs/mark.html#mark-def) (general, position and offset, color, stroke style, and finally hyperlink properties) (i don't think the last "style" section is as important).
2. I like the format of individual mark pages being subpages under the "Mark" headings (as in @mattijn 's PR) rather than links to the gallery. Let's include a few examples for each mark directly on the page, ideally translating the ones showed at the Vega-Lite pages to Altair code (+ mentioning any differences in Altair where appropriate, I can help with that part). Some of these are relative brief, e.g. the [arc examples](https://vega.github.io/vega-lite/docs/arc.html#examples) whereas others are really long, e.g. the [boxplot example](https://vega.github.io/vega-lite/docs/boxplot.html#boxplot-types). Feel free to shorten the really long pages (e.g. we don't need to talk about "The Parts of Box Plots") and only include a few examples to start with (we can always add more later). 
3. I find it really helpful that VegaLite includes [a table on each mark subpage](https://vega.github.io/vega-lite/docs/arc.html#properties) of all the properties specific to each mark. It would be great if we could have this in Altair too (currently we only have [one big table](https://deploy-preview-1--spontaneous-sorbet-49ed10.netlify.app/user_guide/generated/core/altair.markdef) for all marks that is hard to navigate).
    - The challenge here will be to pull this information automatically because we don't want to update it manually each time there is a Vega-Lite update (this would probably also lead to errors). You could explore pulling this info either from the VegaLite repo directly as part of the docs make file, or (preferably) if we could somehow populate this table via sphinx inspecting that arguments taken by each `alt.Chart().mark_*`.
    - Another alternative is to manually filter the properties from `MarkDef` to only include the relevant ones; this way all the descriptions will still be automatic so that could work as well and is [similar to how they do it in VegaLite.](https://github.com/vega/vega-lite/blob/next/site/docs/mark/arc.md#arc-mark-properties) (explained a bit[ in the contrib guidelines](https://github.com/vega/vega-lite/blob/e85f24c65651c5c3b9f3f8f8aa1831b77aad2dcb/CONTRIBUTING.md#property-table))
5. You will also notice that [the individual mark subpages in the VegaLite documentation](https://vega.github.io/vega-lite/docs/arc.html#properties) has a really helpful section with sliders where you can interact with and see how it impacts the chart visuals. I am not sure we will be able to add something like this, but one approach could be to pull the Vega-Lite specs from those URLs and display them in the Altair docs as well (either via Altair's VegaLite primitives or directly in the HTML).

Ok that was a lot of text, as I mentioned, I think 1 and 2 are the most important items here. Does it feel doable to get started with those? Feel free to ask any questions you have here in this issue!
