### ISSUE TITLE
Naming of `parameter` and `add_parameter`

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2598]
It's not directly a problem that blindside me at 4pm on some idle Tuesday, but I prefer `alt.param()` over `alt.parameter()` and `alt.Chart().add_params()` over `alt.Chart().add_parameter()`...

**Comment by ChristopherDavisUCI** [comment]
I'm happy to change that if others agree, but doesn't `add_param` match `add_selection` better than `add_params`? 

Naming in Python has always been mysterious to me, so I don't claim to have any good intuition (like `isna` vs `isnan` vs `isnull` ...).

**Comment by joelostblom** [comment]
I also don't think this is a big issue, but I'm in favor for the shorter form since it is both consistent with what parameters are called in VegaLite specs and a bit easier to type. Notably `selection` is different in Altair versus VegaLite (`select`), but I don't think that should stop using the most appropriate term for new additions.

**Comment by mattijn** [comment]
Another strong argument: on my qwerty keyboard, the `e`, `r` and `t` are next to each other, so when typing `parameter` the `param` part comes automatically, but I always have to think how to type the `eter` part🙈

**Comment by ChristopherDavisUCI** [comment]
It's a compelling argument @mattijn!  I'll plan to make this change next time I'm making updates.

**Comment by joelostblom** [comment]
Closed in #2656
