### ISSUE TITLE
How to filter data based on date?

### ISSUE THREAD

**Issue by fredthedead** [altair-viz/altair#263]
This doesn't seem to work:
```
from altair import *

Chart(Data(
    formatType='csv',
    url='http://vega.github.io/vega-lite/data/stocks.csv',
),
    description='Stock prices of 5 Tech Companies Over Time.',
).mark_line().encode(
    color='symbol:N',
    x='date:T',
    y='price:Q',
).transform_data(filter='datum.date < "2008-01-01"')
```

By the way the example on this page https://altair-viz.github.io/gallery/line_color.html is broken since 'format' is no longer a valid argument to 'Data'

**Comment by jakevdp** [comment]
Hi,
We recently updated altair and the Vega-Lite dependency, and it sounds like you have an old version. Can you try updating your altair installation, including the jupyter extension? If you do that the example you pointed to should work.

**Comment by ellisonbg** [comment]
@fredthedead did you get a chance to try @jakevdp 's suggestion?

**Comment by ellisonbg** [comment]
Closing for now as questions. Let us know if you need more help!

**Comment by firasm** [comment]
I am also trying to filter data based on a date, but rather than filter greater than or less than, I want to pick out exactly one year. 

The example [from the docs](https://altair-viz.github.io/user_guide/transform/filter.html#filter-expression) does not parse the dates like datetime objects as recommended, but instead treats them as integers. If done that way `.transform_filter(datum.year == 2000)` works.

However, how do you pick out the year 2000 when the dataframe column is in the datetime format?

Here is some code that I expected to work:

```
import altair as alt

from vega_datasets import data
pop = pd.read_json(data.population.url)
pop['year'] = pd.to_datetime(pop['year'],format='%Y')

alt.Chart(pop).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    alt.datum.year == '2000'
)
```

Though, seeing issue #2209 about python and javascript's interpretation of `==` and `===, I can understand why it doesn't work.

When I tried:

```
.transform_filter(
    alt.datum.year == pd.to_datetime('2000',format='%Y')
)
```

I got this error:

```
Javascript Error: Unrecognized function: Timestamp
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```

<img width="719" alt="Screen Shot 2021-01-16 at 11 46 43 AM" src="https://user-images.githubusercontent.com/2507459/104821407-83cdc400-57f0-11eb-8278-0f8415c4e402.png">

(Of course, a pure pandas approach works as well):

```
alt.Chart(pop[pop['year']=='2000']).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(alt.datum.sex == 1
)
```

P.S. Sorry to revive an old issue but I really didn't feel right opening a new one with the exact same title.

**Comment by jakevdp** [comment]
You can't use pandas timestamps in Filter expressions

**Comment by firasm** [comment]
There is one there, but the post is long. The screenshot was for the error. 

Here it is:

```
import altair as alt

from vega_datasets import data
pop = pd.read_json(data.population.url)
pop['year'] = pd.to_datetime(pop['year'],format='%Y')

alt.Chart(pop).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    alt.datum.year == '2000'
)
```

**Comment by jakevdp** [comment]
As you've written it, none of the rows pass the filter because none of the timestamps are equal to the string `'2000'`. If you want to extract the year in a vega-lite filter expression, you can use [vega expressions](https://vega.github.io/vega/docs/expressions/) to do so. For example:
```python
alt.Chart(pop).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    'year(datum.year) == 2000'
)
```

**Comment by firasm** [comment]
thanks!! Vega expressions look very useful.
