### ISSUE TITLE
PNG blurry when compared to HTML and SVG

### ISSUE THREAD

**Issue by mcp292** [altair-viz/altair#2664]
HTML:
![image](https://user-images.githubusercontent.com/49123398/182426329-4fb5b7fa-bb23-4f00-8274-d21292481272.png)

PNG:
![image](https://user-images.githubusercontent.com/49123398/182426420-a2bc28d0-5700-4dc7-90df-9099d3c72b08.png)

SVG:  
Slightly clearer than HTML; I'm not able to easily upload or copy into post.

Using geckodriver and selenium 4.2.0, calling `save("chart.png", webdriver="firefox"). Confirmed with chromedriver as well.

**Comment by jakevdp** [comment]
Since PNG is a raster format, it has a finite resolution. On the other hand, HTML and SVG are based on vector graphics and have effectively infinite resolution (to be more precise, their display pixelization will match the native resolution of your screen at every zoom level). So it is expected that PNG will have poorer resolution than HTML or SVG: it's baked into the image encoding.

There is some information on adjusting the PNG output resolution here: https://altair-viz.github.io/user_guide/saving_charts.html#figure-size-resolution

Does that answer your question?

**Comment by mcp292** [comment]
Yes it does! 

Apologies, this should have been posted in the [altair_saver](https://github.com/altair-viz/altair_saver) repo.
