### ISSUE TITLE
docstrings for new introduced methods regarding params and selection_*

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2692]
Currently the docstrings for some new introduced parameter methods are rather limited:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/5186265/195705014-5aaa1553-c5b9-4d57-936c-287157440860.png">

Where in the above example I've defined it as such:
```python
highlight = alt.selection_point(
    name="hover",
    on="mouseover",
    nearest=True,
    encodings=["x"],
    empty=False,
    clear="mouseout",
)
```
How can one know about this without docstrings?

**Comment by ChristopherDavisUCI** [comment]
Is it possible some of these issues have been incidentally fixed along the way?  For example, I seem to have docstrings showing up okay.

<img width="365" alt="Screenshot 2023-02-15 at 11 17 57 AM" src="https://user-images.githubusercontent.com/82750240/219130605-0c6dbf3e-d7fb-4d48-922f-b3e015d93251.png">

shift+tab also seems to reveal a docstring (I can't get a screenshot at the moment).

A different issue is that these are the docstrings for the lower-level objects, such as `core.IntervalSelectionConfig`, so for example, `name` is not mentioned, even though `name` is an expected keyword argument for our higher-level Altair function.

Before looking into this further, I wanted to check @mattijn to what extent the issue you reported in October has been resolved.  Thanks!

**Comment by ChristopherDavisUCI** [comment]
@joelostblom I agree it could make sense to hide `alt.section`, so that `alt.selection_point` and `alt.selection_interval` are encouraged.  Do you remember how to do that?

**Comment by mattijn** [comment]
You are right! This is fixed along the way. Great.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/5186265/219148704-1650f5f6-822e-43fd-a3ce-bc1fb039c1a1.png">

If you want to hide the `alt.selection` from the autocomplete, you'll have to assign `alt.selection` a deprecated status around here https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/api.py#L372 by adding:
```python
@utils.deprecation.deprecated(
    message="'selection' is deprecated.  Use xxx"
)
def selection(type=Undefined, **kwds):
```

**Comment by mattijn** [comment]
Hm, not sure. This is the current docstring for `alt.param`, https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/api.py#L303-L320.
```python
def param(name=None, select=None, **kwds):
    """Create a named parameter.
    Parameters
    ----------
    name : string (optional)
        The name of the parameter. If not specified, a unique name will be
        created.
    **kwds :
        additional keywords will be used to construct a parameter.  If 'select'
        is among the keywords, then a SelectionParameter will be created.
        Otherwise, a VariableParameter will be created.
    Returns
    -------
    parameter: Parameter
        The parameter object that can be used in chart creation.
    """
```
I would say that is too limited to consider this issue complete.

**Comment by ChristopherDavisUCI** [comment]
Glad the docstrings also working on your end @mattijn!  The displayed signature isn't perfect, because on the Altair side we allow a parameter and its selection configuration to be defined simultaneously, but the above docstring only mentions the selection portion.  For example, I believe all of these are missing from `selection_interval`: `{"name", "value", "bind", "empty", "init", "views"}`.

I agree that we should keep this issue open for now.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, I will try to improve the parameter docstrings.  Is there anything wrong with just typing it out by hand in VS Code, including for example the valid keyword arguments?  I just want to make sure that's reasonable before getting started.

Getting the valid arguments automatically from Vega-Lite is harder than usual for parameters, because on the Vega-Lite side, there is a parameter definition like this
```
{
  "name": "brush",
  "select": {"type": "interval", "encodings": ["x"]}
}
```
but on the Altair side, those values of `"name"` and `"encodings"` would typically be passed to the same function (like `alt.selection_interval`).

**Comment by mattijn** [comment]
By _hand_ is fine.

**Comment by ChristopherDavisUCI** [comment]
Is there a rule of thumb for when `Undefined` should be used as a default value, and when `None` should be used as a default value?  I'm increasing the number of keyword arguments to `alt.param` (for example, `bind` and `value`), etc, but am finding myself just guessing whether to use `None` or `Undefined` as the default values.

**Comment by mattijn** [comment]
In the context of Altair, `None`, serializes to `null` in JavaScript, sometimes that is desired. Again in the context of Altair, you probably want `Undefined` most of the time.

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn, please see if #2908 addresses this issue.
