### ISSUE TITLE
Move the geospatial section in the "Specifying data" page to the geoshape mark page

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2740]
I think we should move everything from the heading "[Graticule generator"](https://binste.github.io/altair-docs/user_guide/data.html#graticule-generator) and down to the geoshape mark page. Although (some of) this section is technically about specifying data, I think it is more intuitive for readers to find all the info about how to work with geographical data in one place in the Altair documentation. The rest of the "Specifying data" page is relevant for almost all readers as they lay a foundation for how to use data with most marks in altair, but the geoparts are specific to just the geoshape and feels a bit out of place to me (and at the same time harder to find for readers who want to work with only geo data).

Possibly we could have a heading "Working with geographical data" which just links to the geoshape mark page so that we improve the discoverability of this page (which I think would be helpful since it is a little bit hidden under the "marks" section, I'm even considering a separate side bar item for geoviz like the Time side bar item we have now.).

@mattijn @binste Thoughts on this?

**Comment by mattijn** [comment]
I think we should keep the mark geoshape page about the mark geoshape options. 

But I also agree it would be good to have a section on defining spatial data. I really like the current structure of nested options below _Marks_ and _Transformations_ (although I wished they are not collapsed by default). 
Maybe we can set up something similar for the _Specifying Data_ section? 

I mentioned this before in this [issue](https://github.com/altair-viz/altair/issues/1994) from a while ago:

> By the way, in the docs of Vega-Lite there are no options under Data / Datasets:  
> <img alt="image" width="151" src="https://user-images.githubusercontent.com/5186265/75585244-e5b6fb00-5a71-11ea-9bcc-199f15df6433.png"> 
> I think there should be some sub-options, especially for Altair.

There we can then have a section named _Spatial Data_ and place these GeoPandas and Graticule/Sphere generator sections and info from [this](https://stackoverflow.com/a/55950538/2459096) SO-answer and also some info how to use the `:G` encoding, with a simplified of https://github.com/altair-viz/altair/discussions/2727#discussioncomment-4257715.

But in this _Specifying Data_ section I wish there also is a section how to use eg. `dict` with Altair. Pandas is great, but Dicts? Mindblowing;)!

Btw, I prefer the name Spatial Data over Geographical data, since there are many things spatially related but not necessarily geographical:
```python
import altair as alt

data = [
    {"color": "#F3C14F", "geo": {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[1.45, 3.75], [1.45, 0], [0, 0], [1.45, 3.75]]]}}},
    {"color": "#4098D7", "geo": {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[1.45, 0], [1.45, 3.75], [2.57, 3.75], [2.57, 0], [2.33, 0], [1.45, 0]]]}}},
    {"color": "#66B4E2", "geo": {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[2.33, 0], [2.33, 2.5], [3.47, 2.5], [3.47, 0], [3.2, 0], [2.57, 0], [2.33, 0]]]}}},
    {"color": "#A9CDE0", "geo": {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[3.2, 0], [3.2, 1.25], [4.32, 1.25], [4.32, 0], [3.47, 0], [3.2, 0]]]}}},
]
source = alt.Data(values=data)

alt.Chart(source, title="Vega-Altair").mark_geoshape().encode(
    shape="geo:G", 
    color=alt.Color("color:N", scale=None)
).project(type="identity", reflectY=True)
```
<img width="359" alt="image" src="https://user-images.githubusercontent.com/5186265/205165799-7ee27025-c4bf-4926-92be-2819aaf2a1aa.png">
