### ISSUE TITLE
Error persists when trying to concat facetted charts although it is fixed in VegaLite

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2742]
When I try to concatenate facetted charts with the latest Altair version from master, I am still seeing `Javascript Error: Undefined data set name: "scale_concat_1_child_main"` although this was fixed in https://github.com/vega/vega-lite/pull/7639. Exporting the spec to json and pasting it in the Vega editor also seems to work fine although the VegaLite version is 5.2.0 in both cases [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3o0ABZPAF9ojRCkTBRUUGUkBDg0EASk-gAObQBGGTE4KAi8kKgxNyZtGQSSvJkATjcIwoi4PLaZEDjsxKQIOEwIcxyBAuLS8srq2vrGsWa2jq6ejzQAbVAIBgoAJzRJDSSITEzUFq8QTABPHCuLAGtMuL2DpGPUMTPhy5oADsfzuj2eWje-TUnyOaEK-wuVxaoIeTyykPeMJA+zhqFOdwBVzyqPBWSeeBo0Nh3zQqKJaGaZzJ6ApECpHxxXx+CMJSOBpPRrLglP6AF0BsQfFBEjtQNokFBRuZdHBBCEsmjMsyhSBlGwENYkIJoTinlBzHBlFoQtZ9CkQAAPFXGdVZXG0nXPACODCQvjoiRopFN9xdao16HOgK9WV9-qsSSsIdiGmQhxe5LY1kw-U5CqVuYdqrdUbJsfQ+sNaRNAwg5st1rYtuU9tAzuLrsjXLhFZA8YDSeDWJAYc7Ec1DL7A8TQZTA3TmdZ2d8eYlQA)

@ChristopherDavisUCI Are you seeing this as well?

Example spec:

```py
import altair as alt
import pandas as pd


df = pd.DataFrame({
    'type': ['coke', 'coke', 'coke', 'pepsi', 'pepsi', 'pepsi'],
    'taste':[90,75,95,85,80,75],
    'sugar':[2,5,1,2,5,1],
})

plot_a = alt.Chart(df).mark_point().encode(
    x = 'sugar',
    y = 'taste',
).facet('type')

plot_a & plot_a
```

**Comment by ChristopherDavisUCI** [comment]
Hi @joelostblom, Yes, I can confirm that I get the same JavaScript error (and that the produced json does work in the Vega editor.  (Also, the `to_json` method works for this chart even with the default value of `to_json(validate=True)`.)  I haven't seen this discrepancy before between the validation and what renders in Jupyter lab, so no idea at the moment.

**Comment by mattijn** [comment]
https://github.com/vega/vega-lite/pull/7639 was "officially" [released](https://github.com/vega/vega-lite/releases/tag/v5.4.0) in VL5.4 (but [first](https://github.com/vega/vega-lite/pull/8239) appeared in VL5.3-next-4). 

Altair schema validation & rendering still uses VL5.2 (since altair_viewer is still on VL5.2). But since the schema validation with VL5.2 works win Altair it can be rendered succefully with vl-convert using VL5.3:
```python
import altair as alt
import pandas as pd
import vl_convert as vlc
from IPython import display

df = pd.DataFrame({
    'type': ['coke', 'coke', 'coke', 'pepsi', 'pepsi', 'pepsi'],
    'taste':[90,75,95,85,80,75],
    'sugar':[2,5,1,2,5,1],
})

plot_a = alt.Chart(df).mark_point().encode(
    x = 'sugar',
    y = 'taste',
).facet('type')

vl_spec = (plot_a & plot_a).to_json()

png = vlc.vegalite_to_png(vl_spec, vl_version='v5.3')
display.display(display.Image(data=png))
```
<img width="457" alt="image" src="https://user-images.githubusercontent.com/5186265/205260798-1f42e85a-2b60-4e6b-b9d6-cf62fafc070d.png">

Proof that rendering with VL version `'v5.2'` result in the same error as within Altair:
```python
png = vlc.vegalite_to_png(vl_spec, vl_version='v5.2')
```
```cmd
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [65], in <cell line: 1>()
----> 1 png = vlc.vegalite_to_png(vl_spec, vl_version='v5.2')

ValueError: Vega to SVG conversion failed:
Error: Undefined data set name: "scale_concat_1_child_main"
```

Question is, why it works in the Vega-Editor. It seems that the Vega-Editor validates uses VL5.2 but renders with a higher version? Not the latest either, since features from VL5.6 [won't render](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAbJQBWENgDsQAGhAATONABONHJnZL0AQQAE0JNjhacgtpjMw2AdxoKyJpmzUBPE8ggQJkgKaiYAZsI4OFYmgnBu9IFsYSbRbgyuEJQq6hYoqKAMWoJouZhIBGlkGQpZcoogAL6qyFoA1qU4bK6YOfFQXq5kaKAAHiMgYTRwgmqlAGKR0VomADLxZPQmABQICACUOZje0aUAjgzB+uX6pE2q3hNTM3PoAEJevgCySAE7ZIdVMdTugLlc6BYaHdmiABrYtE9prNSgBlaJQaYQI4nOClBRsBCuJAlGEQGBIEGgZ7I9BouAYzTYkEgfGEhTEpowgYKKbDAogcxxCYALysbDQYWJEDgjVlQA).

I cannot understand anymore what did release at which moment with all these autogenerated next-releases at the VL-repo. Good you opened this: https://github.com/vega/vega-lite/issues/8522.

**Comment by joelostblom** [comment]
Thank you for that thorough investigation! The fact that the vega editor is labeled as version 5.2 but allows for some functionality from later releases to work is indeed confusing. Maybe I'll open an issue there about that too.

**Comment by joelostblom** [comment]
Here is the response I got in https://github.com/vega/vega-lite/issues/8581

> The version shown by the editor is the version of Vega loaded. Right now, the editor does not load a different version when the spec specifies a different version.

**Comment by joelostblom** [comment]
I ran into this today and confirming that with the upgrade to VL 5.6 in https://github.com/altair-viz/altair/pull/2871 this indeed works now.
