### ISSUE TITLE
Consider switching the default renderer to one that supports offline renderering

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2797]
Maybe when Jupyter Notebook's release v7 is out, which is based on jupyterlab, it makes sense to switch the default renderer to one that support offline rendering? This is not the highest priority right now, but I thought I would record the idea. Maybe we could also trim down the amount of available renderers to simplify the selection a bit (at least `html` and `default` are the same, maybe also `jupyterlab` and `mimetype`?). Based on the discussion here https://github.com/vegafusion/vegafusion/discussions/204#discussioncomment-4580932

**Comment by jonmmease** [comment]
I'll also note that when I was testing renderers for VegaFusion, it looks like the default "html" renderer now works fine in Colab and Kaggle, so we may not need to specialized versions anymore.

**Comment by joelostblom** [comment]
Another related topic is to bring the vega and vega-lite javascript for offline rendering into altair instead of having it in altair_viewer as discussed in https://github.com/altair-viz/altair/pull/2807 and https://github.com/altair-viz/altair/issues/2765.

**Comment by ChristopherDavisUCI** [comment]
Are there any subtleties I might be missing related to using `alt.renderers.enable("mimetype")`?  I believe I'm on the master branch of Altair and am using JupyterLab 3.5.2.  If I try for example the following:
```
import altair as alt
alt.renderers.enable("mimetype")
alt.Chart().mark_point()
```
I get the following message
```
<VegaLite 5 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```
I have tried running the following command from the terminal:
```
jupyter labextension install @jupyterlab/vega5-extension
```

**Comment by jakevdp** [comment]
Some history here: originally, `mimetype`/`jupyterlab` was not only the default renderer, it was the *only* renderer. This proved problematic for several reasons:

- not all notebook platforms supporte mimetype-based rendering, which meant users had to enable non-default renderers in classic notebook, kaggle, streamlit, etc.
- mimetype rendering requires your lab extension to match the Altair version, otherwise your chart just says `<VegaLite 5 object>` as @ChristopherDavisUCI found. By design, the lab extension is not controlled by the python runtime, but rather by the jupyter server. This makes it frustrating and difficult to debug when things go wrong. Every time we upgraded vega-lite, we dealt with several months of users who found that their charts no longer displayed because they didn't know how to update jupyterlab extensions.

Eventually, we managed to create an HTML renderer that basically worked everywhere (not a small feat given how vega-lite is packaged with respect to its interaction with requirejs), with the main downside being that it requires web access. Switching to that greatly reduced the number of user questions about rendering charts on various notebook platforms.

Offline rendering is great when it works, but I think going back would be a mistake.

**Comment by joelostblom** [comment]
Thanks for that historical context @jakevdp. I will close this issue then.

It seems like it could still be beneficial to remove some of the redundant renderer aliases, so I opened https://github.com/altair-viz/altair/issues/2821 for that
