### ISSUE TITLE
autosize="none" does not work on concatenations

### ISSUE THREAD

**Issue by salcc** [altair-viz/altair#2803]
The following minimal working example shows the problem:

```python
import altair as alt
from vega_datasets import data


source = data.wheat()

a = alt.Chart(source).mark_line().encode(
    x="year:O",
    y='wheat:Q'
).transform_filter(
    alt.datum.year >= 1700
).properties(
    width=400,
    height=200
)

b = alt.Chart(source).mark_line().encode(
    x="year:O",
    y='wheat:Q'
).transform_filter(
    alt.datum.year >= 1700
).properties(
    width=400,
    height=200
)

(a | b).properties(autosize="none")
```

The resulting chart, although having specified the width and height of both charts composing it, is the following:

![visualization](https://user-images.githubusercontent.com/52110876/210536340-7878ab0f-d790-4358-a6eb-19eea61e311e.png)

Which of course is not what I expected.

**Comment by salcc** [comment]
Seems to be related to https://github.com/vega/vega-lite/issues/7560. Is there any way to work around this if I need to specify autosize="none" for just the first chart I concatenate?

**Comment by joelostblom** [comment]
Unfortunately, I don't think there is anything we can do on the Altair side of things here. When the bug you linked is fixed in Vega-Lite, it will be in the next version of Altair as well. I couldn't find a workaround for this myself, but please share if you found a way to deal with this. Closing the issue, since there is no action to take for Altair.
