### ISSUE TITLE
save using vl-convert doesn't work with json data_transformer

### ISSUE THREAD

**Issue by sid-kap** [altair-viz/altair#2953]
In altair 5.0.0rc1, vl-convert produces images without any data points when the json transformer is enabled.

Example code:
```python
import altair as alt
from vega_datasets import data

alt.data_transformers.enable('json')

chart = alt.Chart(
    data.iris()
).mark_point().encode(
    x='sepalWidth', y='sepalLength'
)
chart.save('test.png', engine='vl-convert', scale_factor=2)
```
In my jupyter notebook, I see
![visualization (8)](https://user-images.githubusercontent.com/6425077/223539893-2d18e1ad-c163-4310-8f4d-c760b5bd9281.png)

but the created `test.png` looks like:
![test](https://user-images.githubusercontent.com/6425077/223539980-90bc2e59-26d8-4b01-81d6-6449d170a788.png)

**Comment by binste** [comment]
Thank you @sid-kap for reporting this bug! I can reproduce it.

@jonmmease would you mind having a look? I noticed that the fix in #2724 for the data-server package might not actually work as at that point the Altair chart got already converted to a dictionary here https://github.com/altair-viz/altair/blob/master/altair/utils/save.py#L124. So we might want to move the temporary disabling of any data transformer (introduced in #2724) to that line anyway when `.to_dict` is called so that all data is inlined. But as this issue is about json files, I'm wondering if vl-convert does not work with data from URLs in any case and if this is the expected behavior?

**Comment by jonmmease** [comment]
Thanks for the ping @binste. My first thought is that this issue is that the URLs reference JSON files on the local file system. vl-convert supports data URLs that reference remote JSON files, but I believe the issue is that it doesn't currently support urls to local files.

In any case, I think your suggestion to move the disabling of data transformers makes sense.

**Comment by binste** [comment]
Thanks for the quick turnaround! I'll create a PR to fix this.

**Comment by sid-kap** [comment]
Hmm, it sounds like this fix would not work for datasets with more than 5000 rows?

**Comment by binste** [comment]
Good point that large data needs to be considered. However, it still works also for more than 5000 rows as during saving we temporarily turn off the `MaxRowsError` as well to prevent exactly this. The following chart with 15'000 rows saves as a png in 8 seconds:
```python
import altair as alt
import pandas as pd
from vega_datasets import data

alt.data_transformers.enable('json')

# Has 150 rows
df = data.iris()
# Has 15'000 rows
df_big = pd.concat([df] * 100)

chart = alt.Chart(df_big).mark_point().encode(
    x='sepalWidth', y='sepalLength'
)
chart.save('test.png', engine='vl-convert', scale_factor=2)
```

The error if a dataset is bigger than 5'000 rows is more relevant if the chart is to be displayed in a frontend, see [Large Datasets](https://binste.github.io/altair-docs/user_guide/large_datasets.html) for the new section in the documentation on this.
