### ISSUE TITLE
Wheat and Wages case study appears to be broken

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#2966]
https://altair-viz.github.io/gallery/wheat_wages.html

<img width="944" alt="Screen Shot 2023-03-15 at 6 59 21 AM" src="https://user-images.githubusercontent.com/9993/225331695-24df6924-2fcd-4848-a85c-f895b2711d22.png">

**Comment by joelostblom** [comment]
The x-axis could be fixed by setting `alt.Scale(zero=False)`, but it seems like there are more differences with this and the corresponding Vega-Lite example (e.g. setting the x-binning to "binned"), so it might be better to rework it more based off on https://vega.github.io/vega-lite/examples/wheat_wages.html
