### ISSUE TITLE
Dynamic title , concatenation of string and selected value in dropdown selectbox

### ISSUE THREAD

**Issue by TONODEKEN** [altair-viz/altair#3032]
I am looking for a working solution of a dynamic head title based on a concatenation of a fiexed string and a selected value in dropdown selectbox used for filtering.
All the solutions I have got from AI-tools give errors.

The title should change each time you make an other selection

Thanks a lot for an answer

**Comment by mattijn** [comment]
Here is a working solution using, still, a bit of human intelligence.
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

input_dropdown = alt.binding_select(
    options=['Europe','Japan','USA'], 
    name='Region '
)

selection = alt.selection_point(
    fields=['Origin'], 
    bind=input_dropdown, 
    value=[{'Origin': 'Europe'}]
)

title=alt.Title(
    alt.expr(f'"You have selected: " + {selection.name}["Origin"]')
)

color = alt.condition(
    selection,
    alt.Color('Origin:N').legend(None),
    alt.value('lightgray')
)

alt.Chart(cars, title=title).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
).add_params(
    selection
)
```
![RRx4D9twYi](https://user-images.githubusercontent.com/5186265/234023418-5c7974ac-b1bf-4a9a-88a4-dd6f161b87d6.gif)

It is based on the new release candidate of altair version 5. For more info read the expression section within the interactive page within the documentation: https://altair-viz.github.io/user_guide/interactions.html#expressions.

I think this answer resolves this issue is answered so we can close this issue. I you think otherwise, please re-open.

**Comment by joelostblom** [comment]
We don't have a date for the release of v5 but the second release candidate should be released soon and you can install it via pip as per the command in the banner on the website.
