### ISSUE TITLE
pyarrow datetime is not supported using altair 5.0

### ISSUE THREAD

**Issue by djouallah** [altair-viz/altair#3050]
I created an altair chart from a duckdb dataframe exported as an arrow table,  but I get this error 

TypeError: Object of type datetime is not JSON serializable

when I cast the field to string everything works fine.

**Comment by amol-** [comment]
I think you can also explore the idea of extending the JSON serialiser with support for datetimes. For example that's what we have done in TurboGears ( https://github.com/TurboGears/tg2/blob/development/tg/jsonify.py#L94-L98 ).

That way you don't have to care about sanitising types explicitly because the json dumper will take care of it for you independently from where that value came from.

**Comment by AlenkaF** [comment]
If you decide to sanitize interchange dataframes on the Python side, you could use `cast` function and cast Timestamp to string to get the correct ISO format, for example:

```python
>>> from datetime import datetime
>>> import pyarrow as pa
>>> arr = pa.array([datetime(2010, 1, 1), datetime(2015, 1, 1)])
>>> arr
<pyarrow.lib.TimestampArray object at 0x12f37a020>
[
  2010-01-01 00:00:00.000000,
  2015-01-01 00:00:00.000000
]
>>> import pyarrow.compute as pc
>>> pc.cast(arr, pa.string())
<pyarrow.lib.StringArray object at 0x12f37a0e0>
[
  "2010-01-01 00:00:00.000000",
  "2015-01-01 00:00:00.000000"
]
```
Note: in case of duration, the error should be raised.

**Comment by mattijn** [comment]
Thanks for responding @AlenkaF! We've to cast dates to full ISO-8601 dates in order to render dates in local time in Altair, where dates cast as string will render as UTC in JavaScript..

**Comment by mattijn** [comment]
Thanks also @amol- for raising ideas! Appreciated!
