### ISSUE TITLE
Label Transform

### ISSUE THREAD

**Issue by tmespe** [altair-viz/altair#3096]
Hi,

I recently started to use Altair and it's a great library. One issue I'm having is on how to avoid overlaps with mark_text. E.g I would like to plot labels on the line ends of a line chart and avoid overlaps. 

I see that this is a feature[ Vega Lite](https://vega.github.io/vega/docs/transforms/label/) with "Transform Label" where you can set "avoidBaseMark" to avoid overlapping labels. 

Is this feature not available in Altair? I have tried searching the documentation, but have not been able to find anything for transform_label or avoidBaseMark.

**Comment by jonmmease** [comment]
Hi @tmespe, it's a little confusing, but the `label` transform you've linked to is a feature of Vega, not Vega-Lite. Altair generates Vega-Lite specifications, which the Vega-Lite JavaScript library compiles into Vega specifications.

The issue is that Vega-Lite does not, as far as I know, support generating Vega specifications that use the label transform. This would be a great feature to have, so I'd recommend opening an issue with the Vega-Lite team at https://github.com/vega/vega-lite/issues.

Thanks!

**Comment by mattijn** [comment]
See also https://github.com/vega/vega-lite/pull/7378

**Comment by tmespe** [comment]
Thanks for the quick replies. I was not aware of the difference between Vega and Vega-lite, and seeing as it's supposedly being worked on by the vega-lite team I will close this issue.
