### ISSUE TITLE
jsonschema 4.18.1 breaks chart rendering

### ISSUE THREAD

**Issue by sean-doody** [altair-viz/altair#3104]
Hey there!

I'm new to Altair and I was continuously running into this bug when trying to render Altair charts (v. 5.0.1) in JupyterLab or VSCode:

```
_RefResolutionError: 'bytes' object has no attribute 'timeout'
```

I was using this example code: 

```python
import altair as alt
from vega_datasets import data

source = data.stocks()

lines = (
    alt.Chart(source)
    .mark_line()
    .encode(x="date", y="price", color="symbol")
)

xrule = (
    alt.Chart()
    .mark_rule(color="cyan", strokeWidth=2)
    .encode(x=alt.datum(alt.DateTime(year=2006, month="November")))
)

yrule = (
    alt.Chart().mark_rule(strokeDash=[12, 6], size=2).encode(y=alt.datum(350))
)


lines + yrule + xrule

```

Turns out it was a `jsonschema` issue. Downgrading to `jsonschema==4.18.0` resolved the problem. All is working now: great library!

**Comment by binste** [comment]
Thank you for reporting this and figuring out that it was the new jsonschema release that caused the issue. This was a regression on the jsonschema side which they just now fixed in a new version 4.18.2. See https://github.com/python-jsonschema/jsonschema/issues/1124 for reference. So upgrading to 4.18.2 should solve it as well 🙂
