### ISSUE TITLE
Object data types are no longer inferred from data frames

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#3177]
Support for inferring the data type from object columns in data frames used to work, but  is not working anymore:

```py
import altair as alt
import pandas as pd

alt.Chart(
    pd.DataFrame({'not_ints': pd.Series([1, 2, 3], dtype='object')})
).mark_circle().encode(x='not_ints')
```

```
NotImplementedError: Non-string object dtypes are not supported yet
```

@jonmmease I think this is a regression from https://github.com/altair-viz/altair/pull/3114 that added support for the dataframe interchange as it used to work fine in Altair 5 (see screenshot below). Do you think it is possible to add a workaround similar to what you have done for datetime data until there is official pyarrow support?

Altair 5.0:
![image](https://github.com/altair-viz/altair/assets/4560057/2d500c1f-18dc-4c41-89ea-aa965c5649cd)

**Comment by jonmmease** [comment]
Yeah, this is from #3114. I don't think the workaround datetime workaround is going to work here because the error message doesn't include enough information to determine the correct type to infer.

I think we could catch NotImplementedErrors exceptions raised from this line:

https://github.com/altair-viz/altair/blob/17e8d07fee3c3d891c9667a14a2a6b3df3d3b581/altair/utils/core.py#L589

And then try again with the pandas implementation (if the datarame is a pandas DataFrame).

I'll take this. Do you think warrants an immediate 5.1.1?

**Comment by mattijn** [comment]
Or maybe using the [`infer_objects()`](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#object-conversion.) function? 
I can imagine doing a 5.1.1 for this

**Comment by jonmmease** [comment]
I'll get this fixed shortly. I'll tag you for review @mattijn, and then you can make the 5.1.1 release at your convenience.
