### ISSUE TITLE
Passing basic polars dataframes to alt.Chart results in Pylance errors

### ISSUE THREAD

**Issue by christopherball** [altair-viz/altair#3294]
I took the default boilerplate chart code from an altair example and simply converted the `cars` Pandas DataFrame to a Polars one (for testing purposes as I am using Polars), and while the code appeared to still execute, Pylance is catching some type issues.  Restarted VSCode and still see the same problem:

![image](https://github.com/altair-viz/altair/assets/5790394/bed0be0b-a224-47fa-8330-3f7790b40904)

**Comment by christopherball** [comment]
Have additionally confirmed this same exact error surfaces with a simple native Polar dataframe to rule out conversion-related issues:

```py
import polars as pl
import altair as alt

df = pl.DataFrame(
    {
        "a": range(5),
        "b": np.random.rand(5),
    }
)

alt.Chart(df).mark_point().encode(
    x="a",
    y="b",
).interactive()
```

**Comment by dangotbanned** [comment]
I was just about to open an issue on this, been having the same issue since I updated to 5.2.0. 

Earlier this week I did some digging, and although I don't know enough about the altair codebase to resolve this, I do have some notes that might speed up a fix for the core devs. 

**Minimal repro**
```python
import altair as alt
import polars as pl

def make_chart(chart: alt.Chart) -> alt.Chart:
    return chart.encode(x="x", y="y").mark_point()

df: pl.DataFrame = pl.DataFrame({"x": [1, 1, 2, 3, 4], "y": [1, 2, 3, 4, 5]})

# all of these produce identical, valid charts
make_chart(alt.Chart(df)) #should be the only type check issue
make_chart(alt.Chart(df.to_arrow()))
make_chart(alt.Chart(df.to_pandas()))
```

**Notes**
- `polars` has pretty extensive type checking, I noticed their `__dataframe__` protocol handling seems different to `altair`
	- [../polars/interchange/protocol.py#L237](https://github.com/pola-rs/polars/blob/96ad535f9ee3ebc53dfaddca7c2e921ad900bb12/py-polars/polars/interchange/protocol.py#L237)
	- [../polars/interchange/dataframe.py#L18](https://github.com/pola-rs/polars/blob/96ad535f9ee3ebc53dfaddca7c2e921ad900bb12/py-polars/polars/interchange/dataframe.py#L18)
	- [../polars/interchange/from_dataframe.py#L17](https://github.com/pola-rs/polars/blob/96ad535f9ee3ebc53dfaddca7c2e921ad900bb12/py-polars/polars/interchange/from_dataframe.py#L17)
- A difference I see is using `ABC` vs `Protocol`. 
	- Maybe this would be resolved by registering each type as a virtual subclass?
	- I know that for protocols, at least, you wouldn't need to do this explicitly
	- [altair/utils/_dfi_types.py#L380](https://github.com/altair-viz/altair/blob/4d06175d305e18739aae1b89eaafdff08e4db9cd/altair/utils/_dfi_types.py#L380)

**Comment by jonmmease** [comment]
Thanks for the reports @christopherball and @dangotbanned 

We can probably fix this particular issue by changing to a Protocol definition as @dangotbanned suggested. But I just tried running pyright on our code base and it turns up hundreds of errors that mypy doesn't flag, so I'm not sure what to make of this.  It may be difficult to test this change in isolations without a major effort to satisfy pyright.

@binste do you have any thoughts here?

**Comment by binste** [comment]
Thanks for the report @christopherball  and the very useful debugging information @dangotbanned! Fully agree, we should switch the definitions to Protocols instead of ABC as other libraries (of course) don't use subclasses of our ABCs.

I'll submit a PR soon to fix this. Just switching to Protocols does not yet fully solve it, there is somehow some other difference in the protocols that Polars uses and that we use. I'll try to track it down.
