### ISSUE TITLE
`MarkDef` docs show wrong docstring

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#3370]
Follow up on https://github.com/altair-viz/altair/pull/3266

The docs on `MarkDef` show that it takes the composite mark strings `'boxplot"` etc as arguments, but this is not correct. Those need to be passed to `CompositeMarkDef` instead. The type hint is correct and does not include the composite marks:

![image](https://github.com/altair-viz/altair/assets/4560057/f0bd0007-f6c2-4fb2-a631-9a734e4d9075)

I *think* the docstring is fetched [from `mark.ts` in Vega-Lite](https://github.com/vega/vega-lite/blob/5b7f963f52dd3483687d0608a045cd0f5aa4cbdb/src/mark.ts#L535-L541), where there is only a generic definition, so I'm not sure that we can actually separate it on the Altair level. We might even argue we don't need to list the individual strings now that they are already included in the type hint (but again, not sure how to exclude that from being fetched from VL).

**Comment by binste** [comment]
I think that this is ideally changed in VL so that we can just can keep taking these descriptions from the VL schema. Also, the VL schema itself would also be improved by it.

Docstring seems to come from that place you linked to and is then used for `MarkDef` [here](https://github.com/vega/vega-lite/blob/5b7f963f52dd3483687d0608a045cd0f5aa4cbdb/src/mark.ts#L611) and for `CompositeMarkDef` [here](https://github.com/vega/vega-lite/blob/5b7f963f52dd3483687d0608a045cd0f5aa4cbdb/src/compositemark/common.ts#L28). There should probably a separate docstring for these two so that it matches with the type hints. Would you be ok if we move this to the VL repo?

**Comment by joelostblom** [comment]
Great, I didn't see that there were separate definitions of `MarkDef` and `CompositeMarkDef`; hopefully it can just be changed in each one of those classes then. I couldn't transfer to another org so I opened https://github.com/vega/vega-lite/issues/9290
