### ISSUE TITLE
Cumulative count aggregation

### ISSUE THREAD

**Issue by nipunbatra** [altair-viz/altair#348]
Many thanks for putting in so much effort for Altair! Huge fan!

I was searching for Altair related questions on StackOverflow (SO). Found this [question](https://stackoverflow.com/questions/40933985/cumulative-count-with-altair), which requires cumulative count aggregation.

I think as of today, Altair does not have a function for cumulative count. Thus, I answered on the SO question by doing the aggregation in Pandas. 

I wonder if the function needs to be defined in Vega or Altair? This function might not be super priority. However, this issue may act as  a sweet first PR.

**Comment by jakevdp** [comment]
Cumulative counts are not really an aggregation (they map vector->vector rather than vector->value), so they'd probably rather be categorized as a transformation operation. In any case, I haven't seen plans to put a cumulation operator in Vega-Lite, and that would be the place to explore making this kind of contribution.

**Comment by jakevdp** [comment]
It would probably require another category of transformation operation: https://vega.github.io/vega-lite/docs/transform.html

**Comment by kanitw** [comment]
Cc: @jheer @arvind

**Comment by jakevdp** [comment]
This can now be done via the [window transform](https://altair-viz.github.io/user_guide/transform.html?highlight=window#user-guide-window-transform)
```python
alt.Chart(data).transform_window(
    x_cuml='sum(x)',
    frame=[None, 0]
)
```
