### ISSUE TITLE
Upgrade to Vega-Lite 2.3

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#569]
https://github.com/vega/vega-lite/releases/tag/v2.3.0 introduces a few schema changes.

**Comment by jakevdp** [comment]
Thanks! I'll take a look.

**Comment by jakevdp** [comment]
Are x/y encodings with ``type='latitude'`` and ``type='longitude'`` still valid? If so would you consider that form deprecated? Right now our shorthand type parser recognizes "latitude" and "longitude" as types like "nominal", "ordinal", etc. Do you think we should remove that?

**Comment by domoritz** [comment]
Yes, prefer to use `latitude: {type: 'quantitative'}`. See https://github.com/vega/vega-lite/issues/3353. @kanitw can provide more details.

**Comment by kanitw** [comment]
Yes, type="latitude/longitude" are deprecated.  One of the reason I make this change sooner than later is so that Altair doesn't have to expose type="latitude/longitude" at all. 

I think users better use 
```
.encode(
    longitude='lng',
    latitude='lat'
)
```
rather than 

```
.encode(
    x='lng',  
    y='lat'
)
```
as x is actually a function of longitude and latitude   (same for y).   So  the old `type='latitude'` and `type='longitude'` are a bit misleading.

**Comment by jakevdp** [comment]
Thanks for the clarification! I'll remove the lat/long types from the Altair API.

**Comment by jakevdp** [comment]
FYI, there are a number of places in the description where it still mentions type latitude/longitude, e.g. https://github.com/vega/schema/blob/master/vega-lite/v2.3.0.json#L1061

**Comment by jakevdp** [comment]
Done in #571
