### ISSUE TITLE
JupyterLab functionality in altair 2.0?

### ISSUE THREAD

**Issue by choldgraf** [altair-viz/altair#608]
I can't figure out how to get plots to show up in JupyterLab...the docs suggest there's a function called `enable_mime_rendering`, but I can't find it anywhere in the code. Did this get deprecated?

**Comment by chhenault** [comment]
Hello,
Probably same issue here. Graph do not show, only getting plain text. cf image below that is a copy-paste of the example on the home page.
If it helps, I am running on the latest version of Jupyter Lab and I have vega3-extension v0.14.4 enabled
Looking forward to playing with Altair ; congrats on the release !

![image](https://user-images.githubusercontent.com/28479323/37610189-42519928-2b9f-11e8-8980-516c022332e5.png)

**Comment by jakevdp** [comment]
``enable_mime_rendering`` is no longer necessary... the instructions in the README are out of date. Please use the install instructions at https://altair-viz.github.io/getting_started/installation.html

**Comment by jakevdp** [comment]
@chhenault I think your problem is different. It looks to me like vega3 is not enabled in the JupyterLab instance that you are running. Make certain to follow the instructions at https://altair-viz.github.io/getting_started/installation.html, and then re-launch jupyterlab and it should (hopefully :smile:) work.

**Comment by choldgraf** [comment]
yep, working on it now :-)

**Comment by chhenault** [comment]
Hello @jakevdp,
Many thanks for getting back to me so quickly. 

I have been through the documentation indeed (esp.[https://altair-viz.github.io/user_guide/display.html]) and relaunched JupyterLab to no avail, unfortunately. Running the `jupyter labextension list` command I believe the vega-3 extension is enabled (screenshot below). However I am unsure as how to check whether the extension is indeed bound to my JupyterLab instance ; could that be the source of the problem?

![image](https://user-images.githubusercontent.com/28479323/37650333-f0a025b8-2c34-11e8-823a-717c6f45f5e8.png)

**Comment by jakevdp** [comment]
OK... @chhenault what output do you see in the notebook when you paste the code block from here? http://0.0.0.0:8000/getting_started/overview.html#overview

**Comment by chhenault** [comment]
Still the same text description of the data ... 

![image](https://user-images.githubusercontent.com/28479323/37671865-f55ac9c2-2c6c-11e8-8158-6ecf73c5b6b3.png)

**Comment by jakevdp** [comment]
What version of JupyterLab are you running?

**Comment by chhenault** [comment]
Hi @jakevdp,
I was running version 0.31.12 but could not get it to work despite checking all the components were fine. I believe the issue was with my Anaconda install as, when I uninstalled and re-installed a MiniConda version it started working.

Sorry for the fuss and many thanks for your support !

Happy to start enjoying Altair new functionalities at last :smile:.

**Comment by jakevdp** [comment]
OK... I suspect the issue was that you were installing components in different kernels. Glad you got it working!

**Comment by pagpires** [comment]
Same issues here, only see a Chart repr (text) rather than a plot. 1. Also using Anaconda in Windows; 2. tried both jupyterlab and jupyter notebook (with this additional alt.renderers.enable('notebook') in the notebook), no luck; 3. sure the environment is using jupterlab 0.31 with vega3-extension and notebook is 5.4.     


However.. Once I recreated a new environment and reinstall every packages, it worked...
