### ISSUE TITLE
Is it possible to set the extent and zoom with a mark_geoshape?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#632]
Say, for instance, I wanted to zoom in on Los Angeles County on map of [U.S. states](https://altair-viz.github.io/gallery/us_state_capitals.html) example included in the documentation.

![visualization](https://user-images.githubusercontent.com/9993/37754144-894d8e94-2d5d-11e8-80a3-6859b8e143bc.png)

Could I set the "scale" or otherwise change the extent so that LA, or any other location, was at the center of the map?

**Comment by jakevdp** [comment]
No, this is not supported at the moment. See https://github.com/vega/vega-lite/issues/3305

**Comment by kot-behemoth** [comment]
I found a workaround, and wrote a small post about it
[here](https://gist.github.com/kot-behemoth/01949f8e9a94d9d343bd62e45adb41a1).
I'll just paste the contents here, in case the link dies later.

# "Zooming in" on a map in Altair

Altair [doesn't allow making maps (aka `mark_geoshape`)
interactive][altair-issue], since geo markers do not yet support interaction in
Vega-Lite ([vega/vega-lite#3306][vega-lite-issue]).

I stumbled upon this problem when I needed to only display information in only
one US state, but the [official example][map-example] shows the full map of the
US. Furthermore, it's not possible to set a fixed zoom, so that only one state
is visible when the map is shown.

I found a solution by essentially only displaying the state I need, instead of
the whole map. For that, I had to find the relevant geometry file. I found a
GeoJson file for the state I was interested in from [world.geo.json
repo](https://github.com/johan/world.geo.json) (state files are located
[here](https://github.com/johan/world.geo.json/tree/master/countries/USA), below
the folders). Then, I loaded it into Geojson.io [geojson.io](http://geojson.io),
and exported as TopoJson (I'm sure it could be done via better means, but this
was the quickest). Finally, I simply used the local file in my notebook as such:

``` python
state = alt.topo_feature('./map.topojson', 'collection')

(
    alt.Chart(state)
    .mark_geoshape(
        fill='white',
        stroke='black'
    )
    .project(type='albersUsa')
)
```

Note that the second argument to `alt.topo_feature` can be found in the topojson
file like this:

``` json
{
  "type": "Topology",
  "objects": {
    "collection": {     <--------- this is the argument
      "type": "GeometryCollection",
      "geometries": [
        {
          "type": "Polygon",
          "id": "USA-TX",
          "properties": {
            "fips": 48,
            "name": "Texas"
          },
          ...
```

Hope this helps while vega-lite gets the required functionality!

[altair-issue]: https://github.com/altair-viz/altair/issues/679
[vega-lite-issue]: https://github.com/vega/vega-lite/issues/3306
[map-example]: https://altair-viz.github.io/gallery/us_state_capitals.html
