### ISSUE TITLE
Layered charts error

### ISSUE THREAD

**Issue by sawula** [altair-viz/altair#687]
In Jupyter notebook, Individual charts render fine, but not layers. Tried both formats ('+' or 'alt.layers'). Running on a freshly installed Anaconda distribution.  Details about versions in pdf below.  I created a minimal pandas dataframe to test, bc I was worried that the issue was with reading from the vega dataset, with which I received the same error.

Apologies if attaching the pdf is not the way to go.  I welcome advice on issue posting conventions. 

[altair 2 Layer issue.pdf](https://github.com/altair-viz/altair/files/1865556/altair.2.Layer.issue.pdf)

Thx

**Comment by jakevdp** [comment]
This looks like an error that was in previous versions of the ``vega3`` renderer. Try updating vega3 and then re-installing the jupyter extension
```
$ pip install -U vega3
$ jupyter nbextension install --sys-prefix --py vega3
```
You should have vega3 version 0.5 or newer.

Also, I would do this from the command line, **not using ! within the jupyter notebook**, because often executable paths and kernel paths are mismatched, and that's difficult to debug unless you know what you're looking for.

Also, the entire Jupyter notebook server has to be restarted after installing the nbextension, so installing it within the notebook will not result in it working right away.

Overall, I'd say just follow the installation instructions here **exactly**: https://altair-viz.github.io/getting_started/installation.html#installing-altair-with-jupyter-notebook

**Comment by jakevdp** [comment]
Were you able to fix this issue?

**Comment by sawula** [comment]
I switched to JupyterLab as you suggested and everything works

**Comment by jakevdp** [comment]
OK, I'll close the issue then. Thanks!
