### ISSUE TITLE
savechart doc fix

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#722]
`savechart` docs note "Supported formats are json, html, png, svg" but the `format` parameters are "the format to write: one of [‘json’, ‘html’, ‘png’, ‘eps’]. If not specified, the format will be determined from the filename.". Presumably eps is out of the picture.

**Comment by jakevdp** [comment]
Yes, for some reason my fingers always write eps when my brain is thinking svg. It's happened before, I'm certain it will happen again :smile:

It needs to be fixed in a few places: https://github.com/altair-viz/altair/search?q=eps&type=Code

Feel free to send a PR changing "eps" to "svg", otherwise I can take care of it
