### ISSUE TITLE
Argument `width` on `configure_view` does not work when x axis is categorical

### ISSUE THREAD

**Issue by bartaelterman** [altair-viz/altair#802]
In the following example, I created a chart (based on an example from the gallery) but set the x axis to a categorical variable. In that case, the `chart.configure_view(width=700)` does not change the width of the chart. It does work when the x axis contains a numerical variable.

```
import altair as alt
from vega_datasets import data

iris = data.iris()

chart = alt.Chart(iris).mark_point().encode(
    x='species',
    y='petalLength'
)

chart.configure_view(width=700)
```

**Comment by jakevdp** [comment]
Hi – the problem is that the ``configure`` methods basically set top-level chart themes, and by design those theme settings are of the lowest priority to the renderer... if chart elements indicate different values, then those more specific values are used.

In the case of categorical marks, the number of categories by default determines the width or height of the chart. I believe this decision was made to prevent the creation of absurdly wide or narrow bars, for example. The fact that the width only applies in a quantitative case is deliberate, and [documented](https://altair-viz.github.io/user_guide/configuration.html#view-configuration).

If you'd like to override the default bar width, you can most easily do it by setting the ``width`` or ``height`` chart property, e.g.
```
chart.propoerties(
    width=700
)
```
