### ISSUE TITLE
Installation instructions give precedence to conda-forge over defaults, causing package weirdness

### ISSUE THREAD

**Issue by makmanalp** [altair-viz/altair#860]
In my case it results in weird things like conda wanting to downgrade conda:

![screen shot 2018-05-17 at 11 23 47 am](https://user-images.githubusercontent.com/161965/40187913-b865b34c-59c6-11e8-9668-099ade612cca.png)

See https://github.com/conda/conda/issues/6941.

The solution there to add conda-forge to my .condarc with lower priority than defaults works but perhaps is a bit verbose and invasive for installation instructions. Perhaps we can split it into two lines to install just jupyterlab alone, and then `-c conda-forge altair vega_datasets`? Or is this on purpose because we perhaps need a forge version of jupyterlab also?

**Comment by jakevdp** [comment]
The installation instructions contain a single line, because I find that every extra installation step approximately doubles the number of users that write to me with problems :smile:

I didn't include information about channels, environments, etc. because it would only serve to confuse beginners, and I presume that the people for whom it would not be confusing already understand how to adapt the simple instructions to suit their own specific needs.

**Comment by makmanalp** [comment]
OK, I think that's fair, thanks!
