### ISSUE TITLE
DOC: Axis format docs link in API reference doesn't work.

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#878]
It links here, which is a 404 https://altair-viz.github.io/user_guide/format.html

![screenshot from 2018-05-21 09-33-25](https://user-images.githubusercontent.com/9993/40318626-110cfa58-5cda-11e8-984a-18a23a60ba43.png)

**Comment by jakevdp** [comment]
This was reported previously: #791

It's not easy to fix because the text in question comes from the description within the schema, is inserted into the automatically generated class, and then is rendered to this webpage by sphinx. Fixing it would require parsing the markdown during the code generation process and replacing bad links with alternates.

Feel free to tackle that, feel free :smile:

**Comment by jakevdp** [comment]
Other options:

- restructure Altair's docs to match the structure of vega-lite, so that these relative URLs resolve correctly
- fix upstream in vega-lite by converting all their relative URLs to absolute URLs. Then the links would go to the relevant vega-lite pages.

**Comment by kanitw** [comment]
If you want to replace all the links in the docs, one hacky solution would be having a JS script that has all indices of "oldUrl" => "newUrl". For each tuple, you can then run `document.querySelector` to query for href=oldUrl and replace the href attribute with new url.   

This won't work for API's autocompletion yet though.  But I guess the same trick can be applied to the class autogeneration code.  

> fix upstream in vega-lite by converting all their relative URLs to absolute URLs. Then the links would go to the relevant vega-lite pages.

This should definitely be done. I'll fix this in Vega-Lite.

**Comment by jakevdp** [comment]
I love when an upstream fix magically happens :smile:
