### ISSUE TITLE
How to get tickCount passed down to the axis?

### ISSUE THREAD

**Issue by reckoner** [altair-viz/altair#906]
I'm trying to do something like this:

    chart.configure_axisY(labelFontSize=14,tickCount=5).\
        mark_bar(size=18).\
        encode(y=alt.Y('Year:T',timeUnit='year'),x='median(Horsepower)').\
        properties(width=200)

But it doesn't like `tickCount` there, but Vega-lite does.

I'm confused here.

**Comment by jakevdp** [comment]
``tickCount`` is not a valid ``configure`` argument, either in Altair or in Vega-Lite.

It is valid as an ``Axis`` argument, though; e.g.

```python
chart.encode(
   y=alt.Y('Year:T', axis=alt.Axis(tickCount=5)
)
```

**Comment by reckoner** [comment]
Thanks! I'm new to Altair and I'm having a hard time understanding why certain options go into the `configure_*` functions as opposed into the `alt.Y` objects. I can't get autocomplete to work for either of these functions so that is an additional complication. For example, why doesn't `labelFontSize` go into `alt.Y` instead of into `configure_axisY`?

**Comment by jakevdp** [comment]
> I'm having a hard time understanding why certain options go into the configure_* functions as opposed into the alt.Y objects

That would be a question for the Vega-Lite developers. Altair simply provides an interface to the grammar of Vega-Lite. But the Altair doc strings will list exactly what attributes any function accepts, so I would check there.

As for tab-completion, it will only work if the interpreter can trace what method is being called. So, for example, 
```python
alt.Chart.configure_<TAB>
```
will work, whereas
```python
alt.Chart(data).encode(x='foo').configure_<TAB>
```
will not, because the interpreter doesn't do any inference on return types of chained methods.

**Comment by jakevdp** [comment]
In general, ``configure_*`` methods should be thought of as a way of specifying a theme that applies to every panel in a chart. I suspect ``tickCount`` is left out because it makes more sense to specify that for a particular panel than to specify it as a chart theme.
