### ISSUE TITLE
Explore using vegascope for rendering outside notebook

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#919]
[vegascope](https://github.com/diana-hep/vegascope)

It's not immediately clear how much of an advantage this has over the ``chart.serve()`` architecture we currently use.

**Comment by jpivarski** [comment]
It's nearly the same thing: using Python's built-in webserver to present Vega graphics, *except*

   * While I see threading logic in `altair/utils/server.py`, when I tried it (latest pip version), the terminal locked up until I control-C'ed the server. Being able to use the Python REPL interactively while the most recent plot is visible is crucial.
   * VegaScope opens a server-sent `EventSource` on the HTML page, so that the user can send additional plots from the Python REPL. These two features together reproduce the Gnuplot experience.
   * Because of the server-sent events, the Python process knows how many connections are viewing the page (and from where). If you open the web server to the world for your own convenience, you'd want to know if anyone else is listening in.
   * When the Python process disconnects, the HTML page turns grey as a hint to the user that they should stop waiting for updates.
   * Remote, local, and ssh-tunnel cases are distinguished (as classes) because being able to locally view graphics from a remote Python process is an important use-case, but one that raises security concerns.
   * The entire functionality is rolled up into a single file (server Python, client HTML and Javascript, even the Vega libraries) for very difficult to access sites. In some scenarios, you can't even run "pip" or access the web; the only way to install software is through `scp`. (Poor souls, indeed!) Sometimes, *this* is the reason one can't set up Jupyter, so VegaScope, as the anti-Jupyter, accommodates this extreme situation.

It wouldn't be unreasonable to port the desired features into `chart.serve()`, rather than depending on VegaScope. That last bullet point could be hard to swallow. (I don't know: maybe I should simply *generate* the single-file version from a more reasonably designed library.)

It's mostly the first two bullet points (emulating a Gnuplot-style plot window) that are important.

**Comment by jpivarski** [comment]
Oh, I almost forgot:

   * Pushing "save as PNG", "save as SVG" from the Python process (again through server-sent events). That appears as a pop-up in the web browser, so it requires user intervention to enable (over and over again as new canvases pick random ports).

**Comment by jakevdp** [comment]
proof of concept for using vegascope as a renderer via entrypoints: https://github.com/diana-hep/vegascope/pull/1

**Comment by jakevdp** [comment]
It works now!
