### ISSUE TITLE
Possible to use Altair visuals in static site?

### ISSUE THREAD

**Issue by reckoner** [altair-viz/altair#944]
I'm trying to build a static site for deployment on AWS S3 and CloudFront. Can I somehow embed Altair visualizations in such a static site? 

Thanks!

**Comment by jploudre** [comment]
It's definitely possible. I'm doing this same thing. If you embed the JSON files, you can use Vega-Embed and the various other needed javascripts in the the <head> of your document. For me, it was actually easier to generate PNG files for use -- I'm just making some plain graphs. But when I want interactivity, I'll go back to JSON files and Vega embed.

**Comment by Skyentific** [comment]
- create chart using altair in python: **chart**
- return chart.to_json() from a REST endpoint using flask: **/data/chart.json**
- use vega embed in a HTML page: **vegaEmbed("#view", '/data/chart.json')**

**Comment by jakevdp** [comment]
Hi @reckoner – the other comments offer good advice. I wanted to point you to the section of the documentation that talks about this: https://altair-viz.github.io/user_guide/saving_charts.html#html-format

If there's anything there that's unclear, please let me know so that we can improve the docs. Thanks!

**Comment by reckoner** [comment]
Thanks for the great tips! Let me see how far I can get with this.
